### ISSUE TITLE
proguard-rules.pro example doesn't work

### ISSUE THREAD

**Issue by DanMossa** [MaikuB/flutter_local_notifications#1044]
Hello!

I was reading through the documentation and I understand that I have to set up proguard-rules.pro for the Android side.

The app works when running with `flutter run --release` and also when just debugging. But the app crashes when using the built apk

I copy and pasted the proguard-rules.pro in the example folder and the issue is not resolved.

Thanks!

https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/example/android/app/proguard-rules.pro

This is my logcat that only occurs on the branch using flutter_local_notifications

```
2021-02-18 18:49:17.673 8637-8637/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ovaperiodtracker, PID: 8637
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.ovaperiodtracker/com.ovaperiodtracker.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.ovaperiodtracker.MainActivity" on path: DexPathList[[zip file "/data/app/~~_A7bms891HWxOwYwxjoYmw==/com.ovaperiodtracker-dz0zsSp93fxn8F6VPOxTnA==/base.apk"],nativeLibraryDirectories=[/data/app/~~_A7bms891HWxOwYwxjoYmw==/com.ovaperiodtracker-dz0zsSp93fxn8F6VPOxTnA==/lib/arm64, /data/app/~~_A7bms891HWxOwYwxjoYmw==/com.ovaperiodtracker-dz0zsSp93fxn8F6VPOxTnA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3347)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.ovaperiodtracker.MainActivity" on path: DexPathList[[zip file "/data/app/~~_A7bms891HWxOwYwxjoYmw==/com.ovaperiodtracker-dz0zsSp93fxn8F6VPOxTnA==/base.apk"],nativeLibraryDirectories=[/data/app/~~_A7bms891HWxOwYwxjoYmw==/com.ovaperiodtracker-dz0zsSp93fxn8F6VPOxTnA==/lib/arm64, /data/app/~~_A7bms891HWxOwYwxjoYmw==/com.ovaperiodtracker-dz0zsSp93fxn8F6VPOxTnA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(Unknown Source:0)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1253)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3335)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7660) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
2021-02-18 18:49:17.676 1606-2112/? W/ActivityTaskManager:   Force finishing activity com.ovaperiodtracker/.MainActivity
```

EDIT: I feel like i've read this 100 times
https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#release-build-configuration

> Before creating the release build of your app (which is the default setting when building an APK or app bundle) you will need to customise your ProGuard configuration file as per this link. Rules specific to the GSON dependency being used by the plugin will need to be added. These rules can be found here. The example app has a consolidated Proguard rules (proguard-rules.pro) file that combines these together for reference here.

To me this says that I need to customize my proguard-rules.pro file. I need to add a psecific GSON rules. But the proguard-rules.pro file has everything needed

EDIT 2: I currently am not using an icon or anything. The notification shows a gray circle. Unclear if this matters

**Comment by balajibrk** [comment]
Have you resolved this issue, I'm also facing the same issue. Could you help me resolve this issue
Thanks in advance :)

**Comment by MaikuB** [comment]
If you're trying to report a bug then you need to use the bug report template and provide everything that's specified there. This includes a minimal sample app that can reproduce the bug. Currently there's none and the stack trace provided doesn't point to an issue with the plugin. Furthermore, the example app compiles and runs in release mode

**Comment by balajibrk** [comment]
Thanks @MaikuB

**Comment by balajibrk** [comment]
Where do I have to map the progaurd-rules file

**Comment by balajibrk** [comment]
By adding this `-keep class com.dexterous.** { *; }` in`progaurd-rules.pro` file resolved this issue.
Reference, https://stackoverflow.com/questions/58134023/flutter-local-notification-causing-crash-only-in-the-apk-version

**Comment by MaikuB** [comment]
Closing as issue has been reopened without further info from OP and @balajibrk has resolved their issue
