### ISSUE TITLE
Call to cancelAll prints error stacktrace due to code shrinking

### ISSUE THREAD

**Issue by devjeff** [MaikuB/flutter_local_notifications#1060]
**Describe the bug**
When calling the method "cancelAll" to cancel all displayed notifications, an error with a stacktrace is printed. The code still seems to work, as the notifications are actually cancelled. Plugin version is: 1.3.0. Here is a log output:

<details>
  <summary>Click to expand!</summary>
2021-02-26` 12:59:16.876 28466-28466/net.lupiter.haeringClient E/MethodChannel#dexterous.com/flutter/local_notifications: Failed to handle method call
    java.lang.RuntimeException: Missing type parameter.
        at f.g.b.O.a.getSuperclassTypeParameter(:84)
        at f.g.b.O.a.<init>(:62)
        at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin$1.<init>(:219)
        at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.loadScheduledNotifications(:219)
        at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.cancelAllNotifications(:931)
        at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(:767)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(:233)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(:85)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(:818)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:174)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

2021-02-26 12:59:16.899 28466-28528/net.lupiter.haeringClient E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(error, Missing type parameter., null, java.lang.RuntimeException: Missing type parameter.
        at f.g.b.O.a.getSuperclassTypeParameter(:84)
        at f.g.b.O.a.<init>(:62)
        at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin$1.<init>(:219)
        at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.loadScheduledNotifications(:219)
        at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.cancelAllNotifications(:931)
        at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(:767)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(:233)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(:85)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(:818)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:174)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
</details>

I've copied the proguard rules from the example app, but unfortunately it doesn't prevent the error.

**To Reproduce**

1. Enable code shrinking
2. Build an app, which provides option to cancel all notifications
3. Call the cancelAll method
4. See error in log output

**Expected behavior**
There should be no error in the log output.

**Comment by MaikuB** [comment]
Are you actually using 1.3.0? If so, i then please update to a recent version. 1.3.0 is quite an old version and would have had different rules back then, which you can find by making use of the Git tags. I imagine you took the rules from the current version of the plugin. If you're going to choose to stick with older versions and experience issues then you'd need to look at keeping your own fork and address issues found in them since the plugin has changed a fair bit since 1.3.0 and some of these changes include fixes.

**Comment by devjeff** [comment]
Hey, thanks for the qucik response. I've updated the plugin to the latest version and I'm still facing this issue. Still, I've noticed that it only occurs for the debug build. I've manually activated the code shrinking in the app/build.gradle for the debug build type as well by setting:
```
  shrinkResources true
  minifyEnabled true 
  proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
```
Maybe the Flutter release build applies some additional proguard rules to keep certain classes.

**Comment by MaikuB** [comment]
Looks like the issue here is you're doing it with the debug build. Code shrinking etc is typically done for release builds and the Flutter tooling does this and applies Proguard rules automatically only on release build, some of which includes rules specific to Flutter. You can see this at https://github.com/flutter/flutter/blob/fc77610dd6e4c47ede2dcc383ebf0ecac9e694b0/packages/flutter_tools/gradle/flutter.gradle#L186. If you want to stick with using debug build then you'll need to do more setup for it to do with

**Comment by MaikuB** [comment]
Forgot to add there may be other things it does for release things. My recommendation here is you should be testing this with release builds and I can't provide more guidance on what you'd need to look at with regards to applying code shrinking for debug builds. If you stick with doing debug builds then you'll need to dig further to see what the Flutter tooling does and potentially seek help elsewhere. I've yet to see the issue you reported for happen for release builds

**Comment by devjeff** [comment]
It didn't occur for release builds. Therefore, I think we can close the issue, because it only occurs for debug builds, which are used for testing only anyway.
