### ISSUE TITLE
java.lang.IllegalArgumentException: NotificationChannelGroup doesn't exist

### ISSUE THREAD

**Issue by julianschmuckli** [MaikuB/flutter_local_notifications#1158]
As soon as I want to setup the notification with Notification channels for Android, I get the following error:

```
E/MethodChannel#dexterous.com/flutter/local_notifications(29685): Failed to handle method call
E/MethodChannel#dexterous.com/flutter/local_notifications(29685): java.lang.IllegalArgumentException: NotificationChannelGroup doesn't exist
E/MethodChannel#dexterous.com/flutter/local_notifications(29685):       at android.os.Parcel.createException(Parcel.java:2075)
E/MethodChannel#dexterous.com/flutter/local_notifications(29685):       at android.os.Parcel.readException(Parcel.java:2039)
E/MethodChannel#dexterous.com/flutter/local_notifications(29685):       at android.os.Parcel.readException(Parcel.java:1987)
E/MethodChannel#dexterous.com/flutter/local_notifications(29685):       at android.app.INotificationManager$Stub$Proxy.createNotificationChannels(INotificationManager.java:3186)
E/MethodChannel#dexterous.com/flutter/local_notifications(29685):       at android.app.NotificationManager.createNotificationChannels(NotificationManager.java:714)
E/MethodChannel#dexterous.com/flutter/local_notifications(29685):       at android.app.NotificationManager.createNotificationChannel(NotificationManager.java:700)
E/MethodChannel#dexterous.com/flutter/local_notifications(29685):       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.setupNotificationChannel(FlutterLocalNotificationsPlugin.java:756)
E/MethodChannel#dexterous.com/flutter/local_notifications(29685):       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotificationChannel(FlutterLocalNotificationsPlugin.java:1217)
E/MethodChannel#dexterous.com/flutter/local_notifications(29685):       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:980)
E/MethodChannel#dexterous.com/flutter/local_notifications(29685):       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#dexterous.com/flutter/local_notifications(29685):       at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#dexterous.com/flutter/local_notifications(29685):       at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#dexterous.com/flutter/local_notifications(29685):       at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#dexterous.com/flutter/local_notifications(29685):       at android.os.MessageQueue.next(MessageQueue.java:363)
E/MethodChannel#dexterous.com/flutter/local_notifications(29685):       at android.os.Looper.loop(Looper.java:176)
E/MethodChannel#dexterous.com/flutter/local_notifications(29685):       at android.app.ActivityThread.main(ActivityThread.java:8387)
E/MethodChannel#dexterous.com/flutter/local_notifications(29685):       at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#dexterous.com/flutter/local_notifications(29685):       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/MethodChannel#dexterous.com/flutter/local_notifications(29685):       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
E/MethodChannel#dexterous.com/flutter/local_notifications(29685): Caused by: android.os.RemoteException: Remote stack trace:
E/MethodChannel#dexterous.com/flutter/local_notifications(29685):       at com.android.server.notification.PreferencesHelper.createNotificationChannel(PreferencesHelper.java:669)
E/MethodChannel#dexterous.com/flutter/local_notifications(29685):       at com.android.server.notification.NotificationManagerService$10.createNotificationChannelsImpl(NotificationManagerService.java:3003)
E/MethodChannel#dexterous.com/flutter/local_notifications(29685):       at com.android.server.notification.NotificationManagerService$10.createNotificationChannels(NotificationManagerService.java:3024)
E/MethodChannel#dexterous.com/flutter/local_notifications(29685):       at android.app.INotificationManager$Stub.onTransact(INotificationManager.java:1287)
E/MethodChannel#dexterous.com/flutter/local_notifications(29685):       at android.os.Binder.execTransactInternal(Binder.java:1028)
E/MethodChannel#dexterous.com/flutter/local_notifications(29685): 
I/flutter (29685): ---------------
E/flutter (29685): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: type 'PlatformException' is not a subtype of type 'String'
```

I have defined the following Notification channel, which is also using the easy_localization library:

```dart
static AndroidNotificationChannel _messagesReceived =
      AndroidNotificationChannel(
          'message_received', // id
          tr("messages.messages"), // title
          tr("messages.permissionMessages"), // description
          importance: Importance.max,
          ledColor: Config.appIconColor,
          groupId: "default",
          showBadge: true);
```

```dart
try {
  if (Platform.isAndroid) {
    await _flutterLocalNotificationsPlugin
        .resolvePlatformSpecificImplementation<
            AndroidFlutterLocalNotificationsPlugin>()
        ?.createNotificationChannel(_messagesReceived);
  }
} catch (e) {
  print("---------------");
  debugPrint(e);
}
```

As you can see, the catched error does produce a PlatformException, which cannot be handled by the plugin.

**Expected behavior**
The problem causes, that the setup for Android cannot be completed correctly, since there is no NotificationChannelGroup. 

**Versions**
flutter_local_notifications: ^5.0.0+1

**Comment by MaikuB** [comment]
Could you please provide a link to a minimal app that can reproduce the problem

**Comment by julianschmuckli** [comment]
I solved it by removing the `groupId: "default"` attribute from the `AndroidNotificationChannel`.

**Comment by Jonny1987** [comment]
I'm having this issue too...surely local notifications should be creating the group with that groupId?

**Comment by amrgetment** [comment]
my solution is to create a channel group by
`createNotificationChannelGroup` before `createNotificationChannel`
