### ISSUE TITLE
iOS: Version 5.0.0+4 attachment not working

### ISSUE THREAD

**Issue by offline-first** [MaikuB/flutter_local_notifications#1166]
iOS image attachment no longer works since the latest version. 
5.0.0+3 still works!

**Comment by MaikuB** [comment]
Please provide a link to a minimal app that can reproduce the problem. I would suspect you have weird issue on your environment as there were no changes to the plugin itself in 5.0.0+4. The only change was an update to the example app and that was only on the Android side

**Comment by offline-first** [comment]
Ok, the problem has nothing to do with the version. I had the same problem again now. After I overwrote the notification without the attachment and then fired again with the attachment, the notification works again as expected. I will get back to you as soon as I know more and provide the source code.

**Comment by outailounni** [comment]
@offline-first  Hey sir, can you please share the sample of code of firing a local notification with Attachment ? 
I'm really struggling with the filepath

**Comment by offline-first** [comment]
@outailounni you need to copy the attachments to application directory (android) or temp directory (iOS)

```dart
Future<String> copyFromAssetsToAppDir(String fileName)async{
    final isIos = Platform.isIOS;
    final directory = isIos ? await getTemporaryDirectory() : await getApplicationDocumentsDirectory();
    final path = isIos ? "${directory.path}/${DateTime.now().millisecondsSinceEpoch}_$fileName" : "${directory.path}/$fileName";
    final file = File(path);
    if(!isIos){
      if(await file.exists()){
        return path;
      }
    }
    final imageBytes = await rootBundle.load('assets/$fileName');
    final bytes = imageBytes.buffer.asUint8List();
    await file.writeAsBytes(bytes);

    return path;
  }
```

**Comment by outailounni** [comment]
thank you so much !

**Comment by offline-first** [comment]
Hello @MaikuB here is my log:

```adb
flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: PlatformException(Error 100, Invalid attachment file URL, UNErrorDomain, null)
flutter: 
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
<asynchronous suspension>
#2      IOSFlutterLocalNotificationsPlugin.zonedSchedule (package:flutter_local_notifications/src/platform_flutter_local_notifications.dart:471:5)
<asynchronous suspension>
#3      FlutterLocalNotificationsPlugin.zonedSchedule (package:flutter_local_notifications/src/flutter_local_notifications_plugin.dart:308:7)
<asynchronous suspension>
flutter: ----------------------------------------------------
```

Here is the simplified code

```dart
void test(Alarm alarm)async{
    final channel =  await _reminderDetails();
    _plugin.zonedSchedule(alarm.id,
        alarm.title,  alarm.body,
        tz.TZDateTime(tz.local, alarm.time.year, alarm.time.month, alarm.time.day, alarm.time.hour, alarm.time.minute),
        channel!,
        uiLocalNotificationDateInterpretation: UILocalNotificationDateInterpretation.absoluteTime,
        payload: json.encode(alarm.toMap()),
        matchDateTimeComponents: DateTimeComponents.dayOfWeekAndTime,
        androidAllowWhileIdle: true);
  }

 Future<NotificationDetails?> _reminderDetails()async{
    final fileName = Platform.isIOS ? "reminder_big.jpg" : "reminder.png";
    final path = await copyFromAssetsToAppDir(fileName);

    if(Platform.isAndroid) {
      final android = AndroidNotificationDetails(
        'test_channel', 'test', 'test',
        largeIcon: path == null ? null : FilePathAndroidBitmap(path),
      );
      return NotificationDetails(android: android);
    }
    if(Platform.isIOS){
      final ios = IOSNotificationDetails(
        presentSound: true,
        presentAlert: true,
        presentBadge: true,
        attachments: path == null ? null : [IOSNotificationAttachment(path)],
      );
      return NotificationDetails(iOS: ios);
    }
    return null;
  }

 Future<String?> copyFromAssetsToAppDir(String fileName)async{
    final dir = await getApplicationDocumentsDirectory();
    final path = "${dir.path}/$fileName";
    try{
      final file = File(path);
      if(await file.exists()){
        print("file already exist:$fileName");
        return path;
      }
      final imageBytes = await rootBundle.load('assets/$fileName');
      final bytes = imageBytes.buffer.asUint8List();
      await file.writeAsBytes(bytes);
    }catch(e){
      print("error file not exist:$e");
      return null;
    }
    return path;
  }
```
I hope this helps to reproduce the error

**Comment by MaikuB** [comment]
@offline-first if you look at the error message, it would indicate that an invalid URL is being provided. This isn't an issue with the plugin but be from the app providing an invalid URL to the native APIs via the plugin. As such, this is something you would need to investigate further. If you're already making use of Crashlytics then I would suggest you add more logging to look into it. Nothing further can be done from the plugin side as the issue doesn't lie with the plugin

**Comment by offline-first** [comment]
@MaikuB 
Strangely enough, the notifications with the image are displayed anyway. I can't do anything with the error from CrashLytics....

**Comment by offline-first** [comment]
@outailounni better use this method otherwise the image will be resaved every time:
```dart
Future<String> copyFromAssetsToAppDir(String fileName)async{
    final dir = await getApplicationDocumentsDirectory();
    final path = "${dir.path}/$fileName";
    final file = File(path);
    if(await file.exists()){
      return path;
    }
    final imageBytes = await rootBundle.load('assets/$fileName');
    final bytes = imageBytes.buffer.asUint8List();
    await file.writeAsBytes(bytes);
    return path;
  }
```

**Comment by outailounni** [comment]
already changed, thought about but still, thanks and good luck @offline-first

**Comment by baize-hub** [comment]
我依旧还是这个问题，并没有得到解决
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(Error 100, Invalid attachment file URL, UNErrorDomain, null)

文件路径是存在的，并且是可以读取的。
