### ISSUE TITLE
Flutter local notifications NullPointerException: Attempt to invoke virtual method 'setAction(java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by PhilipJFry2995** [MaikuB/flutter_local_notifications#1219]
I am trying to use plugin flutter_local_notifications in my project

For new clean default application created in Android Studio - everything works fine. But doing the same in my app leads to exception

```
    E/MethodChannel#dexterous.com/flutter/local_notifications(13407): Failed to handle method call
    E/MethodChannel#dexterous.com/flutter/local_notifications(13407): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Intent android.content.Intent.setAction(java.lang.String)' on a null object reference
    E/MethodChannel#dexterous.com/flutter/local_notifications(13407): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(FlutterLocalNotificationsPlugin.java:166)
    E/MethodChannel#dexterous.com/flutter/local_notifications(13407): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(FlutterLocalNotificationsPlugin.java:793)
    E/MethodChannel#dexterous.com/flutter/local_notifications(13407): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.show(FlutterLocalNotificationsPlugin.java:1056)
    E/MethodChannel#dexterous.com/flutter/local_notifications(13407): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:949)
    E/MethodChannel#dexterous.com/flutter/local_notifications(13407): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
    E/MethodChannel#dexterous.com/flutter/local_notifications(13407): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
    E/MethodChannel#dexterous.com/flutter/local_notifications(13407): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
    E/MethodChannel#dexterous.com/flutter/local_notifications(13407): 	at android.os.MessageQueue.nativePollOnce(Native Method)
    E/MethodChannel#dexterous.com/flutter/local_notifications(13407): 	at android.os.MessageQueue.next(MessageQueue.java:336)
    E/MethodChannel#dexterous.com/flutter/local_notifications(13407): 	at android.os.Looper.loop(Looper.java:174)
    E/MethodChannel#dexterous.com/flutter/local_notifications(13407): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
    E/MethodChannel#dexterous.com/flutter/local_notifications(13407): 	at java.lang.reflect.Method.invoke(Native Method)
    E/MethodChannel#dexterous.com/flutter/local_notifications(13407): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
    E/MethodChannel#dexterous.com/flutter/local_notifications(13407): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
    E/flutter (13407): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'android.content.Intent android.content.Intent.setAction(java.lang.String)' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Intent android.content.Intent.setAction(java.lang.String)' on a null object reference
    E/flutter (13407): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(FlutterLocalNotificationsPlugin.java:166)
    E/flutter (13407): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(FlutterLocalNotificationsPlugin.java:793)
    E/flutter (13407): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.show(FlutterLocalNotificationsPlugin.java:1056)
    E/flutter (13407): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:949)
    E/flutter (13407): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
    E/flutter (13407): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
    E/flutter (13407): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
    E/flutter (13407): 	at android.os.MessageQueue.nativePollOnce(Native Method)
    E/flutter (13407): 	at android.os.MessageQueue.next(MessageQueue.java:336)
    E/flutter (13407): 	at android.os.Looper.loop(Looper.java:174)
    E/flutter (13407): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
    E/flutter (13407): 	at java.lang.reflect.Method.invoke(Native Method)
    E/flutter (13407): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
    E/flutter (13407): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
    E/flutter (13407): )
    E/flutter (13407): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
    E/flutter (13407): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
    E/flutter (13407): <asynchronous suspension>
    E/flutter (13407): #2      FlutterLocalNotificationsPlugin.show (package:flutter_local_notifications/src/flutter_local_notifications_plugin.dart:178:7)
    E/flutter (13407): <asynchronous suspension>
```

AndroidManifest.xml

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
        package="com.somepackage">

    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />

    <application
        android:label="My label"
        android:icon="@mipmap/ic_launcher">
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
        <activity
            android:name="io.flutter.embedding.android.FlutterActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>

                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="@string/fb_login_protocol_scheme" />
            </intent-filter>
            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data
                    android:scheme="myscheme" />
            </intent-filter>
        </activity>
        <activity android:name="com.facebook.FacebookActivity"
            android:configChanges=
                "keyboard|keyboardHidden|screenLayout|screenSize|orientation"
            android:label="Walex"
            android:exported="true"
            />
        <meta-data android:name="com.google.android.geo.API_KEY"
            android:value="MYKEY"/>
        <meta-data android:name="com.facebook.sdk.ApplicationId"
            android:value="@string/facebook_app_id"/>
        <uses-library android:name="org.apache.http.legacy" android:required="false"/>
    </application>
</manifest>
```

Initialization code is in main function

```
void main() {
      WidgetsFlutterBinding.ensureInitialized();
      runApp(
        MyApp(),
      );
    }
    
    class MyApp extends StatelessWidget {
      MyApp();
    
      @override
      Widget build(BuildContext context) {
        return FutureBuilder(
            future: _initialization(),
            builder: (context, snapshot) {
    			...
            });
      }
    
      Future<Container> _initialization() async {
        FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
            FlutterLocalNotificationsPlugin();
        // initialise the plugin. app_icon needs to be a added as a drawable resource to the Android head project
        const AndroidInitializationSettings initializationSettingsAndroid =
            AndroidInitializationSettings('@mipmap/ic_launcher');
        final IOSInitializationSettings initializationSettingsIOS =
            IOSInitializationSettings();
        final MacOSInitializationSettings initializationSettingsMacOS =
            MacOSInitializationSettings();
        final InitializationSettings initializationSettings =
            InitializationSettings(
                android: initializationSettingsAndroid,
                iOS: initializationSettingsIOS,
                macOS: initializationSettingsMacOS);
        await flutterLocalNotificationsPlugin.initialize(initializationSettings);
    
        FirebaseApp firebaseApp = await Firebase.initializeApp();
        return Container(
            firebaseApp, flutterLocalNotificationsPlugin);
      }
    
      ThemeData theme() => ThemeData(
            primaryColor: Colors.white,
            accentColor: WalexColors.accentColor,
          );
    }
    
    class Container {
      FirebaseApp app;
      FlutterLocalNotificationsPlugin notificationsPlugin;
    
      Container(this.app, this.notificationsPlugin);
    }
```

And notification invocation happens in other widget

```
      void foo() async {
        FlutterLocalNotificationsPlugin plugin =
            Provider.of<FlutterLocalNotificationsPlugin>(context, listen: false);
        const AndroidNotificationDetails androidPlatformChannelSpecifics =
            AndroidNotificationDetails(
                'your channel id', 'your channel name', 'your channel description',
                importance: Importance.max,
                priority: Priority.high,
                ticker: 'ticker');
        const NotificationDetails platformChannelSpecifics =
            NotificationDetails(android: androidPlatformChannelSpecifics);
        await plugin.show(0, 'plain title', 'plain body', platformChannelSpecifics,
            payload: 'item x');
      }
```

I guess, that the problem is somewhere in Android configuration, but default project and my project looks pretty much the same.

**Comment by MaikuB** [comment]
This seems to be the same issue as https://github.com/MaikuB/flutter_local_notifications/issues/1187. However, I've not been able to get a minimal app that can reproduce the problem. This would aid in verify any potential fixes, if you're able to help with providing one  then that would be great. The worst case may be to ask others like yourself to help test by having your app point to a branch of this repo that contains a potential fix. There's a link to a PR to another repo that was said to contain a fix for another notification plugin. However, upon looking at it, I can see it causing issues with scenarios where Flutter is added to an existing app. The solution in assumes that a Flutter activity (which tends to correlate to a screen) would be the first/launch activity but that may not be the case when Flutter is added to an existing app

Also, is this issue something that consistently happens in your app as well?

**Comment by PhilipJFry2995** [comment]
Finally got the solution.
1. Not sure, if this is important, but still double checked. Removed all icons from android/app/src/res/mipmap. Opened the inner android project in Android Studio. And added new icon in res folder as Image Asset.
2. Edited AndroidManifest.xml, removed intent-filter for facebook from FlutterActivity element and put into FacebookActivity
The new manifest looks like

```
 <manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="mypackage">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />

    <application
        android:icon="@mipmap/ic_launcher"
        android:label="My Label">
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />

        <activity
            android:name="io.flutter.embedding.android.FlutterActivity"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density"
            android:hardwareAccelerated="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:windowSoftInputMode="adjustResize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data android:scheme="myscheme" />
            </intent-filter>
        </activity>
        <activity
            android:name="com.facebook.FacebookActivity"
            android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation"
            android:exported="true"
            android:label="MyApp">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data android:scheme="@string/fb_login_protocol_scheme" />
            </intent-filter>
        </activity>

        <meta-data
            android:name="com.google.android.geo.API_KEY"
            android:value="MYKEY" />
        <meta-data
            android:name="com.facebook.sdk.ApplicationId"
            android:value="@string/facebook_app_id" />

        <uses-library
            android:name="org.apache.http.legacy"
            android:required="false" />
    </application>
</manifest>
```
Now notifications are shown properly. I guess the issue may be closed now.

**Comment by SLYILL** [comment]
In my case, it was due to the intent-filter.
https://zenn.dev/sly_ill/articles/12d0b629c8a6a7
