### ISSUE TITLE
pendingNotificationRequests returning null instead of id on iOS

### ISSUE THREAD

**Issue by corcoran** [MaikuB/flutter_local_notifications#1287]
**Describe the bug**
Some iOS users are experiencing an error when `pendingNotificationRequests()` is called.

```
type 'Null' is not a subtype of type 'int'. Error thrown null.
  pendingNotificationRequests.<fn> + 62 (platform_flutter_local_notifications.dart:62)
  toList (dart:collection)
  pendingNotificationRequests + 63 (platform_flutter_local_notifications.dart:63)
```

**To Reproduce**
Unclear how to reproduce, only seems to occur since upgrading to null safety. iOS 12-14 users, iPhone and iPad.

**Expected behavior**
`pendingNotificationRequests()` should return a list, not throw an exception

**Sample code to reproduce the problem**
`FlutterLocalNotificationsPlugin().pendingNotificationRequests()`

**Comment by lucasribolli** [comment]
Does that issue occurs only in real devices or in both device and simulator?

**Comment by corcoran** [comment]
Have only seen this on real devices, haven't been able to reproduce it ourselves.

**Comment by MaikuB** [comment]
I'd need ways to reproduce a bug in order to investigate them. I suspect that you have other code that is scheduling notifications that is causing the problem and null safety has only surfaced up an existing problem.

If so, you'd need to address this within your own app as you need to vet libraries you use to see if they achieve what you're after or if you need to implement your own native code. More specifically, the old iOS notification API doesn't expose the notification id as a standard field to be read when looking at pending notifications. It is something this plugin needed to put in as custom info (see https://developer.apple.com/documentation/uikit/uilocalnotification/1616657-userinfo) and is specific to this plugin

**Comment by corcoran** [comment]
I definitely agree that you should be able to reproduce it and I'll try to find a way to do that.

That said, the inability of this library to return a list of pendingNotificationRequests() (regardless of where they were created), should be marked as a bug. Maybe the solution is to make the int id field nullable to account for such a case?

**Comment by MaikuB** [comment]
What would be the use case here and what is the use case you have in your own app at the moment?

**Comment by harryandroiddev** [comment]
same issue on ios

**Comment by harryandroiddev** [comment]
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: type 'Null' is not a subtype of type 'int'
#0      MethodChannelFlutterLocalNotificationsPlugin.pendingNotificationRequests.<anonymous closure>
package:flutter_local_notifications/src/platform_flutter_local_notifications.dart:81
#1      MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
#2      ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
#3      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#4      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#5      new List.of (dart:core-patch/array_patch.dart:51:28)
#6      ListIterable.toList (dart:_internal/iterable.dart:213:44)
#7      MethodChannelFlutterLocalNotificationsPlugin.pendingNotificationRequests
package:flutter_local_notifications/src/platform_flutter_local_notifications.dart:82
<asynchronous suspension>

**Comment by harryandroiddev** [comment]
it should not return null , rather than empty list .

**Comment by marcotta** [comment]
In my case I am testing upgrading an existing native iOS app with a new flutter app.
The native app scheduled some notifications and those come without an id.

When the flutter app is installed, calling `pendingNotificationRequests` retrieves those created from previous app and  
throws `type 'Null' is not a subtype of type 'int'`.

Perhaps id should be nullable as it is not so uncommon to rewrite an existing native app in flutter.
@MaikuB what do you think?

but yes I can workaround it, with a `try/catch` and `cancelAll()` in the `catch`

**Comment by qwadrox** [comment]
> In my case I am testing upgrading an existing native iOS app with a new flutter app. The native app scheduled some notifications and those come without an id.
> 
> When the flutter app is installed, calling `pendingNotificationRequests` retrieves those created from previous app and throws `type 'Null' is not a subtype of type 'int'`.
> 
> Perhaps id should be nullable as it is not so uncommon to rewrite an existing native app in flutter. @MaikuB what do you think?
> 
> but yes I can workaround it, with a `try/catch` and `cancelAll()` in the `catch`

This might be our issue. Switched from Xamarin lately.

**Comment by lukemmtt** [comment]
This remains an issue for me. Reproducible on launch when migrating from a native app to a flutter version of the app.
```dart
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'Null' is not a subtype of type 'int'
#0      MethodChannelFlutterLocalNotificationsPlugin.pendingNotificationRequests.<anonymous closure> (package:flutter_local_notifications/src/platform_flutter_local_notifications.dart:82:18)
#1      MappedListIterable.elementAt (dart:_internal/iterable.dart:425:31)
#2      ListIterator.moveNext (dart:_internal/iterable.dart:354:26)
#3      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#4      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#5      new List.of (dart:core-patch/array_patch.dart:39:18)
#6      ListIterable.toList (dart:_internal/iterable.dart:224:7)
#7      MethodChannelFlutterLocalNotificationsPlugin.pendingNotificationRequests (package:flutter_local_notifications/src/platform_flutter_local_notifications
```

**Comment by lukemmtt** [comment]
This seems to remain an issue for me. Reproducible on launch, in iOS simulator, when migrating from a native app to a flutter version of the app.   flutter_local_notifications version 17.1.2
```dart
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'Null' is not a subtype of type 'int'
#0      MethodChannelFlutterLocalNotificationsPlugin.pendingNotificationRequests.<anonymous closure> (package:flutter_local_notifications/src/platform_flutter_local_notifications.dart:82:18)
#1      MappedListIterable.elementAt (dart:_internal/iterable.dart:425:31)
#2      ListIterator.moveNext (dart:_internal/iterable.dart:354:26)
#3      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#4      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#5      new List.of (dart:core-patch/array_patch.dart:39:18)
#6      ListIterable.toList (dart:_internal/iterable.dart:224:7)
#7      MethodChannelFlutterLocalNotificationsPlugin.pendingNotificationRequests (package:flutter_local_notifications/src/platform_flutter_local_notifications
```

**Comment by orestesgaolin** [comment]
Same issue was reproducible on flutter_local_notifications 18.x. Updated now to 20.0.0 and trying to validate if this still occurs.

```
TypeError: type 'Null' is not a subtype of type 'int'
#0      MethodChannelFlutterLocalNotificationsPlugin.pendingNotificationRequests.<fn> (package:flutter_local_notifications/src/platform_flutter_local_notifications.dart:81)
#1      MappedIterable.elementAt (dart:_internal/iterable.dart:402)
#2      ListIterator.moveNext (dart:_internal/iterable.dart:371)
#3      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:194)
#4      new _GrowableList.of (dart:core-patch/growable_array.dart:154)
#5      new List.of (dart:core-patch/array_patch.dart:39)
#6      SetBase.toList (dart:collection/set.dart:119)
#7      MethodChannelFlutterLocalNotificationsPlugin.pendingNotificationRequests (package:flutter_local_notifications/src/platform_flutter_local_notifications.dart:82)
  File "<asynchronous suspension>"
```
