### ISSUE TITLE
FlutterLocalNotificationsPlugin.java line 48 crashlytics 

### ISSUE THREAD

**Issue by MlecznyU** [MaikuB/flutter_local_notifications#1290]
Hello,
In the application, I have a basic implementation of flutter notifications. The only method I use is zonedSchedule. 

The whole thing works for a long time, very well on android and ios devices. However, crash information has started to appear in crashlytics. The problem only affects Samsung s9+ device on the android 8 operating system. 
I use   flutter_local_notifications: ^5.0.0-nullsafety.1

Code for notifications:

`  Future<void> initialize(SelectNotificationCallback onSelectNotification) async {
    _prefs = await SharedPreferences.getInstance();

    // NOTE: make sure initializeTimeZones() is imported from 'package:timezone/data/latest_all.dart'
    tz.initializeTimeZones();

    final String currentTimeZone = await FlutterNativeTimezone.getLocalTimezone();
    tz.setLocalLocation(tz.getLocation(currentTimeZone));

    FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin = FlutterLocalNotificationsPlugin();

    const AndroidInitializationSettings initializationSettingsAndroid = AndroidInitializationSettings('app_icon');

    final IOSInitializationSettings initializationSettingsIOS = IOSInitializationSettings(
      requestAlertPermission: false,
      requestBadgePermission: false,
      requestSoundPermission: false,
    );
    final InitializationSettings initializationSettings = InitializationSettings(
      android: initializationSettingsAndroid,
      iOS: initializationSettingsIOS,
      macOS: null,
    );
    await flutterLocalNotificationsPlugin.initialize(
      initializationSettings,
      onSelectNotification: onSelectNotification,
    );
  }`

`  Future<void> scheduleNotifications(S localizations) async {
    FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin = FlutterLocalNotificationsPlugin();

    if (Platform.isIOS) {
      final bool result = (await (flutterLocalNotificationsPlugin
          .resolvePlatformSpecificImplementation<IOSFlutterLocalNotificationsPlugin>()
          ?.requestPermissions(
            alert: true,
            badge: true,
            sound: true,
          )))!;

      if (!result) return;
    }

    await flutterLocalNotificationsPlugin.cancelAll();

    tz.TZDateTime nextTimeInstance = getTime();
    final weekdays = getWeekdays();
    for (int i = 0; i < DateTime.daysPerWeek; i++) {
      final scheduledDate = nextTimeInstance.add(Duration(days: i));
      if (weekdays.contains(scheduledDate.weekday)) {
        await flutterLocalNotificationsPlugin.zonedSchedule(
            scheduledDate.weekday,
            null,
            localizations.reminderText,
            scheduledDate,
            NotificationDetails(
              android: AndroidNotificationDetails('reminders', localizations.reminderChannelName, ''),
            ),
            androidAllowWhileIdle: true,
            uiLocalNotificationDateInterpretation: UILocalNotificationDateInterpretation.absoluteTime,
            matchDateTimeComponents: DateTimeComponents.dayOfWeekAndTime);
      }
    }
  }
`

I attach the information from firebase below.
`Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3397)
       at android.app.ActivityThread.-wrap18(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1780)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)`
`Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.setSmallIcon(FlutterLocalNotificationsPlugin.java:48)
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(FlutterLocalNotificationsPlugin.java:138)
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(FlutterLocalNotificationsPlugin.java)
       at com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver.onReceive(ScheduledNotificationReceiver.java:76)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3390)
       at android.app.ActivityThread.-wrap18(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1780)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)`

Is anything known about this problem?

**Comment by MaikuB** [comment]
The only known issue I've seen on this is when the release build configuration hasn't been done

**Comment by chiennv97** [comment]
change code from 
`AndroidNotificationDetails(
             ...
               icon: android?.smallIcon,
               ),`
to 
`AndroidNotificationDetails(
                ...
                icon: '@mipmap/ic_launcher',
              ),`

**Comment by armandojimenez** [comment]
Same error appears randomly on crashlytics from some devices, only on a few models, works on all others so is not configuration.

**Comment by MaikuB** [comment]
@armandojimenez What configuration have you done though? There's some Android-specific release build configuration that is supposed to be done and it might be that it won't affect all devices but should be done to avoid scenarios where it could in release mode. Have you also been able to reproduce this or figure out the steps on how the error can occur?

**Comment by MlecznyU** [comment]
The problem turned out not to be repeated. At the time of reporting, we were flooded with logs with this error from users. The error has not occurred again for some time. I am closing the issue.

**Comment by feelsoftware** [comment]
I have the same issue in my app.
_This issue has 10 crash events affecting 3 users_

<img width="1236" alt="Screenshot 2022-09-15 at 10 12 36" src="https://user-images.githubusercontent.com/84723446/190338864-377fad46-b531-44a5-b1a5-3f6d1ca6b45b.png">
