### ISSUE TITLE
No Valid small icon

### ISSUE THREAD

**Issue by bigbang489** [MaikuB/flutter_local_notifications#1303]
I got this error from Firebase Crashlytics (it happened in user devices, not in my testing devices). It crashed the app
I used vector image for the notification icon (I used Android Studio to convert my SVG to file ic_notification.xml and copy it to drawable folder)
How do I set the small icon for notification?

plugin version: 8.1.1+1
Device info: 
Model:Galaxy Note8
Orientation: Landscape
RAM free: 1.7 GB
Disk free: 5.78 GB

Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(channel=Finance Assist pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x10 color=0xff4caf50 vis=PUBLIC semFlags=0x0 semPriority=0 semMissedCount=0)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3606)
       at android.app.ActivityThread.access$1300(ActivityThread.java:237)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1796)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7045)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

my code:

```
static void initialize() {
    const androidInitialize = AndroidInitializationSettings('ic_notification');
    const iOSInitialize = IOSInitializationSettings();
    const initializationsSettings =
        InitializationSettings(android: androidInitialize, iOS: iOSInitialize);
    notificationService = FlutterLocalNotificationsPlugin();
    notificationService.initialize(initializationsSettings,
        onSelectNotification: _notificationSelected);
    const androidDetails =
        AndroidNotificationDetails(text_app_name, text_app_name, text_app_name,
            icon: 'ic_notification',
            visibility: NotificationVisibility.public,
            styleInformation: BigTextStyleInformation(''),
            importance: Importance.max);
    const iSODetails = IOSNotificationDetails();
    generalNotificationDetails =
        NotificationDetails(android: androidDetails, iOS: iSODetails);
  }
```

**Comment by MaikuB** [comment]
When you tested on your own devices, did you make sure to run the app using a release build and ensured that you had done the [release build configuration](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#release-build-configuration)? I'm guessing when you did your own testing that it was a via debug build, which tends to be the reason why issues like this get found

**Comment by bigbang489** [comment]
I tested release build (Internal Testing, and Preflight Test for IOS), but it not occurs
Not all of my users get this error, but only 2% of them
I haven't applied the release build configuration because I tested in release build and it worked
it is required to apple release build configuration even in case It worked on release build?

**Comment by MaikuB** [comment]
It is needed and not something you should be skipping as it looks like it works fine without it. Also this is specific to Android so testing on iOS isn't going to help. Applying the release build configuration later isn't a retroactive fix either

**Comment by bigbang489** [comment]
You mean the fix will not be appliable for our existing users even when they upgrade the latest build?

**Comment by MaikuB** [comment]
Correct

**Comment by bigbang489** [comment]
What if they remove and reinstall the app?

**Comment by MaikuB** [comment]
I believe it should be fine after that. If you still have a problem after doing so then I'll need repo containing a minimal app with steps to reproduce the issue

**Comment by bigbang489** [comment]
One more thing, all I need to do is, just copy the pro-guard-rules.pro in your example to my project?
I'm sorry for asking too much, I didnt have a android development background 😂

**Comment by MaikuB** [comment]
You also need to configure it so that resources like your notification icons aren't removed. That section of the documentation I linked two has two paragraphs. You should also read the Android docs that are referenced as it's important you understand what is going on and what's involved as opposed to just copying and pasting as the latter won't help you in the long run e.g. if you don't use Flutter in the future, the Android knowledge is more "transferable"

**Comment by kouroku-room** [comment]
@MaikuB 
Sorry for asking a question to an already closed Issue.

I have the same issue. Please allow me to confirm this statement.

> Applying the release build configuration later isn't a retroactive fix either

Is the file that this "release build configuration" refers to the "proguard-rules.pro"? Or are you referring to 'keep.xml'?
It reads as the file settings at installation take precedence and user updating the app after that has no fix, but I could not find any text on the internet that states that.
Is there a web page (Android Developers site, etc.) that describes this?

If this is the case, is there a workaround other than having the user do a clean install?
For example, by appending Suffix to the filename of the resource to re-register it as a different resource.
