### ISSUE TITLE
Android notification details is required?

### ISSUE THREAD

**Issue by LeonardoRosaa** [MaikuB/flutter_local_notifications#1390]
First of all, thanks for the package 😄 

**Describe the bug**

When not put notification details for `Android` Platform I received this error message:

```shell
E/MethodChannel#dexterous.com/flutter/local_notifications(18666): Failed to handle method call
E/MethodChannel#dexterous.com/flutter/local_notifications(18666): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
E/MethodChannel#dexterous.com/flutter/local_notifications(18666): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.setupNotificationChannel(FlutterLocalNotificationsPlugin.java:981)
E/MethodChannel#dexterous.com/flutter/local_notifications(18666): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(FlutterLocalNotificationsPlugin.java:198)
E/MethodChannel#dexterous.com/flutter/local_notifications(18666): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(FlutterLocalNotificationsPlugin.java:1042)
E/MethodChannel#dexterous.com/flutter/local_notifications(18666): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.show(FlutterLocalNotificationsPlugin.java:1376)
E/MethodChannel#dexterous.com/flutter/local_notifications(18666): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:1262)
E/MethodChannel#dexterous.com/flutter/local_notifications(18666): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#dexterous.com/flutter/local_notifications(18666): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/MethodChannel#dexterous.com/flutter/local_notifications(18666): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
E/MethodChannel#dexterous.com/flutter/local_notifications(18666): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#dexterous.com/flutter/local_notifications(18666): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#dexterous.com/flutter/local_notifications(18666): 	at android.os.Looper.loop(Looper.java:183)
E/MethodChannel#dexterous.com/flutter/local_notifications(18666): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/MethodChannel#dexterous.com/flutter/local_notifications(18666): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#dexterous.com/flutter/local_notifications(18666): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/MethodChannel#dexterous.com/flutter/local_notifications(18666): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Reproduce bug**
- Open [example](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications/example) app;
- Remove `notificationDetails` parameter of whatever show method.

My question is:  for `Android` Platform `notificationDetails` parameter is **required**?

**Comment by MaikuB** [comment]
Yes it is. It's not marked as such using the `required` keyword in Dart because there are developers that only target specific platforms so they shouldn't be forced to specify parameters for platforms they don't target
