### ISSUE TITLE
Error when using compute/isolate

### ISSUE THREAD

**Issue by Kharda** [MaikuB/flutter_local_notifications#1413]
Hi all, for scheduling many notifications at a time, are we able to schedule it using isolate by making the function static and calling it via compute? 

for example, I tried to edit the  `_cancelAllNotifications`  function from the plugin example to:

```
static Future<void> _cancelAllNotifications(String message) async {
    await flutterLocalNotificationsPlugin.cancelAll();
}
```

and add compute to the caller
```
onPressed: () async {
    await compute(_cancelAllNotifications, 'message');
}
```

But I got this error when I tap the button

```
E/flutter (23121): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Exception: Null check operator used on a null value
E/flutter (23121): #0      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:121:86)
E/flutter (23121): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:146:36)
E/flutter (23121): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (23121): #3      MethodChannelFlutterLocalNotificationsPlugin.cancelAll (package:flutter_local_notifications/src/platform_flutter_local_notifications.dart:44:40)
E/flutter (23121): #4      FlutterLocalNotificationsPlugin.cancelAll (package:flutter_local_notifications/src/flutter_local_notifications_plugin.dart:247:54)
E/flutter (23121): #5      _HomePageState._cancelAllNotifications (package:flutter_local_notifications_example/main.dart:1372:43)
E/flutter (23121): #6      _IsolateConfiguration.apply (package:flutter/src/foundation/_isolates_io.dart:84:34)
E/flutter (23121): #7      _spawn.<anonymous closure> (package:flutter/src/foundation/_isolates_io.dart:91:65)
E/flutter (23121): #8      _spawn.<anonymous closure> (package:flutter/src/foundation/_isolates_io.dart:90:5)
E/flutter (23121): #9      Timeline.timeSync (dart:developer/timeline.dart:163:22)
E/flutter (23121): #10     _spawn (package:flutter/src/foundation/_isolates_io.dart:88:35)
E/flutter (23121): #11     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:286:17)
E/flutter (23121): #12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

Kindly advise
Thank you

**Comment by MaikuB** [comment]
As far as I know, standard isolates don't work with plugins. I've heard others in the community uses plugins like https://pub.dev/packages/flutter_isolate for use cases like this and I had seen one post on here where it was successfully used with this plugin too. You'll need to look into trying options like this as it's outside the control of this plugin and due to with how Flutter itself
