### ISSUE TITLE
FlutterLocalNotificationsPlugin.java – line 223

### ISSUE THREAD

**Issue by thize** [MaikuB/flutter_local_notifications#1485]
**Describe the bug**
I have been receiving some crash reports through Crashlytics over the Weekend. Multiple users with Android devices encountered failures caused by the FlutterLocalNotificationsPlugin.java. This the Stack trace Crashlytics provided:

**Bug**
```
Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4495)
       at android.app.ActivityThread.access$1500(ActivityThread.java:301)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2177)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8633)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Cause by:**
```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(FlutterLocalNotificationsPlugin.java:223)
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(FlutterLocalNotificationsPlugin.java:1007)
       at com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver.onReceive(ScheduledNotificationReceiver.java:41)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4486)
       at android.app.ActivityThread.access$1500(ActivityThread.java:301)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2177)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8633)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

Package Version : ^9.3.1

**Reproduce the problem**
I Called Zoned Schedule with AndroidDetails, using tags:
enableLights: true,
ledColor: true,
playSound: true,
setAsGroupSummary: true,
visibility: NotificationVisibility.public,
showProgress: true,
progress: progress,
enableVibration: true,
maxProgress: 100,
priority: Priority.max,
importance: Importance.max,
fullScreenIntent: true,
tag: tag,

**Comment by MaikuB** [comment]
Can you provide a link to a repository with a minimal app that can reproduce the issue?

**Comment by MaikuB** [comment]
Actually I've figured out the issue now. Fix incoming

**Comment by MaikuB** [comment]
Released 9.3.2 that should fix this issue. Thanks for reporting

**Comment by alexursul** [comment]
Hi! The same issue in version ^10.0.0-dev.7. Could you please update it too?

**Comment by MaikuB** [comment]
done

**Comment by 2022zhangyuhui** [comment]
你好，flutter_local_notifications在oppoandroid 11上没有效果，通道自定义失败原因，能帮忙看看什么？我们公司正在开发推送自定义铃声，急需解决。
