### ISSUE TITLE
Fatal exception: NoClassDefFoundError - com.jakewharton.threetenabp.AndroidThreeTen.init (Android 4.4.X)

### ISSUE THREAD

**Issue by EsteveAguilera** [MaikuB/flutter_local_notifications#1502]
We're getting a `NoClassDefFoundError` fatal exception on an app on production.

According to crashlytics, it seems it affects **only Android 4.4.X** devices:

**69%** - Android 4.4.2
**31%** - Android 4.4.4

```
Fatal Exception: java.lang.NoClassDefFoundError: e.g.a.b
       at com.jakewharton.threetenabp.AndroidThreeTen.init(AndroidThreeTen.java)
       at com.jakewharton.threetenabp.AndroidThreeTen.init(AndroidThreeTen.java)
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.initAndroidThreeTen(FlutterLocalNotificationsPlugin.java)
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.rescheduleNotifications(FlutterLocalNotificationsPlugin.java)
       at com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver.onReceive(ScheduledNotificationBootReceiver.java)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2624)
       at android.app.ActivityThread.access$1800(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1430)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5345)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

We're using `Flutter 2.10.2` and ` flutter_local_notifications: ^9.3.2`

**Comment by MaikuB** [comment]
That is to do with a transitive dependency used by the plugin, which is mentioned in the stack trace. I'd suggest you take a look at the repo for it to see there's been any mention of this issue in case you've missed something in your apps configuration. From memory, one cause of such error is when an app should've enabled multidex and that tends to be up to each app to determine if that is needed.

**Comment by EsteveAguilera** [comment]
We already have multidex enabled, so this is not be the solution for us.

I've opened an issue on Jake's repository.

Thanks!

**Comment by MaikuB** [comment]
Are you sure about it’s been enabled properly. Flutter may require extra setup for multidex. I believe there were some changes to make it easier for applications built using recent versions of the SDK to get multidex support but only for apps created when they updated the template for creating apps in recent versions. That repo you want to open issue on will likely not get much support either as it’s encouraged to desugaring, which this plugin  should do at some point but had to hold off as it would’ve need the Android Gradle plugin version to be bumped but there were stability issues with Flutter before

**Comment by EsteveAguilera** [comment]
You were right @MaikuB , we missed some multidex configuration [(more info here)](https://github.com/JakeWharton/ThreeTenABP/issues/136#issuecomment-1054184480). 

Thanks for your time!
