### ISSUE TITLE
NPE: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference

### ISSUE THREAD

**Issue by mk-dev-1** [MaikuB/flutter_local_notifications#1517]
Hi guys,

since one of the latest v10-dev releases I have started getting the following occasional error:

```
Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver: java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4495)
       at android.app.ActivityThread.access$1600(ActivityThread.java:301)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2177)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8633)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

Caused by java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
       at android.text.SpannableString.<init>(SpannableString.java:34)
       at android.text.SpannableString.<init>(SpannableString.java:43)
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(FlutterLocalNotificationsPlugin.java:256)
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(FlutterLocalNotificationsPlugin.java:1081)
       at com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver.onReceive(ScheduledNotificationReceiver.java:41)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4486)
       at android.app.ActivityThread.access$1600(ActivityThread.java:301)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2177)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8633)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```
I am unable to reproduce the error, so I was wondering if it might be related to an issue with my implementation, particularly the initialization of the plugin. I realized that I did not await the initialization in all cases, which is fixed now. However, the error remains. It seems to be related to this part of the plugins java code:

```java
        final Spannable actionTitleSpannable = new SpannableString(action.title);
        if (action.titleColor != null) {
          actionTitleSpannable.setSpan(
              new ForegroundColorSpan(action.titleColor), 0, actionTitleSpannable.length(), 0);
        }
```

Now that I am writing this, I believe this part of the code is related to the notification actions and apparently something is wrong with the title of the notification action. Here is an example of my notification details implementation:

```dart
AndroidNotificationDetails(
          'channel_id',
          'channel_name',
          color: AppColors.primary,
          importance: Importance.max,
          priority: Priority.max,
          actions: <AndroidNotificationAction>[
            AndroidNotificationAction(
              NotificationAction.take.toString(),
              localizations.notificationActionTake,
              cancelNotification: true,
            ),
            AndroidNotificationAction(
              NotificationAction.snooze.toString(),
              localizations.notificationActionSnooze(snoozeDuration),
              cancelNotification: true,
            ),
          ],
        );
```

If the issue was that my localization was empty/null, I believe I would be getting a different error though, so I am unsure where to look.

Any ideas?

Thanks for your support!

**Comment by MaikuB** [comment]
Afraid not but this does seem to point to an issue with the title as you say. What version of the plugin are you using? Does your app schedule notifications with actions or does it try to trigger them immediately? If it's the former then perhaps this is specific to release builds and would need to know if you've done the release build configuration and if so, exactly what was specified. It'd be best if a repo hosting minimal app that can reproduce the issue could be provided

**Comment by mk-dev-1** [comment]
Apologies, I meant to add my proguard rules, too, but forgot to do so:

```
# https://pub.dev/packages/flutter_local_notifications
-keepattributes Signature
-keepattributes *Annotation*
-dontwarn sun.misc.**
-keep class * extends com.google.gson.TypeAdapter
-keep class * implements com.google.gson.TypeAdapterFactory
-keep class * implements com.google.gson.JsonSerializer
-keep class * implements com.google.gson.JsonDeserializer
-keepclassmembers,allowobfuscation class * {
  @com.google.gson.annotations.SerializedName <fields>;
}
```

This is copied from the example app.

All notifications are scheduled like this

```dart
return notificationManager!
        .zonedSchedule(
          id,
          title,
          subtitle,
          tz.TZDateTime.from(date, tz.local),
          NotificationDetails(
            android: _getAndroidNotificationChannel(type),
            iOS: DarwinNotificationDetails(
              categoryIdentifier: await darwinNotificationCategoryId(type),
            ),
          ),
          uiLocalNotificationDateInterpretation:
              UILocalNotificationDateInterpretation.absoluteTime,
          androidAllowWhileIdle: true,
          payload: payload,
          matchDateTimeComponents:
              recurring ? DateTimeComponents.dayOfWeekAndTime : null,
        )
        .then((result) => id!);
```

Unfortunately, I don't think I can provide a minimal reproducable example as I am struggling to recreate the error myself.

I will keep monitoring this issue in any case. Currently I am only seeing very few errors....

**Comment by MaikuB** [comment]
It's quite possible you cannot reproduce is as the original work on notification actions missed an annotation that I added later on (see https://github.com/MaikuB/flutter_local_notifications/commit/971663de46b78f678c65b813fdb3293f0e9a7441, which actually went into the 10.0.0-dev.5 release). What might be happening is you have notifications failing to. be triggered from when they were scheduled using an older prerelease that was missing this annotation or from using the fork that formed the basis of the [PR](https://github.com/MaikuB/flutter_local_notifications/pull/880) that got merged in

**Comment by MaikuB** [comment]
Note the plugin in doesn't wipe out instances of bad data for scheduled notifications so the devices that were affected by this would continue to report this. Happy to take a PR if there's a way to do so that doesn't affect the ability to report crashes for scheduled and instant notifications

**Comment by mk-dev-1** [comment]
I believe you have been right as I do no longer see any new errors. Thanks for your support!
