### ISSUE TITLE
Crash if enableLights

### ISSUE THREAD

**Issue by offline-first** [MaikuB/flutter_local_notifications#1529]
**Crash log:**
```log
Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
E/AndroidRuntime(18673): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4381)
E/AndroidRuntime(18673): 	at android.app.ActivityThread.access$1800(ActivityThread.java:287)
E/AndroidRuntime(18673): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2181)
E/AndroidRuntime(18673): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(18673): 	at android.os.Looper.loop(Looper.java:255)
E/AndroidRuntime(18673): 	at android.app.ActivityThread.main(ActivityThread.java:8212)
E/AndroidRuntime(18673): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(18673): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
E/AndroidRuntime(18673): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
E/AndroidRuntime(18673): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
E/AndroidRuntime(18673): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.setLights(FlutterLocalNotificationsPlugin.java:700)
E/AndroidRuntime(18673): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(FlutterLocalNotificationsPlugin.java:255)
E/AndroidRuntime(18673): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(FlutterLocalNotificationsPlugin.java:1009)
E/AndroidRuntime(18673): 	at com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver.onReceive(ScheduledNotificationReceiver.java:41)
E/AndroidRuntime(18673): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4365)
```
**Code Part**
```Dart
AndroidNotificationDetails(
   //...
   enableLights: true,
   ledOnMs: 1000,
   ledOffMs: 500,
   //...
```

**Device**
- Realme 7
- Android 11

if I remove ledOnMS and ledOffMs everything is working.

**Comment by MaikuB** [comment]
Could you provide a link to a repository with a minimal app that can reproduce the issue?

**Comment by MaikuB** [comment]
Another thing to check to see if you can reproduce it on the example app. I've not come across this issue and no one else has reported this. Perhaps you have missed doing the release build configuration? That tends to be the cause of these issues

**Comment by MaikuB** [comment]
Closing due to lack of response and evidence to show that the issue is from the plugin itself with steps on how to reproduce

**Comment by kartik1225** [comment]
Just for the SEO

It might be causing because you forgot to invoke `getNotificationAppLaunchDetails()` in the main file

add this in `main.dart` (also found in the example)
```
final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
    FlutterLocalNotificationsPlugin();

void main async () {
   ...
    await flutterLocalNotificationsPlugin.getNotificationAppLaunchDetails();
   ...
}

```
