### ISSUE TITLE
Bad notification posted from package

### ISSUE THREAD

**Issue by rinkuanuragkumar** [MaikuB/flutter_local_notifications#1598]
I am facing this issue on some devices. 
Kindly resolve the issue as soon as possible.

Fatal Exception: android.app.RemoteServiceException: Bad notification posted from package com.test.app: Couldn't create icon: StatusBarIcon(pkg=com.test.app user=0 id=0x7f060074 level=0 visible=true num=0 )
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1580)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:189)
       at android.app.ActivityThread.main(ActivityThread.java:5529)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)

**Comment by bartekpacia** [comment]
Have you tried answers from [this SO thread](https://stackoverflow.com/questions/25317659/how-to-fix-android-app-remoteserviceexception-bad-notification-posted-from-pac)?

**Comment by MaikuB** [comment]
Please include a link to a minimal app that can reproduce the problem and in future use the bug report template. Currently no evidence has been provided to indicate there's an issue with the plugin and last time this issue occurred was years ago and has been resolved (https://github.com/MaikuB/flutter_local_notifications/issues/178)

Also a reminder that this is open-source software that is provided freely and provided as-is per the license

**Comment by MaikuB** [comment]
Closing due to lack of response with the requested info to reproduce the issue. Feel free to re-open the issue if you're able to do so
