### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by shichonghuotian** [MaikuB/flutter_local_notifications#1688]
The app crash when I use FlutterContacts.requestPermission()
```
E/AndroidRuntime( 8702): java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=1, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.linq.linq_pros/com.linq.redstar_construction.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.dexterous.flutterlocalnotifications.PermissionRequestListener.complete(boolean)' on a null object reference
E/AndroidRuntime( 8702): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5015)
E/AndroidRuntime( 8702): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5056)
E/AndroidRuntime( 8702): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime( 8702): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime( 8702): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime( 8702): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
E/AndroidRuntime( 8702): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 8702): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime( 8702): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime( 8702): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8702): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime( 8702): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime( 8702): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.dexterous.flutterlocalnotifications.PermissionRequestListener.complete(boolean)' on a null object reference
E/AndroidRuntime( 8702): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onRequestPermissionsResult(FlutterLocalNotificationsPlugin.java:1580)
E/AndroidRuntime( 8702): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:777)
E/AndroidRuntime( 8702): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:409)
E/AndroidRuntime( 8702): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult(FlutterActivityAndFragmentDelegate.java:752)
E/AndroidRuntime( 8702): 	at io.flutter.embedding.android.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:748)
E/AndroidRuntime( 8702): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8466)
E/AndroidRuntime( 8702): 	at android.app.Activity.dispatchActivityResult(Activity.java:8314)
E/AndroidRuntime( 8702): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5008)
E/AndroidRuntime( 8702): 	... 11 more
I/Process ( 8702): Sending signal. PID: 8702 SIG: 9

```

**Comment by MaikuB** [comment]
There is a PR that can fix this but from when I tried to reproduce the issue myself, this only happened if the asynchronous permissions request wasn't awaited. In other words, it is missing an `await`. Are you also missing this in your app as you actually should be putting that in, otherwise this leads to more conflicts between different plugins that can handle permission requests

**Comment by MaikuB** [comment]
The fix from this plugin's end has been released so closing this and haven't heard further response to the question either.
