### ISSUE TITLE
Fatal Exception: java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by mdmota** [MaikuB/flutter_local_notifications#1806]
flutter_local_notifications: ^12.0.3+1

Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/LocalDateTime;
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.zonedScheduleNotification(FlutterLocalNotificationsPlugin.java)
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.zonedSchedule(FlutterLocalNotificationsPlugin.java)
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java)
       at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java)
       at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0(DartMessenger.java)
       at io.flutter.embedding.engine.dart.DartMessenger.$r8$lambda$TsixYUB5E6FpKhMtCSQVHKE89gQ(DartMessenger.java)
       at io.flutter.embedding.engine.dart.DartMessenger$$InternalSyntheticLambda$0$ceffc6bae7d364cb48afaf1aaebd60bf9050360d0efb9035ebc54f0851df0a05$0.run(DartMessenger.java)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:159)
       at android.app.ActivityThread.main(ActivityThread.java:6139)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by noahabe** [comment]
Have you used FlutterLocalNotificationsPlugin's [zonedSchedule](https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/FlutterLocalNotificationsPlugin/zonedSchedule.html) method? If yes can you show the code? If not, show the specific code that you used to show notifications?

**Comment by mdmota** [comment]
```
    await flutterLocalNotificationsPlugin.zonedSchedule(
        data.id!,
        Constants.APP_NAME,
        'msg notification xxxx',
        tz.TZDateTime.parse(tz.local, dateFormated),
        const NotificationDetails(
            android: AndroidNotificationDetails('xx_dd_id',
                'AAAA', channelDescription: 'BBBB', styleInformation: BigTextStyleInformation('')),
            iOS: DarwinNotificationDetails()),
        androidAllowWhileIdle: true,
        uiLocalNotificationDateInterpretation:
        UILocalNotificationDateInterpretation.absoluteTime);
  }
```

**Comment by tbt15** [comment]
I have the same issue. The app is crashing for Android 7 or lower. Please help!

**Comment by mdmota** [comment]
I tried to keep java.time.* in proguard. I don't know if it will solve.
If I solve it, I'll comment here.

**Comment by MaikuB** [comment]
You're having this issue because you haven't completed the [Android setup](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#gradle-setup). This is exact same issue another member of the community encountered in https://github.com/MaikuB/flutter_local_notifications/issues/1792

**Comment by eeoom** [comment]
Is there a need to use V 1.1.5 or can we use coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.0.0' also ?
