### ISSUE TITLE
Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.

### ISSUE THREAD

**Issue by ByeBai** [MaikuB/flutter_local_notifications#1820]
**Describe the bug**

Running `flutter_local_notifications: 1.4.4+5` on a flutter 2.0 app.

Notifications work fine on iOS, but when running on Android, I get the following error when trying to schedule a notification.

```
E/MethodChannel#dexterous.com/flutter/local_notifications( 8402): Failed to handle method call
E/MethodChannel#dexterous.com/flutter/local_notifications( 8402): java.lang.IllegalArgumentException: games.sicko.wrestlingceo: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
E/MethodChannel#dexterous.com/flutter/local_notifications( 8402): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
E/MethodChannel#dexterous.com/flutter/local_notifications( 8402):       at android.app.PendingIntent.checkFlags(PendingIntent.java:401)
E/MethodChannel#dexterous.com/flutter/local_notifications( 8402):       at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:671)
E/MethodChannel#dexterous.com/flutter/local_notifications( 8402):       at android.app.PendingIntent.getBroadcast(PendingIntent.java:658)
E/MethodChannel#dexterous.com/flutter/local_notifications( 8402):       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.scheduleNotification(FlutterLocalNotificationsPlugin.java:264)
E/MethodChannel#dexterous.com/flutter/local_notifications( 8402):       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.schedule(FlutterLocalNotificationsPlugin.java:818)
E/MethodChannel#dexterous.com/flutter/local_notifications( 8402):       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:754)
E/MethodChannel#dexterous.com/flutter/local_notifications( 8402):       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#dexterous.com/flutter/local_notifications( 8402):       at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#dexterous.com/flutter/local_notifications( 8402):       at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#dexterous.com/flutter/local_notifications( 8402):       at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#dexterous.com/flutter/local_notifications( 8402):       at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#dexterous.com/flutter/local_notifications( 8402):       at android.os.Looper.loopOnce(Looper.java:161)
E/MethodChannel#dexterous.com/flutter/local_notifications( 8402):       at android.os.Looper.loop(Looper.java:288)
E/MethodChannel#dexterous.com/flutter/local_notifications( 8402):       at android.app.ActivityThread.main(ActivityThread.java:7898)
E/MethodChannel#dexterous.com/flutter/local_notifications( 8402):       at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#dexterous.com/flutter/local_notifications( 8402):       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/MethodChannel#dexterous.com/flutter/local_notifications( 8402):       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/MethodChannel#dexterous.com/flutter/local_notifications( 8402): Failed to handle method call
E/MethodChannel#dexterous.com/flutter/local_notifications( 8402): java.lang.IllegalArgumentException: games.sicko.wrestlingceo: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
```

**To Reproduce**
1. On Android, schedule a notification via

```
Future<void> showScheduledLocalNotification({
    int id,
    String title,
    String body,
    String payload,
    int seconds,
  }) async {
    final platformChannelSpecifics = await _notificationDetails();
    await _localNotifications.schedule(
      id,
      title,
      body,
      tz.TZDateTime.now(tz.local).add(Duration(seconds: seconds)),
      platformChannelSpecifics,
      payload: payload,
      androidAllowWhileIdle: true,
    );
  }
```

I noticed there was a fix for this issue in https://github.com/MaikuB/flutter_local_notifications/issues/1476 from update 10.0.0-dev.6
Is there a manual way I can apply that fix for the 1.4.4+5 version? I am not looking to update past flutter 2.0

**Expected behavior**
Notification works as expected

**Additional Notes**

I've included the below to the AndroidManifest

```
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.VIBRATE" />

    .
    .
    .
    .


     ...
        <receiver android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver" />
        <receiver android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"/>
                <action android:name="android.intent.action.MY_PACKAGE_REPLACED"/>
            </intent-filter>
        </receiver>
```

**Comment by vienhp1996** [comment]
same with 4.0.1

**Comment by MyHue2507** [comment]
@vienhp1996 If you don't want to update the version of  the package you can fork and then reset to a commit that has a code your current version and implement your own fix based on the version you're using
For detail: 
1. You can go to FlutterLocalNotificationsPlugin.java file 
2. Find a error function that is "scheduleNotification"
3. Fix `PendingIntent pendingIntent = PendingIntent.getBroadcast(context, notificationDetails.id, notificationIntent, PendingIntent.FLAG_UPDATE_CURRENT) ` to `PendingIntent pendingIntent = PendingIntent.getBroadcast(context, notificationDetails.id, notificationIntent, PendingIntent.FLAG_UPDATE_CURRENT  | PendingIntent.FLAG_IMMUTABLE) `
4. It worked for me

**Comment by MaikuB** [comment]
As mentioned by @MyHue2507 if you don't want to update then you need to maintain your own fork and apply the fixes you need
