### ISSUE TITLE
java.lang.NoClassDefFoundError when scheduling notifications on Android 7

### ISSUE THREAD

**Issue by jenspfahl** [MaikuB/flutter_local_notifications#1823]
**Describe the bug**
Scheduling notifications on Android 7 don't work. (But on Android 13 it works fine, I haven't tested other Android versions.)
I use your recent plugin version 12.0.4.

**To Reproduce**

Call `FlutterLocalNotificationsPlugin.zonedScheduleNotification` with a `scheduledDate` which is in the future on an Android 7 device or emulator. (Android SDK 25)

**Stacktrace**
```

E/AndroidRuntime( 4131): java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/LocalDateTime;
E/AndroidRuntime( 4131): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.zonedScheduleNotification(FlutterLocalNotificationsPlugin.java:534)
E/AndroidRuntime( 4131): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.zonedSchedule(FlutterLocalNotificationsPlugin.java:1447)
E/AndroidRuntime( 4131): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:1299)
E/AndroidRuntime( 4131): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/AndroidRuntime( 4131): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/AndroidRuntime( 4131): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/AndroidRuntime( 4131): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
E/AndroidRuntime( 4131): 	at android.os.Handler.handleCallback(Handler.java:751)
E/AndroidRuntime( 4131): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 4131): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime( 4131): 	at android.app.ActivityThread.main(ActivityThread.java:6119)
E/AndroidRuntime( 4131): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4131): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
E/AndroidRuntime( 4131): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
E/AndroidRuntime( 4131): Caused by: java.lang.ClassNotFoundException: Didn't find class "java.time.LocalDateTime" on path: xxx
E/AndroidRuntime( 4131): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime( 4131): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
E/AndroidRuntime( 4131): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime( 4131): 	... 14 more
```

**Expected behavior**

Scheduling should also work on Android 7.  It worked with plugin version 10.0.0.

**Comment by jenspfahl** [comment]
Classes under package "java.time" have been introduced with SDK 26 (Android 8). Before they cannot be used.

**Comment by MaikuB** [comment]
Please ensure you check changelog entries upon moving to newer major versions. This error would indicate you haven't done the required Android setup related to desugaring (see https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#gradle-setup) and was called out as the first breaking change in 10.0 https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/CHANGELOG.md#1000. There have been other issues raised on this where it turns out the person reporting it had also missed this step e.g. https://github.com/MaikuB/flutter_local_notifications/issues/1792
