### ISSUE TITLE
PlatformException(error, Attempt to invoke virtual method 'int java.lang.Integer.intValue()

### ISSUE THREAD

**Issue by Shahmirzali-Huseynov** [MaikuB/flutter_local_notifications#1827]
**Describe the bug**

When an app is alive, foreground (onMessage.listen), If I send a notification this error happens.  in the background no problem.

Debug console : 
```
E/MethodChannel#dexterous.com/flutter/local_notifications(11009): Failed to handle method call
E/MethodChannel#dexterous.com/flutter/local_notifications(11009): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
E/MethodChannel#dexterous.com/flutter/local_notifications(11009): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.setSmallIcon(FlutterLocalNotificationsPlugin.java:419)
E/MethodChannel#dexterous.com/flutter/local_notifications(11009): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(FlutterLocalNotificationsPlugin.java:326)
E/MethodChannel#dexterous.com/flutter/local_notifications(11009): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(FlutterLocalNotificationsPlugin.java:1140)
E/MethodChannel#dexterous.com/flutter/local_notifications(11009): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.show(FlutterLocalNotificationsPlugin.java:1456)
E/MethodChannel#dexterous.com/flutter/local_notifications(11009): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:1293)
E/MethodChannel#dexterous.com/flutter/local_notifications(11009): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#dexterous.com/flutter/local_notifications(11009): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#dexterous.com/flutter/local_notifications(11009): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#dexterous.com/flutter/local_notifications(11009): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#dexterous.com/flutter/local_notifications(11009): 	at android.os.Handler.handleCallback(Handler.java:900)
E/MethodChannel#dexterous.com/flutter/local_notifications(11009): 	at android.os.Handler.dispatchMessage(Handler.java:103)
E/MethodChannel#dexterous.com/flutter/local_notifications(11009): 	at android.os.Looper.loop(Looper.java:219)
E/MethodChannel#dexterous.com/flutter/local_notifications(11009): 	at android.app.ActivityThread.main(ActivityThread.java:8668)
E/MethodChannel#dexterous.com/flutter/local_notifications(11009): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#dexterous.com/flutter/local_notifications(11009): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/MethodChannel#dexterous.com/flutter/local_notifications(11009): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
E/flutter (11009): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
E/flutter (11009): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.setSmallIcon(FlutterLocalNotificationsPlugin.java:419)
E/flutter (11009): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(FlutterLocalNotificationsPlugin.java:326)
E/flutter (11009): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(FlutterLocalNotificationsPlugin.java:1140)
E/flutter (11009): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.show(FlutterLocalNotificationsPlugin.java:1456)
E/flutter (11009): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:1293)
E/flutter (11009): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/flutter (11009): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter (11009): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/flutter (11009): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter (11009): 	at android.os.Handler.handleCallback(Handler.java:900)
E/flutter (11009): 	at android.os.Handler.dispatchMessage(Handler.java:103)
E/flutter (11009): 	at android.os.Looper.loop(Looper.java:219)
E/flutter (11009): 	at android.app.ActivityThread.main(ActivityThread.java:8668)
E/flutter (11009): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (11009): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/flutter (11009): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
E/flutter (11009): )
E/flutter (11009): #0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:653
E/flutter (11009): #1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:296
E/flutter (11009): <asynchronous suspension>
E/flutter (11009): #2      FlutterLocalNotificationsPlugin.show
package:flutter_local_notifications/src/flutter_local_notifications_plugin.dart:234
E/flutter (11009): <asynchronous suspension>
E/flutter (11009): #3      LocalNotification.showNotification
package:ondan/…/notification/local_notification_provider.dart:92
E/flutter (11009): <asynchronous suspension>
E/flutter (11009):
```

**Comment by Davete0302** [comment]
Hello how did you solve this?

**Comment by Shahmirzali-Huseynov** [comment]
> Hello how did you solve this?
> 
> 

I forget the local notification initialize. And also you need to initialize first above your code

**Comment by Aravin** [comment]
can you please share your code?

**Comment by FidelAHM** [comment]
??

**Comment by mahdibagjani** [comment]
> > Hello how did you solve this?
> 
> I forget the local notification initialize. And also you need to initialize first above your code

Thanks. You save my time.
