### ISSUE TITLE
Android 5.1 crashes with message: Didn't find class "java.time.LocalDateTime"

### ISSUE THREAD

**Issue by OlKir** [MaikuB/flutter_local_notifications#1879]
**Describe the bug**
For my flutter app I see crash reports in Firebase for Android 5.1.1
```
Caused by java.lang.ClassNotFoundException: Didn't find class "java.time.LocalDateTime" on path: DexPathList[[zip file "/data/app/com.veggybo.mobile-1/base.apk", zip file "/data/app/com.veggybo.mobile-1/split_config.arm64_v8a.apk", zip file "/data/app/com.veggybo.mobile-1/split_config.de.apk", zip file "/data/app/com.veggybo.mobile-1/split_config.hdpi.apk"],nativeLibraryDirectories=[/data/app/com.veggybo.mobile-1/lib/arm64, /vendor/lib64, /system/lib64]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.zonedScheduleNotification(FlutterLocalNotificationsPlugin.java:540)
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.zonedSchedule(FlutterLocalNotificationsPlugin.java:1453)
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:1305)
```

**To Reproduce**
Unfortunately I don't have device running Android 5.1.1 at hand.

**Expected behavior**
I've checked LocalDateTime [documentation](https://developer.android.com/reference/java/time/LocalDateTime) and it was introduced on API level 26. 
And in Android Studio I see that for flutter_local_notification `minSDKVersion` is set to 16. 
Android 5.1 is using API level 22 and therefore crashes.

I would suggest to increase flutter_local_notification `minSDKVersion` to 26.

**Comment by MaikuB** [comment]
This issue is an indication that you haven't done the entire Android setup that is specific to desugaring. This was called out in one of the breaking changes in the changelog. There are other similar issues that have been reported as developers missed doing this so you should reference what you've done with the docs and the example app can also act as an additional reference point
