### ISSUE TITLE
 Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent. 

### ISSUE THREAD

**Issue by AliPunjabi** [MaikuB/flutter_local_notifications#1896]
Why I am getting this exception:
` Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles., null, java.lang.IllegalArgumentException: com.sj.alphatrack: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:401)
	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:484)
	at android.app.PendingIntent.getActivity(PendingIntent.java:470)
	at android.app.PendingIntent.getActivity(PendingIntent.java:434)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(FlutterLocalNotificationsPlugin.java:167)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(FlutterLocalNotificationsPlugin.java:791)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.show(FlutterLocalNotificationsPlugin.java:1054)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:947)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:178)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$handleMessageFromDart$0$DartMessenger(DartMessenger.java:206)
	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$R4HPk6oFVb-i-YR_PN9YE6kqx1I.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
))`

It was working good with lower sdk, I change it to 33, applied all changes in android manifest and gradle file.
here I am getting exception:
` Future<void> show(
    int id,
    String title,
    String body,
    NotificationDetails notificationDetails, {
    String payload,
  }) async {
    if (_platform.isAndroid) {
      await resolvePlatformSpecificImplementation<
              AndroidFlutterLocalNotificationsPlugin>()
          ?.show(id, title, body,
              notificationDetails: notificationDetails?.android,
              payload: payload);
    } `

**Comment by michalsulekintent** [comment]
same here:

 `
flutter_local_notifications: ^8.2.0
`

```
I/flutter ( 4669): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles., null, java.lang.IllegalArgumentException: ..... Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
I/flutter ( 4669): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
I/flutter ( 4669): 	at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
I/flutter ( 4669): 	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:458)
I/flutter ( 4669): 	at android.app.PendingIntent.getActivity(PendingIntent.java:444)
I/flutter ( 4669): 	at android.app.PendingIntent.getActivity(PendingIntent.java
I/flutter ( 4669): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
I/flutter ( 4669): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:18)
I/flutter ( 4669): <asynchronous suspension>
I/flutter ( 4669): #2      FlutterLocalNotificationsPlugin.show (package:flutter_local_notifications/src/flutter_local_notifications_plugin.dart:195:7)
I/flutter ( 4669): <asynchronous suspension>
```

**Comment by MaikuB** [comment]
You need to move to recent version of the plugin. There are already old issues reported on this e.g. https://github.com/MaikuB/flutter_local_notifications/issues/1476 that were solved a while back. I suggest you monitor for new releases of dependencies you use. GitHub provides a way to be notified of new releases.
