### ISSUE TITLE
java.lang.IllegalArgumentException: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.

### ISSUE THREAD

**Issue by delizondo** [MaikuB/flutter_local_notifications#1904]
Getting the following error when creating a notification in Android 13 (so far only in an emulator). 
I've tested in a physical device running Android 10, and everything works fine. 

My Android implementation is targeted to API 33

```
E/flutter (11481): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, org.schoolrunner.mobile2: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
E/flutter (11481): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles., null, java.lang.IllegalArgumentException: org.schoolrunner.mobile2: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
E/flutter (11481): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
E/flutter (11481): 	at android.app.PendingIntent.checkFlags(PendingIntent.java:401)
E/flutter (11481): 	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:484)
E/flutter (11481): 	at android.app.PendingIntent.getActivity(PendingIntent.java:470)
E/flutter (11481): 	at android.app.PendingIntent.getActivity(PendingIntent.java:434)
E/flutter (11481): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(FlutterLocalNotificationsPlugin.java:176)
E/flutter (11481): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(FlutterLocalNotificationsPlugin.java:820)
E/flutter (11481): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.show(FlutterLocalNotificationsPlugin.java:1109)
E/flutter (11481): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:996)
E/flutter (11481): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/flutter (11481): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter (11481): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/flutter (11481): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter (11481): 	at android.os.Handler.handleCallback(Handler.java:942)
E/flutter (11481): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (11481): 	at android.os.Looper.loopOnce(Looper.java:201)
E/flutter (11481): 	at android.os.Looper.loop(Looper.java:288)
E/flutter (11481): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/flutter (11481): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (11481): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/flutter (11481): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/flutter (11481): )
E/flutter (11481): #0      StandardMethodCodec.decodeEnvelope
message_codecs.dart:653
E/flutter (11481): #1      MethodChannel._invokeMethod
platform_channel.dart:315
E/flutter (11481): <asynchronous suspension>
E/flutter (11481): #2      FlutterLocalNotificationsPlugin.show
flutter_local_notifications_plugin.dart:195
E/flutter (11481): <asynchronous suspension>
E/flutter (11481):
```

**Comment by thinhnguyenphuc** [comment]
@delizondo 
@mohabbatta 

In my case, I found that `flutter pub add flutter_local_notifications` auto import version 8.2.0 to pubspec.yaml, so this issue was caused.
After changing to 13.0.0, this issue was solved.

**Comment by delizondo** [comment]
@thinhnguyenphuc works like a charm! thanks!
