### ISSUE TITLE
I don't know it showing the error below

### ISSUE THREAD

**Issue by SivaStwx** [MaikuB/flutter_local_notifications#1923]
**Describe the bug**
I've initiailized the android settings in main() but donno why I'm getting this errror need Help!!

**To Reproduce**

E/flutter ( 9515): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter ( 9515): 	at android.os.Looper.loopOnce(Looper.java:201)
E/flutter ( 9515): 	at android.os.Looper.loop(Looper.java:288)
E/flutter ( 9515): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/flutter ( 9515): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 9515): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/flutter ( 9515): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/flutter ( 9515): )
E/flutter ( 9515): #0      StandardMethodCodec.decodeEnvelope
message_codecs.dart:653
E/flutter ( 9515): #1      MethodChannel._invokeMethod
platform_channel.dart:315
E/flutter ( 9515): <asynchronous suspension>
E/flutter ( 9515): #2      FlutterLocalNotificationsPlugin.show
flutter_local_notifications_plugin.dart:195
E/flutter ( 9515): <asynchronous suspension>
E/flutter ( 9515): #3      DashboardMainState.showNotification
dashboard_main.dart:119
E/flutter ( 9515): <asynchronous suspension>
E/flutter ( 9515):

**Expected behavior**

**Sample code to reproduce the problem**

**Comment by SivaStwx** [comment]
Thanks for the reply @MaikuB as I've already resolved the issue now it is working very wel.
