### ISSUE TITLE
Notification Action Not Working with Open File

### ISSUE THREAD

**Issue by irufano** [MaikuB/flutter_local_notifications#1933]
**Describe the bug**
I use this local notification for downloaded file, and when user tap action `Open File`  came up error 
```bash
/MethodChannel#open_file(14221): Failed to handle method call
E/MethodChannel#open_file(14221): java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Context.checkPermission(java.lang.String, int, int)' on a null object reference
```

**To Reproduce**

1. I use plugin open_filex, for integration to open file
2. Handle open file function on method notificationTapBackground below:
    ```dart
     @pragma('vm:entry-point')
     static void notificationTapBackground(NotificationResponse notificationResponse) {
           var data = jsonDecode(notificationResponse.payload ?? '{}');
           OpenFilex.open(data['payload']);
     }
    ```
4. then when notif show and user tap action `Open File` the error log came up:

```bash
/MethodChannel#open_file(14221): Failed to handle method call
E/MethodChannel#open_file(14221): java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Context.checkPermission(java.lang.String, int, int)' on a null object reference
E/MethodChannel#open_file(14221): 	at androidx.core.content.ContextCompat.checkSelfPermission(ContextCompat.java:555)
E/flutter (14221): 	at com.crazecoder.openfile.OpenFilePlugin.hasPermission(OpenFilePlugin.java:84)
E/flutter (14221): 	at com.crazecoder.openfile.OpenFilePlugin.canStartActivityWithPermission(OpenFilePlugin.java:134)
E/flutter (14221): 	at com.crazecoder.openfile.OpenFilePlugin.onMethodCall(OpenFilePlugin.java:113)
E/flutter (14221): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/flutter (14221): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter (14221): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/flutter (14221): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter (14221): 	at android.os.Handler.handleCallback(Handler.java:938)
E/flutter (14221): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (14221): 	at android.os.Looper.loopOnce(Looper.java:210)
E/flutter (14221): 	at android.os.Looper.loop(Looper.java:299)
E/flutter (14221): 	at android.app.ActivityThread.main(ActivityThread.java:8168)
E/flutter (14221): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (14221): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
E/flutter (14221): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1037)
E/flutter (14221): )
E/flutter (14221): #0      StandardMethodCodec.decodeEnvelope
message_codecs.dart:653
E/flutter (14221): #1      MethodChannel._invokeMethod
platform_channel.dart:315
E/flutter (14221): <asynchronous suspension>
E/flutter (14221): #2      OpenFilex.open
open_filex.dart:58
E/flutter (14221): <asynchronous suspension>
```

**Expected behavior**

When user tap action `Open File`  can open file perfectly

**Sample code to reproduce the problem**

This is my actions:
```dart
    var android = AndroidNotificationDetails(
      defaultNotifId,
      defaultNotifName,
      channelDescription: defaultNotifDesc,
      playSound: true,
      priority: Priority.high,
      importance: Importance.max,
      color: Styles.color.primaryLight,
      largeIcon: largeIcon,
      styleInformation:
          bigPictureStyleInformation ?? const BigTextStyleInformation(''),
      actions: [
        const AndroidNotificationAction(
          'id_2',
          "Open File",
        ),
      ],
    );
```

**Comment by MaikuB** [comment]
Whilst I understand that you're using this plugin with another plugin, the exception isn't to do with this plugin so it isn't appropriate to raise an issue with this plugin. With that in mind, will be closing this issue as it's not a problem with this plugin
