### ISSUE TITLE
java.lang.NoSuchMethodError using zonedSchedule (j$.time.format.x.<clinit>)

### ISSUE THREAD

**Issue by tomc128** [MaikuB/flutter_local_notifications#1994]
**Describe the bug**
Very occasionally, when using zonedSchedule to schedule a notification, the app crashes with a fatal java exception.

<details>
<summary>Stack trace</summary>

```java
FATAL EXCEPTION: main
Process: uk.co.tdsstudios.noterly, PID: 8903
java.lang.NoSuchMethodError: No direct method <init>(II)V in class Lj$/util/concurrent/ConcurrentHashMap; or its super classes (declaration of 'j$.util.concurrent.ConcurrentHashMap' appears in /data/app/~~aghkZaYcwnblo7EBc--cTg==/androidx.test.tools.crawler-MSreWHfcl72cBXnSP8LKFQ==/base.apk!classes2.dex)
	at j$.time.format.x.<clinit>(Unknown Source:12)
	at j$.time.format.r.u(SourceFile:2)
	at j$.time.format.r.t(Unknown Source:4)
	at j$.time.format.DateTimeFormatter.<clinit>(Unknown Source:37)
	at j$.time.LocalDateTime.parse(Unknown Source:0)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.zonedScheduleNotification(Unknown Source:36)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.zonedSchedule(Unknown Source:27)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(Unknown Source:380)
	at v3.k$a.a(Unknown Source:17)
	at i3.c.l(Unknown Source:18)
	at i3.c.m(Unknown Source:40)
	at i3.c.i(Unknown Source:0)
	at i3.b.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```
</details>

**To Reproduce**
This only happens on a very small number of devices. I've only seen 5 of these reports in Firebase Crashlytics. I've managed to reproduce the issue in a Firebase robo test (I'm not sure if this is useful or not though). I've tried recreating the issue manually to no avail.

**Expected behavior**
The error should not happen.

**Sample code to reproduce the problem**
Again, I'm sorry but I do not have any sample code as this only happens very rarely. Please ask if you need any more details.

**Comment by armandojimenez** [comment]
Getting the same error, any way to fix this?

**Comment by MaikuB** [comment]
This error relates to code that the plugin calls that belongs to Java APIs so from what I could tell, not something I can help with. I'm not sure if using a higher version of the desugaring libraries would help this or not. You may need to report this issue with affected devices and how to reproduce on a forum where the Android dev team can look into this further

**Comment by armandojimenez** [comment]
I can confirm this happened only on the devices google run the app to generate the pre-launch report

**Comment by MaikuB** [comment]
16.0.0-dev.1 prerelease has bumped the desugaring library dependency but I don't know if this will solve the issue as it doesn't originate from the plugin. I would suggest trying it out to see as this would also help verify. Other thing to potentially try out is if updating the rules in the Proguard file may help
