### ISSUE TITLE
Calling `zonedSchedule` on Android 13/Android 14 Beta 2 throws `ExactAlarmPermissionException`

### ISSUE THREAD

**Issue by timobaehr** [MaikuB/flutter_local_notifications#1995]
**Describe the bug**
Calling `zonedSchedule` on Android 13/Android 14 Beta 2 throws `ExactAlarmPermissionException`.

**To Reproduce**
1. Call `FlutterLocalNotificationsPlugin.zonedSchedule`.
2. See stacktrace, no notification is scheduled.

**Expected behavior**
If the user has given permission for notifications, it should be scheduled.

**Stacktrace**
```
E/flutter (15787): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(exact_alarms_not_permitted, Exact alarms are not permitted, null, null)
E/flutter (15787): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
E/flutter (15787): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
E/flutter (15787): <asynchronous suspension>
E/flutter (15787): #2      AndroidFlutterLocalNotificationsPlugin.zonedSchedule (package:flutter_local_notifications/src/platform_flutter_local_notifications.dart:202:5)
E/flutter (15787): <asynchronous suspension>
E/flutter (15787): #3      FlutterLocalNotificationsPlugin.zonedSchedule (package:flutter_local_notifications/src/flutter_local_notifications_plugin.dart:386:7)
```

**Version details**
* `flutter_local_notifications: ^14.0.0+2`
* Android 14 - UPB2.230407.014
* Flutter 3.10.0
* Android SDK version 33.0.1

**Sample code to reproduce the problem**
```
final flutterLocalNotificationsPlugin = FlutterLocalNotificationsPlugin();

Future<void> initLocalNotifications() async {
  final notificationAppLaunchDetails = await flutterLocalNotificationsPlugin.getNotificationAppLaunchDetails();

  bool _isNotificationsInitialized = false;

  /// Indicates if the app was launched via notification
  if (notificationAppLaunchDetails?.didNotificationLaunchApp ?? false) {
    selectedNotificationPayload = notificationAppLaunchDetails!.notificationResponse?.payload;
  }

  final InitializationSettings initializationSettings = InitializationSettings(
    android: _androidSettings(),
  );

  timezone.initializeTimeZones();

  _isNotificationsInitialized = await flutterLocalNotificationsPlugin.initialize(
        initializationSettings,
        onDidReceiveBackgroundNotificationResponse: onReceivedNotification,
        onDidReceiveNotificationResponse: onReceivedNotification,
      ) ??
      false;
  Log.info('[Notifications] initialized = $_isNotificationsInitialized');
}

Future<bool> requestAndroidNotificationPermissions() async {
  if (!_isNotificationsInitialized) {
    return false;
  }

  final androidFlutterLocalNotificationsPlugin =
      flutterLocalNotificationsPlugin.resolvePlatformSpecificImplementation<AndroidFlutterLocalNotificationsPlugin>();
  return await androidFlutterLocalNotificationsPlugin?.requestPermission() ?? false;
}

Future<void> scheduleNotification({
  required int id,
  required String title,
  required String body,
  required Map<String, dynamic> payload,
  required DateTime when,
}) async {
  if (!_isNotificationsInitialized) {
    return;
  }

  final androidPlatformChannelSpecifics = AndroidNotificationDetails(
      /* channel id */ 'channelId',
      /* channel name */ 'channelName',
      channelDescription: 'channelDescription',
      importance: Importance.max,
      priority: Priority.high,
      showWhen: false);
  final platformChannelSpecifics = NotificationDetails(
    android: androidPlatformChannelSpecifics,
  );

  await flutterLocalNotificationsPlugin.zonedSchedule(
    id,
    title,
    body,
    TZDateTime.from(when, local),
    platformChannelSpecifics,
    payload: payload.toString(),
    uiLocalNotificationDateInterpretation: UILocalNotificationDateInterpretation.absoluteTime,
  );
}
```

**Comment by timobaehr** [comment]
Duplicate of https://github.com/MaikuB/flutter_local_notifications/issues/1526 / https://github.com/MaikuB/flutter_local_notifications/issues/1906 ?
