### ISSUE TITLE
 java.lang.NullPointerException createNotification on Android 

### ISSUE THREAD

**Issue by JangJuMyeong** [MaikuB/flutter_local_notifications#2065]
When calling Notification in Android, the following error occurs.

```
E/MethodChannel#dexterous.com/flutter/local_notifications(21446): Failed to handle method call
E/MethodChannel#dexterous.com/flutter/local_notifications(21446): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Intent android.content.Intent.setAction(java.lang.String)' on a null object reference
E/MethodChannel#dexterous.com/flutter/local_notifications(21446): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(FlutterLocalNotificationsPlugin.java:243)
E/MethodChannel#dexterous.com/flutter/local_notifications(21446): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(FlutterLocalNotificationsPlugin.java:1217)
E/MethodChannel#dexterous.com/flutter/local_notifications(21446): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.show(FlutterLocalNotificationsPlugin.java:1537)
E/MethodChannel#dexterous.com/flutter/local_notifications(21446): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:1379)
E/MethodChannel#dexterous.com/flutter/local_notifications(21446): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#dexterous.com/flutter/local_notifications(21446): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#dexterous.com/flutter/local_notifications(21446): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#dexterous.com/flutter/local_notifications(21446): 	at android.os.Handler.handleCallback(Handler.java:883)
E/MethodChannel#dexterous.com/flutter/local_notifications(21446): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/MethodChannel#dexterous.com/flutter/local_notifications(21446): 	at android.os.Looper.loop(Looper.java:237)
E/MethodChannel#dexterous.com/flutter/local_notifications(21446): 	at android.app.ActivityThread.main(ActivityThread.java:8167)
E/MethodChannel#dexterous.com/flutter/local_notifications(21446): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#dexterous.com/flutter/local_notifications(21446): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
E/MethodChannel#dexterous.com/flutter/local_notifications(21446): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
I/flutter (21446): PlatformException(error, Attempt to invoke virtual method 'android.content.Intent android.content.Intent.setAction(java.lang.String)' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Intent android.content.Intent.setAction(java.lang.String)' on a null object reference
I/flutter (21446): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(FlutterLocalNotificationsPlugin.java:243)
I/flutter (21446): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(FlutterLocalNotificationsPlugin.java:1217)
I/flutter (21446): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.show(FlutterLocalNotificationsPlugin.java:1537)
I/flutter (21446): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:1379)
I/flutter (21446): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
I/flutter (21446): 	at io.flutter.embedding.engine.dart.DartMessenger.invo

```

here is my Notification class code 

```
class WhichiPetLocalNotification {
  WhichiPetLocalNotification._();

  static AndroidNotificationChannel channel = const AndroidNotificationChannel(
    'high_importance_channel', // id
    'High Importance Notifications', // title
    description:
        'This channel is used for important notifications.', // description
    importance: Importance.high,
  );

  static FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
      FlutterLocalNotificationsPlugin();

  static init() async {
    var initialzationSettingsAndroid =
        const AndroidInitializationSettings('@mipmap/app_icon');

    var initialzationSettingsIOS = const DarwinInitializationSettings(
      requestSoundPermission: false,
      requestBadgePermission: false,
      requestAlertPermission: false,
    );

    // await flutterLocalNotificationsPlugin
    //     .resolvePlatformSpecificImplementation<
    //         AndroidFlutterLocalNotificationsPlugin>()
    //     ?.createNotificationChannel(channel);

    InitializationSettings initializationSettings = InitializationSettings(
        android: initialzationSettingsAndroid, iOS: initialzationSettingsIOS);

    await flutterLocalNotificationsPlugin.initialize(initializationSettings);
  }

  static requestNotificationPermission() {
    if (Platform.isIOS) {
      flutterLocalNotificationsPlugin
          .resolvePlatformSpecificImplementation<
              IOSFlutterLocalNotificationsPlugin>()
          ?.requestPermissions(alert: true, badge: true, sound: true);
    } else {
      flutterLocalNotificationsPlugin
          .resolvePlatformSpecificImplementation<
              AndroidFlutterLocalNotificationsPlugin>()
          ?.requestPermission();
    }
  }

  static Future<void> showNotification(
      int id, String? title, String? body) async {
    AndroidNotificationDetails androidNotificationDetails =
        AndroidNotificationDetails(channel.id, channel.name,
            importance: Importance.max,
            priority: Priority.max,
            showWhen: false);
    DarwinNotificationDetails iosNotificationDetails =
        const DarwinNotificationDetails();

    NotificationDetails notificationDetails = NotificationDetails(
        android: androidNotificationDetails, iOS: iosNotificationDetails);
    try {
      await flutterLocalNotificationsPlugin.show(
        id,
        title,
        body,
        notificationDetails,
      );
    } catch (err) {
      print(err);
    }
  }
}
```

and call init main() 

```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
  ]);

  await WhichiPetLocalNotification.init();

  runApp(_App());
}
```
and pressed button call method

```
  showNotifiation() async {
    await WhichiPetLocalNotification.showNotification(3, 'hi', 'hoho');
  }
```
The icon name has been changed to app_icon. 

It doesn't seem to be a problem with icon settings, but is it an initialization problem? Can you tell me what could be the problem?

**Comment by JangJuMyeong** [comment]
I fixed the problem by modifying as below.

```
<intent-filter>
           <action android:name="android.intent.action.MAIN"/>
           <category android:name="android.intent.category.LAUNCHER"/>
</intent-filter>
 <intent-filter>
           <action android:name="android.intent.action.VIEW"/>
           <category android:name="android.intent.category.DEFAULT"/>
           <category android:name="android.intent.category.BROWSABLE"/>
```
