### ISSUE TITLE
[Error] PlatformException occured on `show` function (android device)

### ISSUE THREAD

**Issue by Uday-kiran9147** [MaikuB/flutter_local_notifications#2101]
**Describe the bug**
Exception has occurred.
PlatformException (PlatformException(error, Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.setSmallIcon(FlutterLocalNotificationsPlugin.java:451)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(FlutterLocalNotificationsPlugin.java:352)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(FlutterLocalNotificationsPlugin.java:1225)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.show(FlutterLocalNotificationsPlugin.java:1545)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:1387)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8249)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)
))

**To Reproduce**
      await _flutterLocalNotifications.show(0, remoteMessage.notification!.title,remoteMessage.notification!.body, notificationDetails);
      The above function giving the PlatformException Error(
![notification](https://github.com/MaikuB/flutter_local_notifications/assets/105251622/5652a3a5-d248-4a0b-8aef-360025af0e58)
message above pasted).

**Expected behavior**
notification has to pop up

**Sample code to reproduce the problem**
```
  Future<void> showNotification(RemoteMessage remoteMessage)async{
    // notification channel for id and name 
    // AndroidNotificationChannel androidNotificationChannel = AndroidNotificationChannel("high_importance_channel" , "high_importance_channel",description: 'This channel is used for important notifications.',playSound: true,importance: Importance.high,);
    const AndroidNotificationChannel androidNotificationChannel = AndroidNotificationChannel('high_importance_channel','High Importance Notifications',description: 'This channel is used for important notifications.',importance: Importance.max,);

    // Android notification 
    AndroidNotificationDetails androidNotificationDetails = AndroidNotificationDetails(androidNotificationChannel.id, androidNotificationChannel.name,importance: Importance.high,priority: Priority.high,ticker: 'ticker',channelDescription: "channel description");
    // Android notification details
    DarwinNotificationDetails darwinNotificationDetails = DarwinNotificationDetails(presentBadge: true,presentSound: true,presentAlert: true,);

    // notification details for android and ios
    NotificationDetails notificationDetails = NotificationDetails(android: androidNotificationDetails,iOS: darwinNotificationDetails);

   FlutterLocalNotificationsPlugin _flutterLocalNotifications = FlutterLocalNotificationsPlugin();

     await _flutterLocalNotifications.show(0, remoteMessage.notification!.title,remoteMessage.notification!.body, notificationDetails);
    
    // Push the notification to Frontend
    await localNotificationInitilization(remoteMessage);
  }
```

**Comment by knatnaela** [comment]
any solution for this error?

**Comment by Uday-kiran9147** [comment]
Looking for a solution.

**Comment by MaikuB** [comment]
This issue is occurring as you've not specified/provided a notification icon properly. Most apps will typically do so by calling this plugin's `initialize()` method and passing the default icon that should be used. I would guess you've not done so as the code snippet shared indicates the lack of calling `initialize()` unless you had done this elsewhere in the app. Regardless this is an issue with the application not using the plugin properly so will close this as it's not an issue with the plugin itself

**Comment by caseycrogers** [comment]
There are a ton of issues in this repo from people not initializing properly on Android and getting arcane error messages. Maybe you could add some asserts in `show` etc that throw with informative error messages if the service has not been properly initialized for the current platform?
