### ISSUE TITLE
[Question]: If schedule notifications not working in Android 14?

### ISSUE THREAD

**Issue by weluid** [MaikuB/flutter_local_notifications#2247]
![290110248-fbaa73cb-f097-4090-b58d-d0823ab43bb7](https://github.com/MaikuB/flutter_local_notifications/assets/124319560/5828bf82-831e-47e1-96cf-86635a520fab)

I got this message on Google Play.
Could you tell me how to get around it, I think it appeared on android 14 because of the use of local notifications?

**Comment by davidjovelabhouse** [comment]
I also recently got a crashlytics new crash on the same topic.
It is only happening to some Android 14 users and the weird part is that i'm only using _AndroidScheduleMode.inexactAllowWhileIdle_, so there is nowhere in the code I'm requesting to schedule an exact alarm. May inexact alarms also need the permission in some cases from Android 14 onwards?

My package version is 15.1.1

This are the stack traces:

```
Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver: java.lang.SecurityException: Caller com.example needs to hold android.permission.SCHEDULE_EXACT_ALARM or android.permission.USE_EXACT_ALARM to set exact alarms.
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4499)
       at android.app.ActivityThread.-$$Nest$mhandleReceiver()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2281)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:205)
       at android.os.Looper.loop(Looper.java:294)
       at android.app.ActivityThread.main(ActivityThread.java:8248)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```
```
Caused by java.lang.SecurityException: Caller com.example needs to hold android.permission.SCHEDULE_EXACT_ALARM or android.permission.USE_EXACT_ALARM to set exact alarms.
       at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
       at android.os.Parcel.createException(Parcel.java:3041)
       at android.os.Parcel.readException(Parcel.java:3024)
       at android.os.Parcel.readException(Parcel.java:2966)
       at android.app.IAlarmManager$Stub$Proxy.set(IAlarmManager.java:311)
       at android.app.AlarmManager.setImpl(AlarmManager.java:1084)
       at android.app.AlarmManager.setImpl(AlarmManager.java:1044)
       at android.app.AlarmManager.setAlarmClock(AlarmManager.java:912)
       at androidx.core.app.s.b(:2)
       at androidx.core.app.u.a(:10)
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.setupAlarm(:44)
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.zonedScheduleNotification(:58)
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.rescheduleNotifications(:36)
       at com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver.onReceive(:38)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4490)
       at android.app.ActivityThread.-$$Nest$mhandleReceiver()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2281)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:205)
       at android.os.Looper.loop(Looper.java:294)
       at android.app.ActivityThread.main(ActivityThread.java:8248)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Comment by MaikuB** [comment]
@weluid have you checked to make sure that you're on the latest version of the plugin? The permission checks were added in 16. @davidjovelabhouse's issue makes sense given the version mentioned is 15.1.1

**Comment by MaikuB** [comment]
Closing due to lack of response and there have been updates to the plugin to Android 14. I've also seen an app that use to have this message shown on the Google Play console that no longer had the message appear after pointing to the latest/recent versions of the plugin

**Comment by orgesballa** [comment]
@MaikuB to not open a new ticket, what if I cannot upgrade to latest version? I have upgraded my app from Flutter 1.22.4 (4 years old) to Flutter 2.10.5 and dart 2.16, however due to deadline 31 August I cannot upgrade anymore. 

Is there a workaround for versions older than 16.0? I am using 12.0.4 now.

**Comment by Jakuzeisme** [comment]
@orgesballa the notifications don't come in without use exact alarm and schedule exact alarm on Android 14.
Would  love to know how u solved yours.
Also does the schedule exact alarm require special approval like the use exact alarm. 
Just a quick summary will do, don't wanna take yo time
