### ISSUE TITLE
[Crash] Android 14 crashes when using inexactAllowWhileIdle and SCHEDULE_EXACT_ALARM missing

### ISSUE THREAD

**Issue by davidjovelabhouse** [MaikuB/flutter_local_notifications#2248]
It is only happening to some Android 14 users and the weird part is that i'm only using _AndroidScheduleMode.inexactAllowWhileIdle_, so there is nowhere in the code I'm requesting to schedule an exact alarm. May inexact alarms also need the permission in some cases from Android 14 onwards?

My package version is 15.1.1

This are the stack traces:

```
Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver: java.lang.SecurityException: Caller com.example needs to hold android.permission.SCHEDULE_EXACT_ALARM or android.permission.USE_EXACT_ALARM to set exact alarms.
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4499)
       at android.app.ActivityThread.-$$Nest$mhandleReceiver()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2281)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:205)
       at android.os.Looper.loop(Looper.java:294)
       at android.app.ActivityThread.main(ActivityThread.java:8248)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```
```
Caused by java.lang.SecurityException: Caller com.example needs to hold android.permission.SCHEDULE_EXACT_ALARM or android.permission.USE_EXACT_ALARM to set exact alarms.
       at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
       at android.os.Parcel.createException(Parcel.java:3041)
       at android.os.Parcel.readException(Parcel.java:3024)
       at android.os.Parcel.readException(Parcel.java:2966)
       at android.app.IAlarmManager$Stub$Proxy.set(IAlarmManager.java:311)
       at android.app.AlarmManager.setImpl(AlarmManager.java:1084)
       at android.app.AlarmManager.setImpl(AlarmManager.java:1044)
       at android.app.AlarmManager.setAlarmClock(AlarmManager.java:912)
       at androidx.core.app.s.b(:2)
       at androidx.core.app.u.a(:10)
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.setupAlarm(:44)
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.zonedScheduleNotification(:58)
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.rescheduleNotifications(:36)
       at com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver.onReceive(:38)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4490)
       at android.app.ActivityThread.-$$Nest$mhandleReceiver()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2281)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:205)
       at android.os.Looper.loop(Looper.java:294)
       at android.app.ActivityThread.main(ActivityThread.java:8248)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

_Originally posted by @davidjovelabhouse in https://github.com/MaikuB/flutter_local_notifications/issues/2247#issuecomment-1970713978_

**Comment by mahmoud-othmane** [comment]
`SCHEDULE_EXACT_ALARM` is not granted by default starting Android 14, so I guess the package has to ask for permissions whenever a scheduled alarm is needed.
We got this warning on the Play Store when we started targeting Android 14.
<img width="952" alt="Screenshot 2024-03-01 at 1 01 19 PM" src="https://github.com/MaikuB/flutter_local_notifications/assets/40755715/909cad78-2477-44b1-9b38-ad7078f9729c">

**Comment by MaikuB** [comment]
I pushed out a new version to run a permissions check when using alarm clock as the schedule mode as it looks like it got missed as part of this PR https://github.com/MaikuB/flutter_local_notifications/pull/1997.

@davidjovelabhouse the stack trace you shared looks odd as it would indicate it's `alarmClock` as the schedule mode

**Comment by MaikuB** [comment]
@davidjovelabhouse another thing is you are on an older version of the plugin. The permission checks relevant to Android 14 were added in 16.0

**Comment by MaikuB** [comment]
Closer to due lack of further response and info previously shared would indicate issue was from using an outdated version of the plugin
