### ISSUE TITLE
zonedSchedule function not working on andriod release mode 

### ISSUE THREAD

**Issue by adilInnsof** [MaikuB/flutter_local_notifications#2265]
` PlatformException(error, Missing type parameter., null, java.lang.RuntimeException: Missing type parameter.
	at p7.a.d(SourceFile:1)
	at p7.a.<init>(SourceFile:1)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin$a.<init>(Unknown Source:0)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.loadScheduledNotifications(Unknown Source:25)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.saveScheduledNotification(Unknown Source:0)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.zonedScheduleNotification(Unknown Source:67)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.zonedSchedule(SourceFile:1)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(SourceFile:1)
	at b9.k$a.a(SourceFile:1)
	at s8.c.l(SourceFile:1)
	at s8.c.m(SourceFile:1)
	at s8.c.g(SourceFile:1)
	at s8.b.run(SourceFile:1)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8893)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
)
       at StandardMethodCodec.decodeEnvelope(message_codecs.dart:651)
       at MethodChannel._invokeMethod(platform_channel.dart:334)
       at AndroidFlutterLocalNotificationsPlugin.zonedSchedule(platform_flutter_local_notifications.dart:191)
       at FlutterLocalNotificationsPlugin.zonedSchedule(flutter_local_notifications_plugin.dart:352)
       at NotificationServices.sheduleNotificationDaily(notification_services.dart:188
      `
 the zonedSchedule function is not working on android release mode returns the above exception

**Comment by adilInnsof** [comment]
i forgot to add the proguard-rules.pro file as mentioned in the documentation
