### ISSUE TITLE
zonedSchedule function not working in release mode after adding flavors

### ISSUE THREAD

**Issue by adilInnsof** [MaikuB/flutter_local_notifications#2269]
**After adding flavors  i am getting following error while calling zhonedshedule function**
does this plugin not support flavors?

\ PlatformException(error, TypeToken must be created with a type argument: new TypeToken<...>() {}; When using code shrinkers (ProGuard, R8, ...) make sure that generic signatures are preserved., null, java.lang.IllegalStateException: TypeToken must be created with a type argument: new TypeToken<...>() {}; When using code shrinkers (ProGuard, R8, ...) make sure that generic signatures are preserved.
	at q3.a.e(SourceFile:41)
	at q3.a.<init>(SourceFile:1)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin$a.<init>(Unknown Source:0)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.loadScheduledNotifications(Unknown Source:25)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.saveScheduledNotification(Unknown Source:0)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.repeatNotification(Unknown Source:148)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.repeat(SourceFile:18)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(SourceFile:357)
	at c4.k$a.a(SourceFile:18)
	at T3.c.l(SourceFile:19)
	at T3.c.m(SourceFile:42)
	at T3.c.e(SourceFile:1)
	at T3.b.run(SourceFile:13)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8893)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
)`

**Comment by wayupdev** [comment]
Hello @adilInnsof, how did you solve this issue ?

**Comment by adilInnsof** [comment]
@wayupdev  That was my mistake i just forgot to add the proguard-rules.pro file as told on their documentation

**Comment by wayupdev** [comment]
I can't find any mention of this configuration in the current documentation, could you send me the link?

**Comment by wayupdev** [comment]
My bad, just found it ! Thank you ;)
