### ISSUE TITLE
Upgrading from version 17.2.3 to 17.2.4 may have introduced crashing behavior

### ISSUE THREAD

**Issue by leaf-node** [MaikuB/flutter_local_notifications#2446]
**Describe the bug**

App randomly crashes every few hours, or crashes when trying to start it after the app is stopped by the system following app optimization. My app is using a foreground service notification that at least some of the time may be persisting when the app and its background process gets closed by the user.

Tested on Android 15 with 34 target SDK with flutter_local_notifications 17.2.4.

**To Reproduce**

1. Upgrade GrapheneOS version
2. Reboot phone
3. Wait for apps to optimize
4. Press GrapheneOS notification to restart apps
5. Start app manually
6. It crashes

Crashing also occurs randomly every few hours. I started noticing this issue in the last few days, about a week after I upgraded dependencies for my app, including this module from version 17.2.3 to 17.2.4.

**Expected behavior**

The app shouldn't crash.

**Sample code to reproduce the problem**

I don't have source code available for this yet, hoping that it's an easy bug to solve. If not, please let me know, and I'll consider creating a basic app with this problem. Thanks!

** Crash Logs **

```
type: crash
osVersion: google/shiba/shiba:15/AP3A.241005.015/2024110400:user/release-keys
flags: dev options enabled
package: com.example.foo:1, targetSdk 34
process: com.example.foo
processUptime: 92 + 323 ms

java.lang.RuntimeException: Unable to start service com.dexterous.flutterlocalnotifications.ForegroundService@c4128db with null: java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.Serializable android.content.Intent.getSerializableExtra(java.lang.String, java.lang.Class)' on a null object reference
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5199)
at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2478)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loopOnce(Looper.java:232)
at android.os.Looper.loop(Looper.java:317)
at android.app.ActivityThread.main(ActivityThread.java:8744)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
at com.android.internal.os.ExecInit.main(ExecInit.java:50)
at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.Serializable android.content.Intent.getSerializableExtra(java.lang.String, java.lang.Class)' on a null object reference
at com.dexterous.flutterlocalnotifications.b1.a(SourceFile:1)
at com.dexterous.flutterlocalnotifications.ForegroundService.onStartCommand(Unknown Source:10)
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5181)
... 11 more
```

**Comment by leaf-node** [comment]
I'm still getting this on version 18.0.0.

**Comment by leaf-node** [comment]
I'm also seeing this on the 17.2.3 version of the library, but I don't recall this error before, so it's possible that the crashing behavior could be due to a bug in my code.

**Comment by leaf-node** [comment]
I believe that this is where the error is occuring:

https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/ForegroundService.java#L21

I wonder if the `ForegroundServiceStartParameter` class' static variables are not initialized before they are accessed? One possible reason for that is that there could be a circular dependency between classes, and so initialization order is not guaranteed. However, a I didn't see any circular dependencies after a brief check.

Also, another user of my app reports no crashing behavior, while I was seeing a lot of crashes for a while.

**Comment by Levi-Lesches** [comment]
Judging by the error, it's not saying the parameters are null, which would be `EXTRA` and `.class` like you're suggesting, but rather that the code is trying to call `android.content.Intent.getSerializableExtra` on a null reference. 

So the intent itself is null. This is also indicated by `Unable to start service ... with null`, meaning the intent passed to the service is null. 

A quick look at [the Android Services docs](https://developer.android.com/develop/background-work/services) shows that `onStartCommand` must return with specific values. In this case, we're interested in [`START_STICKY`](https://developer.android.com/reference/android/app/Service#START_STICKY): 

> If the system kills the service after [onStartCommand()](https://developer.android.com/reference/android/app/Service#onStartCommand(android.content.Intent,%20int,%20int)) returns, recreate the service and call [onStartCommand()](https://developer.android.com/reference/android/app/Service#onStartCommand(android.content.Intent,%20int,%20int)), but do not redeliver the last intent. Instead, the system calls [onStartCommand()](https://developer.android.com/reference/android/app/Service#onStartCommand(android.content.Intent,%20int,%20int)) with a null intent unless there are pending intents to start the service. In that case, those intents are delivered. This is suitable for media players (or similar services) that are not executing commands but are running indefinitely and waiting for a job.

You can get yourself into this situation with the plugin if you call `plugin.startForegroundService()` and leave `startType` to `AndroidServiceStartType.startSticky`, which is the default.

**Comment by EPNW-Eric** [comment]
@Levi-Lesches thanks for the good issue analysis and brining this to my attention!

I've already looked into it provide a write up tomorrow.

**Comment by EPNW-Eric** [comment]
My reason for needing a foreground service was audio recording and processing using dart. By starting a foreground service the process is treated as in foreground (even if not visible) and my dart code continued running.

I think the best solution would be using `START_REDELIVER_INTENT` as default and warning about `START_STICKY`. Also, on second thought `START_STICKY` makes only sense if the services would actualy do something, but I guess most flutter developers only use the foreground service like me to just keep the process in foreground.

As a sidenote, while I was thinking about the bug today I considered storing the start parameters in a static variable instead of an intent, but I then realized, that when the process is terminated by the system while under load, the variable would also lose its value, so this is not a solution.

About wheter to remove the foreground feature or not this is my opinion: The fact that this bug surfaced shows that people are using the feature. Foreground services are tightly connected to notifications. Moving foreground services in to a new package would also mean that the new package would need to redo a lot of the notification related things this package already solves.

If we want to keep the feature I can provide a PR until Friday (but feel free to do it yourself if you can get to it earlier).

**Comment by Levi-Lesches** [comment]
Right, to clarify, I don't think anyone wants to remove the feature. If anything, I was suggesting removing or at least deprecating the start sticky option. Seems like you agree that flag isn't inherently useful. 

In case we do keep it, what should we do on a null intent? Just return and quit? It seems the startup code you wrote is very dependent on there being an intent with some data, so I'm not sure what useful value the plugin has if there is no intent. 

If the solution is as simple as returning if null and deprecating the flag, I can take care of it. If there's something else that should be done, a PR would be great.

**Comment by leaf-node** [comment]
Thanks for both of your help with this. : ) I am using <https://github.com/AhsanSarwar45/flutter_boot_receiver> to restart the app if the OS reboots, and it may eventuall also handle restarting after app upgrades.

I see that I can specify the service start type here: <https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/AndroidFlutterLocalNotificationsPlugin/startForegroundService.html>, but it's not yet clear to me how to update `AndroidManifest.xml` this information. I'll keep doing research on that.

**Comment by leaf-node** [comment]
I should note that I tried wiping and uninstalling the app, and the crashing stopped. So hopefully I can reproduce the bug on a new build the next time GrapheneOS has an update for my phone.

I wonder if there is an interplay between app optimizations after a phone reboot on the one hand, and the fact that `flutter_boot_receiver` doesn't actually handle restarting the app after app upgrades yet? It's just odd that it keeps happening after that condition occurs.

**Comment by EPNW-Eric** [comment]
I'm not sure if I would remove the flag, just because I don't see a usecase yet, doesn't mean some dev out there is actually benefiting from it...

I'm not even sure if I would change something in native code. Yes, the app crashes but maybe thats a good thing: Imagine if it does not crash and just returns; users would not reach out to developers because from their perspective, the app would work "fine". Also developers investigating the reason why sometimes there seems to be no foreground service in their app would have no clue where to start since there is no kind logging.

If we were about to do anything in native code, an idea might be to throw an even more explicit exception instead of a null pointer:
```java
throw new 
IllegalStateException("The intent carrying the notification data is null, most likley beause the service start type was START_STICKY.\r\nConsider using START_REDELIVER_INTENT and see https://github.com/MaikuB/flutter_local_notifications/issues/2446 for more details.");
```
Nethertheless we should we warn about `START_STICKY` in the documentation and make `START_REDELIVER_INTENT` the default.


@leaf-node Hm an interplay with optimizers is an interesting thought. I never actually came across a situation where a system under load terminates an app with a foreground service. Maybe optimizers are way more strict here and start "resource saving" earlyer.

**Comment by EPNW-Eric** [comment]
@leaf-node thanks for the report! Could you do some testing with START_NOT_STICKY? Since we are currently discussing in the PR if we should remove the other start options I wonder if you are able to achieve your desired behavior with this?

**Comment by leaf-node** [comment]
Yes, I can test out `START_NOT_STICKY` at some point and see if it works for me. My hunch is that this will not be something that my app needs, if the `START_REDELIVER_INTENT` (and / or `START_STICKY`) is the only way of resuming an interrupted foreground service. (For starting after boot, I am using a package for that, and may use my own code to replace it).

As for `START_STICKY`, it could also work, right? It may also be appropriate for my case, because i don't need to deliver any information about the reason for the previous foreground service to the new one. I think that the looping behavior was because the method affected by it was crashing when it didn't know what to do with `null`. If it returned any of the three values (most likely `START_STICKY`), would it work then too, right?

**Comment by Levi-Lesches** [comment]
We could theoretically make start sticky work by just returning if the intent is null. But the question we ran into is, fundamentally, what work is being done that the notification should be reinstated? 
 
 Other packages allow you to link Dart code to your foreground service, but this plugin just makes notification and that's it. So if the foreground service is sticky, the user will get notification again, but no actual logic will be running to justify it. For that reason we are thinking of removing the start type option entirely and only use start not sticky. 

In other words, say you're using this plugin to start a foreground service because you're downloading some files. The download is only happening in your dart code, not in the service. Well having a service makes it less likely your app will be killed, but if it is, and the system reinstates it because it's sticky, there's no way for the Java code to restart the download operation that's happening in Dart. 

There are other packages that actually let you pass a function when creating a foreground service, and that function is actually tied to the service such that it will be restarted as well. But that's a bit out of scope for this plugin now

**Comment by leaf-node** [comment]
Using `START_NOT_STICKY` does not lead to any crashes for me after apps are optimized in GrapheneOS and then restarted automatically.

**Comment by hmagdyadel** [comment]
## Solution: Handle App Restart Gracefully

I encountered this exact issue on **Android 13 and Android 15+** where toggling notification permissions through system settings crashes the app with `Lost connection to device`.

### Root Cause
This is **intentional Android OS behavior**, not a Flutter bug. When notification permissions are revoked while the app is in the foreground, Android kills and attempts to restore the app process. Flutter's navigator tries to restore routes that no longer have valid state, resulting in a white screen or crash.

### Solution

**1. Warn Users with a Dialog/Bottom Sheet**

Show users a warning before redirecting to system settings:

```dart
Future<void> _handleNotificationToggle() async {
  final bool isCurrentlyEnabled = activeNotification;

  await showDialog(
    context: context,
    builder: (ctx) => AlertDialog(
      title: Text(isCurrentlyEnabled ? 'Disable Notifications' : 'Enable Notifications'),
      content: Text(
        'You will be redirected to settings. The app may restart when you change this permission.'
      ),
      actions: [
        TextButton(
          onPressed: () => Navigator.pop(ctx),
          child: Text('Cancel'),
        ),
        TextButton(
          onPressed: () async {
            Navigator.pop(ctx);
            await openAppSettings(); // from permission_handler package
          },
          child: Text('Go to Settings'),
        ),
      ],
    ),
  );
}
```

**2. Handle Clean Restart in MainActivity.kt**

Prevent white screen by forcing a clean app restart when Android tries to restore a killed process:

```kotlin
package your.package.name

import io.flutter.embedding.android.FlutterActivity
import android.content.Intent
import android.os.Bundle

class MainActivity : FlutterActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        // If Android is restoring a killed process, restart clean
        if (savedInstanceState != null) {
            val intent = Intent(this, MainActivity::class.java)
            intent.addFlags(
                Intent.FLAG_ACTIVITY_NEW_TASK or
                Intent.FLAG_ACTIVITY_CLEAR_TASK or
                Intent.FLAG_ACTIVITY_CLEAR_TOP
            )
            startActivity(intent)
            finish()
            return
        }
        super.onCreate(savedInstanceState)
    }
}
```

**3. Update AndroidManifest.xml**

Ensure `singleTop` launch mode:

```xml
<activity
    android:name=".MainActivity"
    android:launchMode="singleTop"
    android:exported="true"
    ...>
```

### Result

- ✅ Users are warned the app may restart
- ✅ No white screen crash
- ✅ App restarts cleanly with a brief delay (~1-2 seconds)
- ✅ Same UX as major apps like WhatsApp, Instagram, etc.

### Note
The brief restart delay is unavoidable — it's the time Android needs to kill and reinitialize the app process. This is **normal behavior** and significantly better than crashing or showing a white screen.

**Tested on:** Android 13, Android 14, Android 15+ (both emulator and real devices)
