### ISSUE TITLE
Scheduled Notification Does not work.

### ISSUE THREAD

**Issue by vikasgola** [MaikuB/flutter_local_notifications#250]
Notifications are not displaying. I am working with Android 9.
Here is the code snippet which I have used.

**AndroidManifest.xml file**
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="some package">

    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.WAKE_LOCK" />

    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="some app"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <receiver android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver" />
        <receiver android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"></action>
            </intent-filter>
        </receiver>
    </application>
</manifest>
```
**In Main.dart file**
```
@override
  initState() {
    super.initState();
    flutterLocalNotificationsPlugin = FlutterLocalNotificationsPlugin();
    var initializationSettingsAndroid =
        AndroidInitializationSettings('@mipmap/ic_launcher');
    var initializationSettingsIOS = IOSInitializationSettings();
    var initializationSettings = InitializationSettings(
        initializationSettingsAndroid, initializationSettingsIOS);
    flutterLocalNotificationsPlugin.initialize(initializationSettings,
        onSelectNotification: onSelectNotification);
    callNotifications();
  }

Future<void> scheduleNotification() async {
    var scheduledNotificationDateTime =
        new DateTime.now().add(new Duration(seconds: 5));
    print(scheduledNotificationDateTime.toString());
    var androidPlatformChannelSpecifics2 = new AndroidNotificationDetails(
        'contests_notifications',
        'Notification',
        'your channel description',
        importance: Importance.Max,
        priority: Priority.High);
    var iOSPlatformChannelSpecifics2 = new IOSNotificationDetails();
    NotificationDetails platformChannelSpecifics2 = new NotificationDetails(
        androidPlatformChannelSpecifics2, iOSPlatformChannelSpecifics2);
    await flutterLocalNotificationsPlugin.schedule(
        0,
        'scheduled $scheduledNotificationDateTime',
        'scheduled body',
        scheduledNotificationDateTime,
        platformChannelSpecifics2);
  }

  callNotifications() async {
    await scheduleNotification().then((onValue) {
      print("notification Done");
    }).catchError((onError) {
      print("ERROR: $onError");
    });
  }
```

**Comment by MaikuB** [comment]
Do you see an error and what device did you try this on? What steps have taken to to debug the problem?

For example:
- does it work on an emulator?
- have you tried running the example app (clone the repository to do this
- does calling `show` work?

**Comment by MaikuB** [comment]
Also should mention that all method calls are asynchronous. The code you've used isn't waiting for initialisation to be done before you try to schedule notifications

**Comment by vikasgola** [comment]
@MaikuB Yes, calling <code> show </code> works But it seems <code> schedule </code> does not work. Also, it does not show any kind of error.

**Comment by MaikuB** [comment]
There are a few points in my responses that don't seem to have looked at based on your response that I'd suggest you look at

**Comment by vikasgola** [comment]
@MaikuB I have tried to run it in the emulator. But it did not work in that also. I am currently trying to run the example app given in the repo.

**Comment by MaikuB** [comment]
I've copied your code into the example app and seems to work fine. Though as pointed out earlier, `initialise` is an asynchronous method call so you really should wait for that to be done before invoking `callNotifications`

**Comment by vikasgola** [comment]
@MaikuB I have tried calling <code> callNotifications </code> functions in the <code> build </code> function. It still does not work.

Waiting for example app to finish "Initializing gradle...". It's saying " (This is taking an unexpectedly long time.) ".

**Comment by vikasgola** [comment]
@MaikuB Is there any callback function for the <code> initialise </code> function. e.g. then?

**Comment by MaikuB** [comment]
you shouldn't be calling a method like that as part of your `build` function as that would be invoked every time state changes and your UI gets re-rendered. Yes you can use `then` like JS promises that you were already doing in other parts of your code

**Comment by vikasgola** [comment]
Here is my updated <code> initState </code> function.
```
@override
  initState() {
    super.initState();

    var initializationSettingsAndroid =
        AndroidInitializationSettings('@mipmap/ic_launcher');
    var initializationSettingsIOS = IOSInitializationSettings();
    var initializationSettings = InitializationSettings(
        initializationSettingsAndroid, initializationSettingsIOS);
    flutterLocalNotificationsPlugin
        .initialize(initializationSettings,
            onSelectNotification: this.onSelectNotification)
        .then((onValue) async {
      await this.scheduleNotification().then((onValue) {
        print("notification Done");
      }).catchError((onError) {
        print("ERROR: $onError");
      });
    });
  }

```

Still no Luck!

**Comment by MaikuB** [comment]
Would need a repo to look at this

**Comment by MaikuB** [comment]
I'm also curious to know if the example app works for you but as mentioned earlier, you'll need to clone the repo for it to work

**Comment by vikasgola** [comment]
```
Launching lib/main.dart on Redmi Note 4 in debug mode...
Initializing gradle...                                              0.9s
Resolving dependencies...                                           2.6s
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                         4.7s
Built build/app/outputs/apk/debug/app-debug.apk.
I/ola.coding_lis(26318): The ClassLoaderContext is a special shared library.
I/DynamiteModule(26318): Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:20290
I/DynamiteModule(26318): Selected remote version of com.google.android.gms.ads.dynamite, version >= 20290
D/DynamitePackage(26318): Instantiated singleton DynamitePackage.       
D/DynamitePackage(26318): Instantiating com.google.android.gms.ads.ChimeraMobileAdsSettingManagerCreatorImpl
D/NetworkSecurityConfig(26318): No Network Security Config specified, using platform default
I/Ads     (26318): Updating ad debug logging enablement.                
E/Ads     (26318): Fail to get isAdIdFakeForDebugLogging                
E/Ads     (26318): java.io.IOException: Connection failure              
E/Ads     (26318):      at com.google.android.gms.ads.identifier.a.a(:com.google.android.gms.policy_ads_fdr_dynamite@20290000@20290000.249178941.249178941:24)
E/Ads     (26318):      at com.google.android.gms.ads.identifier.a.a(:com.google.android.gms.policy_ads_fdr_dynamite@20290000@20290000.249178941.249178941:64)
E/Ads     (26318):      at com.google.android.gms.ads.identifier.a.b(:com.google.android.gms.policy_ads_fdr_dynamite@20290000@20290000.249178941.249178941:3)
E/Ads     (26318):      at com.google.android.gms.ads.internal.util.d.e_(:com.google.android.gms.policy_ads_fdr_dynamite@20290000@20290000.249178941.249178941:1)
E/Ads     (26318):      at com.google.android.gms.ads.internal.util.b.run(:com.google.android.gms.policy_ads_fdr_dynamite@20290000@20290000.249178941.249178941:3)
E/Ads     (26318):      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
E/Ads     (26318):      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/Ads     (26318):      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/Ads     (26318):      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/Ads     (26318):      at java.lang.Thread.run(Thread.java:764)        
W/Ads     (26318): Update ad debug logging enablement as false          
I/WebViewFactory(26318): Loading com.google.android.webview version 75.0.3770.89 (code 377008935)
I/cr_LibraryLoader(26318): Time to load native libraries: 14 ms (timestamps 6621-6635)
I/chromium(26318): [INFO:library_loader_hooks.cc(50)] Chromium logging enabled: level = 0, default verbosity = 0
I/cr_LibraryLoader(26318): Expected native library version number "75.0.3770.89", actual native library version number "75.0.3770.89"
W/cr_ChildProcLH(26318): Create a new ChildConnectionAllocator with package name = com.google.android.webview, sandboxed = true
W/ola.coding_lis(26318): Accessing hidden method Landroid/content/Context;->bindServiceAsUser(Landroid/content/Intent;Landroid/content/ServiceConnection;ILandroid/os/Handler;Landroid/os/UserHandle;)Z (light greylist, reflection)
I/cr_BrowserStartup(26318): Initializing chromium process, singleProcess=false
W/ola.coding_lis(26318): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker;-><init>(Landroid/content/Context;I)V (light greylist, reflection)
W/ola.coding_lis(26318): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker;->logEvent(Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;)V (light greylist, reflection)
W/ola.coding_lis(26318): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionStarted(I)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
W/ola.coding_lis(26318): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionModified(II)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
W/ola.coding_lis(26318): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionModified(IILandroid/view/textclassifier/TextClassification;)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
W/ola.coding_lis(26318): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionModified(IILandroid/view/textclassifier/TextSelection;)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
W/ola.coding_lis(26318): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionAction(III)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
W/ola.coding_lis(26318): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionAction(IIILandroid/view/textclassifier/TextClassification;)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
W/cr_media(26318): Requires BLUETOOTH permission                        
W/VideoCapabilities(26318): Unrecognized profile 4 for video/hevc       
W/VideoCapabilities(26318): Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities(26318): Unrecognized profile/level 0/3 for video/mpeg2
I/VideoCapabilities(26318): Unsupported profile 4 for video/mp4v-es     
W/Utils   (26318): could not parse long range '175-174'                 
Syncing files to device Redmi Note 4...                          1,974ms

🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on Redmi Note 4 is available at:
http://127.0.0.1:34365/NSgfi9A3TX8=/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
W/ola.coding_lis(26318): Accessing hidden field Lsun/misc/Unsafe;->theUnsafe:Lsun/misc/Unsafe; (light greylist, reflection)
I/Gralloc2(26318): Adding additional valid usage bits: 0x202000
D/DynamitePackage(26318): Instantiating com.google.android.gms.ads.ChimeraAdManagerCreatorImpl
I/Ads     (26318): Use AdRequest.Builder.addTestDevice("36CA1B98A5A4C0B004BB36EB34950361") to get test ads on this device.
I/ola.coding_lis(26318): The ClassLoaderContext is a special shared library.
I/DynamiteModule(26318): Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:20290
I/DynamiteModule(26318): Selected remote version of com.google.android.gms.ads.dynamite, version >= 20290
I/ViewRootImpl(26318): CPU Rendering VSync enable = true
D/DynamitePackage(26318): Instantiating com.google.android.gms.ads.ChimeraAdManagerCreatorImpl
I/Ads     (26318): Use AdRequest.Builder.addTestDevice("36CA1B98A5A4C0B004BB36EB34950361") to get test ads on this device.
I/ViewRootImpl(26318): CPU Rendering VSync enable = true
E/FA      (26318): GoogleService failed to initialize, status: 10, Missing google app id value from from string resources with name google_app_id.
W/ola.coding_lis(26318): Accessing hidden field Ljava/nio/Buffer;->address:J (light greylist, reflection)
I/FA      (26318): App measurement is starting up, version: 13001
I/FA      (26318): To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
I/FA      (26318): To enable faster debug mode event logging run:
I/FA      (26318):   adb shell setprop debug.firebase.analytics.app io.github.vikasgola.coding_list
E/FA      (26318): Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
E/FA      (26318): Uploading is not possible. App measurement disabled
W/Ads     (26318): Not retrying to fetch app settings
I/FA      (26318): Tag Manager is not found and thus will not be used
I/Ads     (26318): Ad failed to load : 3
I/flutter (26318): Admob banner failed to load. Error code: 3
I/Ads     (26318): Ad failed to load : 3
I/flutter (26318): Admob banner failed to load. Error code: 3
Application finished.

```

**Comment by soncco** [comment]
@vikasgola any solution for this?
