### ISSUE TITLE
This library fails on android 8.0

### ISSUE THREAD

**Issue by markg85** [MaikuB/flutter_local_notifications#339]
Hi,

I'm sadly stuck on a Galaxy S7 (aka, android 8.0).
If i'm running the pure example applications it even crashes.
```
E/flutter ( 6848): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(INVALID_ICON, The resource app_icon could not be found. Please make sure it has been added as a drawable resource to your Android head project., null)
E/flutter ( 6848): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter ( 6848): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
E/flutter ( 6848): <asynchronous suspension>
E/flutter ( 6848): #2      FlutterLocalNotificationsPlugin.initialize (package:flutter_local_notifications/src/flutter_local_notifications.dart:103:24)
E/flutter ( 6848): <asynchronous suspension>
E/flutter ( 6848): #3      _HomePageState.initState (package:fluttest/main.dart:62:37)
E/flutter ( 6848): #4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4068:58)
E/flutter ( 6848): #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter ( 6848): #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 6848): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 6848): #8      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter ( 6848): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 6848): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 6848): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter ( 6848): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter ( 6848): #13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
E/flutter ( 6848): #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter ( 6848): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 6848): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 6848): #17     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter ( 6848): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 6848): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 6848): #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter ( 6848): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 6848): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 6848): #23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter ( 6848): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 6848): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 6848): #26     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter ( 6848): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 6848): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 6848): #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter ( 6848): #30     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter ( 6848): #31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
E/flutter ( 6848): #32     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
E/flutter ( 6848): #33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter ( 6848): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 6848): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 6848): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter ( 6848): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter ( 6848): #38     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
E/flutter ( 6848): #39     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter ( 6848): #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 6848): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 6848): #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter ( 6848): #43     Element.rebuild (package
```
I did try a tutorial (and did set the appropriate icon! as this log shows an INVALID_ICON error). And in that app it also crashes where it starts in the function: FlutterLocalNotificationsPlugin::show, it eventually ends up in a core flutter function (message_codecs.dart) and crashes here:
```
  @override
  dynamic decodeEnvelope(ByteData envelope) {
    // First byte is zero in success case, and non-zero otherwise.
    if (envelope.lengthInBytes == 0)
      throw const FormatException('Expected envelope, got nothing');
    final ReadBuffer buffer = ReadBuffer(envelope);
    if (buffer.getUint8() == 0)
      return messageCodec.readValue(buffer);
    final dynamic errorCode = messageCodec.readValue(buffer);
    final dynamic errorMessage = messageCodec.readValue(buffer);
    final dynamic errorDetails = messageCodec.readValue(buffer);
    if (errorCode is String && (errorMessage == null || errorMessage is String) && !buffer.hasRemaining)
---->      throw PlatformException(code: errorCode, message: errorMessage, details: errorDetails);
    else
      throw const FormatException('Invalid envelope');
  }
```

see the "---->".

Is there anything i can provide to ease debugging here?
Android development is really new to me, just so you know :) That means you should probably be quite verbose if you want me to get a log of something.

Cheers,
Mark

**Comment by MaikuB** [comment]
The logs would indicate who haven't actually created the icon on the Android side. How to do that is something you'll need to look at Android docs/tutorials. Regarding the example failing, I'm guessing you just copied the Dart code and tried to run it. Is that right? If so, note that there are notes that just doing this won't work

**Comment by markg85** [comment]
Ha :)

I did follow the readme and did have the code to show it. I just had it commented.
Simply uncommenting it made it work. Awesome! :D I guess i just didn't see that when writing this bug report.

Sorry for the noise!
