### ISSUE TITLE
Unable to start receiver com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver

### ISSUE THREAD

**Issue by JCKodel** [MaikuB/flutter_local_notifications#408]
**Describe the bug**
This is a Crashlytics report, can't pinpoint exactly what's going on.
I have >140k active users and this error affected 11 users.

```
Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3623)
       at android.app.ActivityThread.access$1300(ActivityThread.java:240)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7097)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.setupNotificationChannel(FlutterLocalNotificationsPlugin.java:584)
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(FlutterLocalNotificationsPlugin.java:115)
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(FlutterLocalNotificationsPlugin.java:634)
       at com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver.onReceive(ScheduledNotificationReceiver.java:45)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3614)
       at android.app.ActivityThread.access$1300(ActivityThread.java:240)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7097)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```

**Comment by MaikuB** [comment]
Would need more info on what your app is doing, which version of the plugin you're using etc. The code is open-source so you can check what your app is doing to see how it relates to the crash given you have a stack trace

**Comment by MaikuB** [comment]
Also note that you can have your app point to a local copy of the plugin or via a Git reference. This could be used to track the problem and submit a PR back should you find out what the issue is

**Comment by JCKodel** [comment]
The problem is that this don't happen in any of my devices (of course, "works on my machine" ®)
I would love to help, but I don't have any idea of what can trigger this behavior.

Anyway, `flutter_local_notifications: ^0.9.1`

**Comment by MaikuB** [comment]
Would the users that have those crashes have a version of your app that is using version 0.9.1 of the plugin?  Line 584 of the `FlutterLocalNotificationsPlugin.java` file currently doesn't point to code that would deal with an integer so I suspect it's on an older version of the plugin. Regardless, without more information, this may not be something I'll be able to track down to fix. Be good if you can provide more info about what kind of code you have has well when it comes to notifications. Snippets would help.

**Comment by yeskayviswa** [comment]
This is a Crashlytics report, can't pinpoint exactly what's going on.

 ```
java.lang.RuntimeException: Unable to start receiver com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
E/AndroidRuntime( 5911): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3388)
E/AndroidRuntime( 5911): 	at android.app.ActivityThread.access$1200(ActivityThread.java:199)
E/AndroidRuntime( 5911): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
E/AndroidRuntime( 5911): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 5911): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime( 5911): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/AndroidRuntime( 5911): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5911): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime( 5911): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
```Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
E/AndroidRuntime( 5911): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.setSmallIcon(FlutterLocalNotificationsPlugin.java:188)
E/AndroidRuntime( 5911): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(FlutterLocalNotificationsPlugin.java:146)
E/AndroidRuntime( 5911): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(FlutterLocalNotificationsPlugin.java:688)
E/AndroidRuntime( 5911): 	at com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver.onReceive(ScheduledNotificationReceiver.java:45)
E/AndroidRuntime( 5911): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3379)
```

After this when the schedule time is arrived, the apps gets stopped. 

```Future<void> scheduleNotification(DateTime _combinedDateTime) async {
    var androidPlatformChannelSpecifics = AndroidNotificationDetails(
      'scheduler channel id',
      'scheduler channel name',
      'scheduler description',
      importance: Importance.Max,
      ledColor: Color(0xFF3EB16F),
      ledOffMs: 1000,
      ledOnMs: 1000,
      enableLights: true,
    );

    var iOSPlatformChannelSpecifics = IOSNotificationDetails();

    var platformChannelSpecifics = NotificationDetails(
        androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);

    int inttaskid = int.parse(taskId);
    await flutterLocalNotificationsPlugin.schedule(
        inttaskid,
        taskName,
        "Its ${CommonUtils().timeDisplay(_combinedDateTime)} and you have some tasks pending!",
        _combinedDateTime,
        platformChannelSpecifics,
        androidAllowWhileIdle: true);
  }```

This is my code. I'm using _*flutter_local_notifications: ^1.4.4+4*_ 

Can you please help me , we need to resolve this ASAP. KIndly help us @MaikuB @JCKodel

**Comment by yourshinsuke** [comment]
Did you fix?

**Comment by yeskayviswa** [comment]
Yes. The integer value I've provided in dart, exceeded the limit of maximum integer value in java file. So i reduced the number within the limit of integer max value and then the issue was resolved. 

Try to reduce the id value.

**Comment by yourshinsuke** [comment]
I just add the code in `initStatus`, and error didn't show. but I don't know what it is.

```
    var initializationSettingsAndroid =
        AndroidInitializationSettings('@mipmap/ic_launcher');
    var initializationSettingsIOS = IOSInitializationSettings();
    var initializationSettings = InitializationSettings(
        initializationSettingsAndroid, initializationSettingsIOS);
    flutterLocalNotificationsPlugin.initialize(
      initializationSettings,
    );
```

**Comment by yourshinsuke** [comment]
@yeskayviswa Thank you for replying.

> Try to reduce the id value.

I pushed `channel_id`, `ZONE_ALERT` via Cloud Messaging in Firebase.
what is `id` ? it should number?

**Comment by yeskayviswa** [comment]
The error I faced is in flutterLocalNotificationsPlugin.schedule( ) function. My inttaskid was more than the limit. 

That's the id I've mentioned

**Comment by mercatelli** [comment]
> Yes. The integer value I've provided in dart, exceeded the limit of maximum integer value in java file. So i reduced the number within the limit of integer max value and then the issue was resolved.
> 
> Try to reduce the id value.

Sorry I'm a little noob. I'm with the same problem and using five tipes of notification (every minute, hourly, every day, every week and specific Time) I put the IDs 01, 02, 03, 04 and 05. Qhat I can do to solve this?

**Comment by dikshantrawal** [comment]
I am having an error in the android app when I have updated the flutter version and library version 9.3.2 and even9.2.0. I am getting the below error.

Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver: java.lang.RuntimeException: Missing type parameter.
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4757)
       at android.app.ActivityThread.access$1800(ActivityThread.java:309)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2279)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8582)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:563)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)

Please help on this

**Comment by dikshantrawal** [comment]
This is the crashlytics report when I have updated the version. And the application is crashing only in release mode.
Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver: java.lang.RuntimeException: Missing type parameter.
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3858)
       at android.app.ActivityThread.access$1500(ActivityThread.java:227)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1901)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:224)
       at android.app.ActivityThread.main(ActivityThread.java:7592)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by MaikuB** [comment]
Make sure you've done the release build configuration

**Comment by under3415** [comment]
I am able to replicate this on my physical test device. Getting below error in `crashlytics`.
NB: This is only happening since upgrading to Gradle 8.4 and AGP 8.1.2. Not happening on gradle version 7.

```
Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver: java.lang.RuntimeException: Missing type parameter.
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4471)
       at android.app.ActivityThread.access$1700(ActivityThread.java:262)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2166)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loopOnce(Looper.java:238)
       at android.os.Looper.loop(Looper.java:357)
       at android.app.ActivityThread.main(ActivityThread.java:8111)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
```

**Comment by under3415** [comment]
Seems that this is related to ProGuard and R8. As I was making changes to upgrade to AGP8, I have added this to `gradle/properties` file:

```
android.enableR8.fullMode=true
```

Removing this line seems to fix the issue.

**Comment by gibbsvjy007** [comment]
@MaikuB 

We are getting the same error suddenly, we did not change any code since many versions regarding scheduling local notification. Since last two version after upgrading the plugin to 16.0.0 we are getting the crash event for many users in firebase crashlytics. Any idea how to solve this error ? this is very important error as it has decreased our crash free users to almost 50%. Let me know if you have any idea on this.

Fatal Exception: java.lang.RuntimeException
Unable to start receiver com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver: java.lang.RuntimeException: Missing type parameter.

<img width="1314" alt="image" src="https://github.com/MaikuB/flutter_local_notifications/assets/6039305/a6bc5a97-0147-455e-900f-ecd9242b292a">

**Comment by markosole** [comment]
Just looking at the setup of `proguard-rules.pro` and example file is missing. 

https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/example/android/app/proguard-rules.pro

The file is still required for Release build, right?

**Comment by koji-1009** [comment]
@MaikuB 
I see, it is indeed a necessary document and file for the current stable (v18)! Now I will try to create a follow up PR. Please wait a moment...
