### ISSUE TITLE
PlatformException when shceduling notifications

### ISSUE THREAD

**Issue by jesusrp98** [MaikuB/flutter_local_notifications#418]
Scheduling notifications when the app is uploaded on the Play Store doesn't work: crashes the app.
However, when I try the app on debug or release mode, works perfectly fine. Strange isn't it?

This is the code I use to schedule nots:
```
  Future _scheduleNotification({
    BuildContext context,
    int id,
    String time,
    Duration subtract,
  }) async {
    await Provider.of<AppModel>(context, listen: false).notifications.schedule(
          id,
          FlutterI18n.translate(context, 'spacex.notifications.launches.title'),
          FlutterI18n.translate(
            context,
            'spacex.notifications.launches.body',
            {
              'rocket': launch.rocket.name,
              'payload': launch.rocket.secondStage.getPayload(0).id,
              'orbit': launch.rocket.secondStage.getPayload(0).orbit,
              'time': time,
            },
          ),
          launch.launchDate.subtract(subtract),
          NotificationDetails(
            AndroidNotificationDetails(
              'channel.launches',
              FlutterI18n.translate(
                context,
                'spacex.notifications.channel.launches.title',
              ),
              FlutterI18n.translate(
                context,
                'spacex.notifications.channel.launches.description',
              ),
              importance: Importance.High,
              color: Theme.of(context).primaryColor,
            ),
            IOSNotificationDetails(),
          ),
          androidAllowWhileIdle: true,
        );
  }
```

Here's the error output
```
E/flutter (22386): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, java.lang.NoSuchMethodException: com.dexterous.flutterlocalnotifications.a.values [], null)
E/flutter (22386): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569)
E/flutter (22386): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321)
E/flutter (22386): <asynchronous suspension>                            
E/flutter (22386): #2      FlutterLocalNotificationsPlugin.schedule (package:flutter_local_notifications/src/flutter_local_notifications.dart:152)
E/flutter (22386): #3      HomeModel._scheduleNotification (package:cherry/data/models/home.dart:102)
E/flutter (22386): #4      HomeModel.initNotifications (package:cherry/data/models/home.dart:53)
E/flutter (22386): <asynchronous suspension>                            
E/flutter (22386): #5      HomeModel.loadData (package:cherry/data/models/home.dart:24)
E/flutter (22386): <asynchronous suspension>                            
E/flutter (22386): #6      new QueryModel (package:cherry/data/classes/abstract/query_model.dart:20)
E/flutter (22386): #7      new HomeModel (package:cherry/data/models/home.dart:15)
E/flutter (22386): #8      _StartScreenState.build.<anonymous closure> (package:cherry/ui/screens/start.dart:115)
E/flutter (22386): #9      _CreateInheritedProviderState.value (package:provider/src/inherited_provider.dart:392)
E/flutter (22386): #10     _InheritedProviderScopeMixin.value (package:provider/src/inherited_provider.dart:279)
E/flutter (22386): #11     Provider.of (package:provider/src/provider.dart:251)
E/flutter (22386): #12     Consumer.buildWithChild (package:provider/src/consumer.dart:179)
E/flutter (22386): #13     SingleChildStatelessWidget.build (package:nested/nested.dart:238)
E/flutter (22386): #14     StatelessElement.build (package:flutter/src/widgets/framework.dart:4291)
E/flutter (22386): #15     SingleChildStatelessElement.build (package:nested/nested.dart:280)
E/flutter (22386): #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223)
E/flutter (22386): #17     Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
E/flutter (22386): #18     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206)
E/flutter (22386): #19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
E/flutter (22386): #20     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:223)
E/flutter (22386): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
E/flutter (22386): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
E/flutter (22386): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243)
E/flutter (22386): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
E/flutter (22386): #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206)
E/flutter (22386): #26     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381)
E/flutter (22386): #27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
E/flutter (22386): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
E/flutter (22386): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
E/flutter (22386): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243)
E/flutter (22386): #31     _InheritedProviderScopeMixin.performRebuild (package:provider/src/inherited_provider.dart:220)
E/flutter (22386): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
E/flutter (22386): #33     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206)
E/flutter (22386): #34     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
E/flutter (22386): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
E/flutter (22386): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
E/flutter (22386): #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243)
E/flutter (22386): #38     Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
E/flutter (22386): #39     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206)
E/flutter (22386): #40     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
E/flutter (22386): #41     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:223)
E/flutter (22386): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
E/flutter (22386): #43     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5551)
E/flutter (22386): #44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
E/flutter (22386): #45     Element.updateChild (package:flutter/src/widgets
```

**Comment by MaikuB** [comment]
Have you setup the Proguard rules file?

**Comment by jesusrp98** [comment]
I don't have any ProGuard file inside my Flutter project, and never had.
Is this because I updated to the latest version of Flutter?

Also, is [this](https://stackoverflow.com/a/59202013) the way to implement it?

**Comment by MaikuB** [comment]
I believe the Flutter docs had always talked about configuring ProGuard (see [here](https://flutter.dev/docs/deployment/android#enabling-proguard)). There were mention of the rules required for the plugin in the readme for quite a long time too though I had recently updated it to make sure it include some info on making sure resources related to icons aren't removed and GSON-related rules (GSON is a library used for serialising/deserialising notification info as JSON on the Android side). To summarise, check the Flutter docs and the info I have put in the readme

**Comment by jesusrp98** [comment]
Thanks! I think that solved my issue. But I still don't know why before Flutter 1.12 the plugin worked flawlessly in production without the ProGuard file, and know it crashes without it.
I'm really puzzled :/

**Comment by MaikuB** [comment]
Perhaps when you updated, you may have enabled Proguard/R8 without realising. It would've been a configuration on the Android side of the app, not Flutter so could be why you missed that but that's just a guess. Going to close this

**Comment by jamie1192** [comment]
Sorry for pinging an old thread, but I think the answer to your question @jesusrp98 is that [it's enabled by default when using Gradle >= 3.4.0](https://developer.android.com/studio/build/shrink-code#enable), and if I remember correctly Flutter upped the default gradle version from 3.3.x for new projects.

Just had the same issues myself.
