### ISSUE TITLE
Unable to run flutter_local_notifications plugin from background

### ISSUE THREAD

**Issue by hb0nes** [MaikuB/flutter_local_notifications#430]
We are trying to use this awesome plugin in combination with FCM, so that we can send a data notification through Firebase and subsequently create a notification based on it with this plugin.
We have setup top-level defined instance of a class containing an instance of FlutterLocalNotificationPlugin and try to use this instance to show() a plugin:

```dart
// Top-Level function that runs in background isolate. Handles incoming FCM data notifications when app is either in background or terminated.
Future<dynamic> backgroundMessageHandler(Map<String, dynamic> message) async {
  if(message.containsKey('data')) {
    await _showNotification(message);
    return Future<void>.value();
  }
}

// Function to build custom local notification based on data payload received from FCM.
Future _showNotification(message) async {
  var name = message['data']['sender'];
  Iterable<Contact> itContacts = await ContactsService.getContactsForPhone(message['data']['sender']);
    if(itContacts.isNotEmpty){
    itContacts.forEach((c) {
      name = c.displayName;
    });
  }
  var rdm = new Random();
  var androidPlatformChannelSpecifics = AndroidNotificationDetails(
      'channel id', 'channel name', 'channel description',
      importance: Importance.Max, priority: Priority.High,
      enableLights: true);
  var iOSPlatformChannelSpecifics = new IOSNotificationDetails();
  var platformChannelSpecifics = new NotificationDetails(
      androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);
  await notificationHandler.flutterLocalNotificationsPlugin.show(
    rdm.nextInt(64),
    name,
    message['data']['body'],
    platformChannelSpecifics,
    payload: message['data']['screen'],
  );
}
```

```dart
// Class notification handling
class NotificationHandler {
  final FirebaseMessaging fcm = FirebaseMessaging();
  StreamSubscription iosSubscription;
  String deviceToken = "";
  FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin = FlutterLocalNotificationsPlugin();

  // Ensure only one class instance lives at a time
  static final NotificationHandler _singleton =
  new NotificationHandler._internal();

  factory NotificationHandler() {
    return _singleton;
  }
  NotificationHandler._internal();

  // Initialization of local notification and FCM settings
  Future<void> initialize([BuildContext context]) async {
    var initializationSettingsAndroid =
    new AndroidInitializationSettings('@mipmap/ic_launcher');
    var initializationSettingsIOS = new IOSInitializationSettings(onDidReceiveLocalNotification: onDidReceiveLocalNotification);
    var initializationSettings = new InitializationSettings(initializationSettingsAndroid, initializationSettingsIOS);
    flutterLocalNotificationsPlugin.initialize(initializationSettings, onSelectNotification: onClickNotification);

    // Configure Firebase Cloud Messaging
    fcm.configure(
      // Only used for IOS since data and notification payloads are concatenated. IOS calls onMessage in each state.
      onMessage: (Map<String, dynamic> message) async {
        if(message.containsKey('data') && Platform.isIOS) {
          _showNotification(message);
        }
      },
      // onBackgroundMessage handler is used for android. Top-Level function backgroundMessageHandler runs in a background isolate
      onBackgroundMessage: Platform.isIOS
          ? null
          : backgroundMessageHandler,
    );
    // Null check to prevent error when updateDeviceToken() would be executed in the isolate
    if(loggedInUser != null){
      updateDeviceToken();
    }
  }
...
```

The error is as follows:
```
I/flutter (20856): Unable to handle incoming background message.
I/flutter (20856): MissingPluginException(No implementation found for method show on channel dexterous.com/flutter/local_notifications)
```

What are we doing wrong?

**Comment by MaikuB** [comment]
What happens if you try to use the plugin on the main isolate?

**Comment by hb0nes** [comment]
Then it works just fine.

**Comment by MaikuB** [comment]
I have a suspicion that the background message handler is relying on headless execution given the restrictions to use a top-level or static function. In general, extra steps are needed to execute code to makes use of plugins. Off memory some of those steps include a custom Android application class. The android_alarm_manager plugin makes use of this mechanism but documents what's needed. Could be that the FCM plugin needs similar documentation.

You could quickly try have the code call methods within another plugin since if you run into the same problem to confirm. I reckon you'll run into the same problem and can refer to the documentation in android_alarm_manager plugin on how to solve the issue

**Comment by MaikuB** [comment]
Also note that based on my understanding and experience with running code in scenarios where it makes use of headless execution, the code runs in a completely separate context. So things like creating an instance of a plugin (as a local variable) etc needed to be done in the function.

**Comment by hb0nes** [comment]
> Also note that based on my understanding and experience with running code in scenarios where it makes use of headless execution, the code runs in a completely separate context. So things like creating an instance of a plugin (as a local variable) etc needed to be done in the function.

Yes, it definitely runs in a seperate isolate. However, when things are definied as static, it seems they are accessible in this isolated context. For example, it knows the instance of flutterLocalNotificationPlugin, but it doesn't know its methods. 

I will check the alarm manager plugin docs later to see if I can find what you are referring to.
It does seem odd that not many people try to use your plugin from a background context.

I did find an issue of someone referring to the same behaviour when he tried to use location based background logic to notify using this plugin. 
https://github.com/MaikuB/flutter_local_notifications/issues/238

So I'm not completely alone ^^.

**Comment by MaikuB** [comment]
> Yes, it definitely runs in a seperate isolate. However, when things are defined as static, it seems they are accessible in this isolated context. For example, it knows the instance of flutterLocalNotificationPlugin, but it doesn't know its methods.

But have you tried changing it to be like my previous response where the plugin is a local variable created within the static method? When I tried this in the past, it may look like a global variable (an instance of the plugin in this case) can be used but it would fall over because the method runs in complete isolation despite how it may seem

**Comment by hb0nes** [comment]
It was one of the things I tried early on, just putting the entire plugin logic (initialize inside the static backgroundHandler method. I just tried it again:

```dart
// Top-Level function that runs in background isolate. Handles incoming FCM data notifications when app is either in background or terminated.
Future<dynamic> backgroundMessageHandler(Map<String, dynamic> message) async {
  print("background message handler reached");
  // Called whenever a notification is received. Could later be used for back-up notifications and such.
  Future<void> onDidReceiveLocalNotification(int id, String title, String body, String payload) async {}

  // Called when clicked on a notification. Note that this function may run in the background isolate.
  // The isolateToMainStream (receive) port run in the main app and listens for events from the isolate.
  Future<void> onClickNotification(String payload) async {
    if (payload != null) {
      isolateToMainStream.sendPort.send(payload);
//      await flutterLocalNotificationsPlugin.cancelAll();
    }
  }

  // FLN Plugin logic
  FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin = FlutterLocalNotificationsPlugin();
  flutterLocalNotificationsPlugin = FlutterLocalNotificationsPlugin();
  var initializationSettingsAndroid = new AndroidInitializationSettings('@mipmap/ic_launcher');
  var initializationSettingsIOS =
      new IOSInitializationSettings(onDidReceiveLocalNotification: onDidReceiveLocalNotification);
  var initializationSettings = new InitializationSettings(initializationSettingsAndroid, initializationSettingsIOS);
  flutterLocalNotificationsPlugin.initialize(initializationSettings, onSelectNotification: onClickNotification);
  var androidPlatformChannelSpecifics = new AndroidNotificationDetails(
      'channel id', 'channel name', 'channel description',
      importance: Importance.Max, priority: Priority.High, enableLights: true);
  var iOSPlatformChannelSpecifics = new IOSNotificationDetails();
  var platformChannelSpecifics = new NotificationDetails(androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);

  if (message.containsKey('data')) {
    var name = message['data']['sender'];
    Iterable<Contact> itContacts = await ContactsService.getContactsForPhone(message['data']['sender']);
    if (itContacts.isNotEmpty) {
      itContacts.forEach((c) {
        name = c.displayName;
      });
    }
    var rdm = Random();
    await flutterLocalNotificationsPlugin.show(
      rdm.nextInt(64),
      name,
      message['data']['body'],
      platformChannelSpecifics,
      payload: message['data']['screen'],
    );

    return Future<void>.value();
  }
}
```

Results in below output
```
I/flutter ( 6416): background message handler reachd
E/flutter ( 6416): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method initialize on channel dexterous.com/flutter/local_notifications)
E/flutter ( 6416): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
E/flutter ( 6416): <asynchronous suspension>
E/flutter ( 6416): #1      FlutterLocalNotificationsPlugin.initialize (package:flutter_local_notifications/src/flutter_local_notifications.dart:103:24)
E/flutter ( 6416): #2      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:46:6)
E/flutter ( 6416): #3      FlutterLocalNotificationsPlugin.initialize (package:flutter_local_notifications/src/flutter_local_notifications.dart:87:26)
E/flutter ( 6416): #4      backgroundMessageHandler (package:messenger/firestore/notification_handler.dart:33:35)
E/flutter ( 6416): #5      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:46:6)
E/flutter ( 6416): #6      backgroundMessageHandler (package:messenger/firestore/notification_handler.dart:12:41)
E/flutter ( 6416): #7      _fcmSetupBackgroundChannel.<anonymous closure> (package:firebase_messaging/firebase_messaging.dart:38:30)
E/flutter ( 6416): #8      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:46:6)
E/flutter ( 6416): #9      _fcmSetupBackgroundChannel.<anonymous closure> (package:firebase_messaging/firebase_messaging.dart:31:42)
E/flutter ( 6416): #10     MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:402:55)
E/flutter ( 6416): #11     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:46:6)
E/flutter ( 6416): #12     MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:399:39)
E/flutter ( 6416): #13     MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:370:54)
E/flutter ( 6416): #14     _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:200:33)
E/flutter ( 6416): #15     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:46:6)
E/flutter ( 6416): #16     _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:191:37)
E/flutter ( 6416): #17     _invoke3.<anonymous closure> (dart:ui/hooks.dart:303:15)
E/flutter ( 6416): #18     _rootRun (dart:async/zone.dart:1126:13)
E/flutter ( 6416): #19     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter ( 6416): #20     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
E/flutter ( 6416): #21     _invoke3 (dart:ui/hooks.dart:302:10)
E/flutter ( 6416): #22     _dispatchPlatformMessage (dart:ui/hooks.dart:162:5)
E/flutter ( 6416): 
I/flutter ( 6416): Unable to handle incoming background message.
```

Also, I now realize this is not an issue with your plugin at all.
Thanks a lot for the quick and clear responses and we will try to work it out further.
You the best.

**Comment by furiousdazzewizard** [comment]
> Then it works just fine.
> 
> Actually - one of my teammates registered your plugin, just like we register Firebase plugins. That made it work.
> 
> However, I can't help but think this is not the way to go. I also cannot find any information related to using stuff in the background, so it must be something that everybody knows how to do, but us.
> 
> Is this not a very normal use case?

@hb0nes .. can you please explain/detail how you made it work by registering the local_notifications plugin "just like we register Firegase plugins"?.. we are also trying to use both firebase_messaging and local_notifications plugins but we are having problems to make local_notifications work for onBackground message received from firebase. Thanks

**Comment by hb0nes** [comment]
Sorry man don't have a lot of time for this as this project is over, but
these docs should guide your steps:
https://pub.dev/packages/android_alarm_manager


Op wo 26 feb. 2020 om 18:25 schreef furiousdazzewizard <
notifications@github.com>:
