### ISSUE TITLE
NullPointerException related to notification details id

### ISSUE THREAD

**Issue by talmor-guy** [MaikuB/flutter_local_notifications#446]
We are developing a flutter app that uses local notifications and while everything works fine for us here we can see many crashes on crashlytics that are caused by the same reason - it seems like the notification details id is null. I have seen this issue being reported here in the past and it was closed, i assume it was so due to inability to reproduce however this issue is probably still there and requires attention. If this is not solvable I think at least the plugin should check for null values and not crash.

Here are some stack samples, plugin version 0.9.1+3

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Integer.equals(java.lang.Object)' on a null object reference
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.removeNotificationFromCache(FlutterLocalNotificationsPlugin.java:213)
       at com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver.onReceive(ScheduledNotificationReceiver.java:49)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3788)

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(FlutterLocalNotificationsPlugin.java:119)
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(FlutterLocalNotificationsPlugin.java:634)
       at com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver.onReceive(ScheduledNotificationReceiver.java:45)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3106)
     

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.setupNotificationChannel(FlutterLocalNotificationsPlugin.java:584)
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(FlutterLocalNotificationsPlugin.java:115)
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(FlutterLocalNotificationsPlugin.java:634)
       at com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver.onReceive(ScheduledNotificationReceiver.java:45)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3788)

**Comment by talmor-guy** [comment]
The plugin allows scheduling of notifications without id, it should return an error.

**Comment by MaikuB** [comment]
> If this is not solvable I think at least the plugin should check for null values and not crash.

Masking the exceptions means it'll be even harder to find out issues and trace them down

> The plugin allows scheduling of notifications without id, it should return an error.

You're welcome to submit a pull request to help out

**Comment by talmor-guy** [comment]
created a pull request

**Comment by MaikuB** [comment]
Closed by #447 and #453
