### ISSUE TITLE
"java.lang.AssertionError: java.lang.NoSuchFieldException: Drawable " error only with create bundle

### ISSUE THREAD

**Issue by hkndzdr** [MaikuB/flutter_local_notifications#457]
I am sending schedule notifications in my application. Works seamlessly with the emulator in debug mode in emulator. Also works when connected to real device via usb cable in android studio. But when i create the bundle and upload it to the play store it throws me this error.

```
E/flutter (31837): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.AssertionError: java.lang.NoSuchFieldException: Drawable
E/flutter (31837): 	at c.b.d.y.n.n$j0.<init>(Unknown Source:87)
E/flutter (31837): 	at c.b.d.y.n.n$w.a(Unknown Source:29)
E/flutter (31837): 	at c.b.d.f.a(Unknown Source:74)
E/flutter (31837): 	at c.b.d.y.n.i.a(Unknown Source:42)
E/flutter (31837): 	at c.b.d.y.n.i.a(Unknown Source:123)
E/flutter (31837): 	at c.b.d.y.n.i.a(Unknown Source:22)
E/flutter (31837): 	at c.b.d.f.a(Unknown Source:74)
E/flutter (31837): 	at c.b.d.f.a(Unknown Source:4)
E/flutter (31837): 	at c.b.d.f.a(Unknown Source:8)
E/flutter (31837): 	at c.b.d.f.a(Unknown Source:5)
E/flutter (31837): 	at c.b.d.f.a(Unknown Source:13)
E/flutter (31837): 	at com.dexterous.flutterlocalnotifications.b.b(Unknown Source:4)
E/flutter (31837): 	at com.dexterous.flutterlocalnotifications.b.e(Unknown Source:23)
E/flutter (31837): 	at com.dexterous.flutterlocalnotifications.b.a(Unknown Source:137)
E/flutter (31837): 	at d.a.c.a.k$a.a(Unknown Source:17)
E/flutter (31837): 	at io.flutter.embedding.engine.b.b.a(Unknown Source:57)
E/flutter (31837): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
E/flutter (31837): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (31837): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/flutter (31837): 	at android.os.Looper.loop(Looper.java:148)
E/flutter (31837): 	at android.app.ActivityThread.main(ActivityThread.java:6698)
E/flutter (31837): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (31837): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
E/flutter (31837): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
E/flutter (31837): Caused by: java.lang.NoSuchFieldException: Drawable
E/flutter (31837): 	at java.lang.Class.getField(Class.java:1601)
E/flutter (31837): 	at c.b.d.y.n.n$j0.<init>(Unknown Source:34)
E/flutter (31837): 	... 23 more
E/flutter (31837): 
F/flutter (31837): [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(76)] Check failed: CheckException(env). 
```

**Comment by MaikuB** [comment]
Have you done the steps mentioned in the last few paragraphs of the Android integration guide?

**Comment by hkndzdr** [comment]
Sorry, I overlooked that paragraph. I implemented "-keep class com.dexterous.** { *; }." Thanks

**Comment by MaikuB** [comment]
No worries. I would suggest you include the gson rules as well. In fact, you should be about to copy the rules from the example app to your app as well

**Comment by shadyshrif** [comment]
I had the same issue and I has been resolved after I copied proguard rules from the example app to my app. 

I think a link of this file has to in the read me with gradle sample code

```
buildTypes {
        release {
            // Enables code shrinking, obfuscation, and optimization for only
            // your project's release build type.
            minifyEnabled true

            // Enables resource shrinking, which is performed by the
            // Android Gradle plugin.
            shrinkResources true

            // Includes the default ProGuard rules files that are packaged with
            // the Android Gradle plugin. To learn more, go to the section about
            // R8 configuration files.
            proguardFiles getDefaultProguardFile(
                    'proguard-android-optimize.txt'),
                    'proguard-rules.pro'
        }
    }
```
