### ISSUE TITLE
ios notify error when in background process. plugin workmanager

### ISSUE THREAD

**Issue by lucmertins** [MaikuB/flutter_local_notifications#549]
This https://github.com/lucmertins/bgnotif.git uses the workmanager plugin to perform background processes.

Android works like a charme from button and background actions.
IOS only works using the button. Using simulator  [https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md#testing-background-fetch]( https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md#testing-background-fetch)

this error occurs:

`2020-03-26 14:36:31.754668-0300 Runner[27396:278535] SwiftWorkmanagerPlugin - DebugNotificationHelper scheduleNotification(identifier:title:body:icon:): plugin is not running in debug mode or on iOS 9 or lower
2020-03-26 14:36:31.973465-0300 Runner[27396:279367] flutter: ************* 1 background task *****  iOSPerformFetch
2020-03-26 14:36:31.975124-0300 Runner[27396:279367] flutter: showNotification
2020-03-26 14:36:31.988693-0300 Runner[27396:279367] flutter: notification failed - MissingPluginException(No implementation found for method show on channel dexterous.com/flutter/local_notifications)
2020-03-26 14:36:31.989253-0300 Runner[27396:279367] flutter: Stack: 
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
<asynchronous suspension>
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
#2      IOSFlutterLocalNotificationsPlugin.show (package:flutter_local_notifications/src/platform_flutter_local_notifications.dart:268:21)
#3      FlutterLocalNotificationsPlugin.show (package:flutter_local_notifications/src/flutter_local_notifications_plugin.dart:142:13)
#4      showNotification (package:bgnotif/Notification.dart:76:41)
#5      callbackDispatcher.<anonymous closure> (package:bgnotif/WorkBackground.dart:30:13)
#6      Workmanager.executeTask.<anonymous closure> (package:workmanager/src/workmanager.dart:80:28)
#7      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:409:55)
#8      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:377:54)
#9      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:199:33)
#10     _invoke3.<anonymous closure> (dart:ui/hooks.dart:305:15)
#11     _rootRun (dart:async/zone.dart:1133:13)
#12     _CustomZone.run (dart:async/zone.dart:1026:19)
#13     _CustomZone.runGuarded (dart:async/zone.dart:928:7)
#14     _invoke3 (dart:ui/hooks.dart:304:10)
#15     _dispatchPlatformMessage (dart:ui/hooks.dart:164:5)
2020-03-26 14:36:31.989683-0300 Runner[27396:279367] flutter: ************* 3 background task  end
2020-03-26 14:36:31.997324-0300 Runner[27396:278535] [<workmanager.SwiftWorkmanagerPlugin: 0x60000139e730>] application(_:performFetchWithCompletionHandler:) -> UIBackgroundFetchResult.newData (finished in 0.24 seconds)
2020-03-26 14:36:31.997776-0300 Runner[27396:278535] SwiftWorkmanagerPlugin - DebugNotificationHelper scheduleNotification(identifier:title:body:icon:): plugin is not running in debug mode or on iOS 9 or lower
`
Is there some issue with background process and notification on ios?

**Comment by MaikuB** [comment]
I've never used that plugin so can't tell you if there are issues. I believe others have gotten it working successfully. Some setup is generally required for background isolates to be able to call plugin code. From looking at your repository, it appears you haven't completed the setup that is mentioned in their guide

**Comment by lucmertins** [comment]
You are right! My fail.
Thanks a lot!
P.S. I fixed the link.
