### ISSUE TITLE
Crashes with no notifications on Android 8.0 (Oreo)

### ISSUE THREAD

**Issue by Simpler1** [MaikuB/flutter_local_notifications#58]
Ran the example app on my Samsung S7 Edge with Android 8.0 (Oreo) and no notifications are sent.

Clicking the first button produces the following output, but no notifications appear:

```
E/MethodChannel#dexterous.com/flutter/local_notifications(16770): Failed to handle method call
E/MethodChannel#dexterous.com/flutter/local_notifications(16770): java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(channel=your channel id pri=1 contentView=null vibrate=null sound=null defaults=0x0 flags=0x10 color=0x00000000 number=0 vis=PRIVATE semFlags=0x0 semPriority=0 semMissedCount=0)
E/MethodChannel#dexterous.com/flutter/local_notifications(16770): 	at android.app.NotificationManager.notifyAsUser(NotificationManager.java:335)
E/MethodChannel#dexterous.com/flutter/local_notifications(16770): 	at android.app.NotificationManager.notify(NotificationManager.java:299)
E/MethodChannel#dexterous.com/flutter/local_notifications(16770): 	at android.support.v4.app.NotificationManagerCompat.notify(NotificationManagerCompat.java:210)
E/MethodChannel#dexterous.com/flutter/local_notifications(16770): 	at android.support.v4.app.NotificationManagerCompat.notify(NotificationManagerCompat.java:194)
E/MethodChannel#dexterous.com/flutter/local_notifications(16770): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(FlutterLocalNotificationsPlugin.java:528)
E/MethodChannel#dexterous.com/flutter/local_notifications(16770): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:459)
E/MethodChannel#dexterous.com/flutter/local_notifications(16770): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/MethodChannel#dexterous.com/flutter/local_notifications(16770): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:136)
E/MethodChannel#dexterous.com/flutter/local_notifications(16770): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#dexterous.com/flutter/local_notifications(16770): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/MethodChannel#dexterous.com/flutter/local_notifications(16770): 	at android.os.Looper.loop(Looper.java:142)
E/MethodChannel#dexterous.com/flutter/local_notifications(16770): 	at android.app.ActivityThread.main(ActivityThread.java:6944)
E/MethodChannel#dexterous.com/flutter/local_notifications(16770): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#dexterous.com/flutter/local_notifications(16770): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
E/MethodChannel#dexterous.com/flutter/local_notifications(16770): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Lost connection to device.
Exited (sigterm)
```

**Comment by MaikuB** [comment]
I've tried it right now and didn't run into issues. Did you run the entire example app that is on the github repository or did you copy just copy the example Dart code? The latter won't work as there's setup required for each platform (see the README)

**Comment by Simpler1** [comment]
@MaikuB Thanks for the quick response.  You are correct.  I was trying to run this by just copy/paste of the example on https://pub.dartlang.org/packages/flutter_local_notifications#-example-tab-

After cloning the GitHub repository and building from the example directory, it works properly.
