### ISSUE TITLE
Warnings in Google Play Pre-Launch-Reports

### ISSUE THREAD

**Issue by nohli** [MaikuB/flutter_local_notifications#623]
Not sure what this means. Maybe has something to do with this plugin (and someone can help)?
Latest flutter stable, build with Codemagic.

--------------------------

```
API Lsun/misc/Unsafe;->allocateInstance(Ljava/lang/Class;)Ljava/lang/Object;
8 occurrences identified. Only unique stack traces are shown.
```

<details>
  <summary>Stacktrace 1</summary>

```
 StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Lsun/misc/Unsafe;->allocateInstance(Ljava/lang/Class;)Ljava/lang/Object;
	at android.os.StrictMode.lambda$static$1(StrictMode.java:407)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Class.java)
	at java.lang.Class.getPublicMethodRecursive(Class.java:2079)
	at java.lang.Class.getMethod(Class.java:2066)
	at java.lang.Class.getMethod(Class.java:1693)
	at com.google.gson.internal.UnsafeAllocator.a(UnsafeAllocator.java:32)
	at com.google.gson.internal.ConstructorConstructor$14.<init>(ConstructorConstructor.java:7)
	at com.google.gson.internal.ConstructorConstructor.newUnsafeAllocator(ConstructorConstructor.java:2)
	at com.google.gson.internal.ConstructorConstructor.a(ConstructorConstructor.java:54)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:16)
	at com.google.gson.Gson.a(Gson.java:35)
	at com.dexterous.flutterlocalnotifications.RuntimeTypeAdapterFactory.create(RuntimeTypeAdapterFactory.java:52)
	at com.google.gson.Gson.a(Gson.java:74)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(ReflectiveTypeAdapterFactory.java:41)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(ReflectiveTypeAdapterFactory.java:123)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:22)
	at com.google.gson.Gson.a(Gson.java:74)
	at com.google.gson.Gson.a(Gson.java:4)
	at com.google.gson.Gson.a(Gson.java:8)
	at com.google.gson.Gson.a(Gson.java:5)
	at com.google.gson.Gson.a(Gson.java:13)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.repeatNotification(FlutterLocalNotificationsPlugin.java:4)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.repeat(FlutterLocalNotificationsPlugin.java:19)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:165)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:17)
	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:57)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:4)
	at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
	at android.os.MessageQueue.next(MessageQueue.java:336)
	at android.os.Looper.loop(Looper.java:174)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

</details>
<details>
  <summary>Stacktrace 2</summary>

```
 StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Lsun/misc/Unsafe;->allocateInstance(Ljava/lang/Class;)Ljava/lang/Object;
	at android.os.StrictMode.lambda$static$1(StrictMode.java:407)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Class.java)
	at java.lang.Class.getPublicMethodRecursive(Class.java:2079)
	at java.lang.Class.getMethod(Class.java:2066)
	at java.lang.Class.getMethod(Class.java:1693)
	at com.google.gson.internal.UnsafeAllocator.a(UnsafeAllocator.java:32)
	at com.google.gson.internal.ConstructorConstructor$14.<init>(ConstructorConstructor.java:7)
	at com.google.gson.internal.ConstructorConstructor.newUnsafeAllocator(ConstructorConstructor.java:2)
	at com.google.gson.internal.ConstructorConstructor.a(ConstructorConstructor.java:54)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:16)
	at com.google.gson.Gson.a(Gson.java:74)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:26)
	at com.google.gson.Gson.a(Gson.java:74)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(ReflectiveTypeAdapterFactory.java:41)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(ReflectiveTypeAdapterFactory.java:123)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:22)
	at com.google.gson.Gson.a(Gson.java:35)
	at com.dexterous.flutterlocalnotifications.RuntimeTypeAdapterFactory.create(RuntimeTypeAdapterFactory.java:52)
	at com.google.gson.Gson.a(Gson.java:74)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(ReflectiveTypeAdapterFactory.java:41)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(ReflectiveTypeAdapterFactory.java:123)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:22)
	at com.google.gson.Gson.a(Gson.java:74)
	at com.google.gson.Gson.a(Gson.java:4)
	at com.google.gson.Gson.a(Gson.java:8)
	at com.google.gson.Gson.a(Gson.java:5)
	at com.google.gson.Gson.a(Gson.java:13)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.repeatNotification(FlutterLocalNotificationsPlugin.java:4)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.repeat(FlutterLocalNotificationsPlugin.java:19)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:165)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:17)
	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:57)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:4)
	at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
	at android.os.MessageQueue.next(MessageQueue.java:336)
	at android.os.Looper.loop(Looper.java:174)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```
</details>
<details>
  <summary>Stacktrace 3</summary>

```
 StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Lsun/misc/Unsafe;->allocateInstance(Ljava/lang/Class;)Ljava/lang/Object;
	at android.os.StrictMode.lambda$static$1(StrictMode.java:407)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Class.java)
	at java.lang.Class.getPublicMethodRecursive(Class.java:2079)
	at java.lang.Class.getMethod(Class.java:2066)
	at java.lang.Class.getMethod(Class.java:1693)
	at com.google.gson.internal.UnsafeAllocator.a(UnsafeAllocator.java:32)
	at com.google.gson.internal.ConstructorConstructor$14.<init>(ConstructorConstructor.java:7)
	at com.google.gson.internal.ConstructorConstructor.newUnsafeAllocator(ConstructorConstructor.java:2)
	at com.google.gson.internal.ConstructorConstructor.a(ConstructorConstructor.java:54)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:16)
	at com.google.gson.Gson.a(Gson.java:74)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(ReflectiveTypeAdapterFactory.java:41)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(ReflectiveTypeAdapterFactory.java:123)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:22)
	at com.google.gson.Gson.a(Gson.java:74)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:26)
	at com.google.gson.Gson.a(Gson.java:74)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(ReflectiveTypeAdapterFactory.java:41)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(ReflectiveTypeAdapterFactory.java:123)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:22)
	at com.google.gson.Gson.a(Gson.java:35)
	at com.dexterous.flutterlocalnotifications.RuntimeTypeAdapterFactory.create(RuntimeTypeAdapterFactory.java:52)
	at com.google.gson.Gson.a(Gson.java:74)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(ReflectiveTypeAdapterFactory.java:41)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(ReflectiveTypeAdapterFactory.java:123)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:22)
	at com.google.gson.Gson.a(Gson.java:74)
	at com.google.gson.Gson.a(Gson.java:4)
	at com.google.gson.Gson.a(Gson.java:8)
	at com.google.gson.Gson.a(Gson.java:5)
	at com.google.gson.Gson.a(Gson.java:13)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.repeatNotification(FlutterLocalNotificationsPlugin.java:4)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.repeat(FlutterLocalNotificationsPlugin.java:19)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:165)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:17)
	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:57)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:4)
	at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
	at android.os.MessageQueue.next(MessageQueue.java:336)
	at android.os.Looper.loop(Looper.java:174)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

</details>
<details>
  <summary>Stacktrace 4</summary>

```
 StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Lsun/misc/Unsafe;->allocateInstance(Ljava/lang/Class;)Ljava/lang/Object;
	at android.os.StrictMode.lambda$static$1(StrictMode.java:407)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Class.java)
	at java.lang.Class.getPublicMethodRecursive(Class.java:2079)
	at java.lang.Class.getMethod(Class.java:2066)
	at java.lang.Class.getMethod(Class.java:1693)
	at com.google.gson.internal.UnsafeAllocator.a(UnsafeAllocator.java:32)
	at com.google.gson.internal.ConstructorConstructor$14.<init>(ConstructorConstructor.java:7)
	at com.google.gson.internal.ConstructorConstructor.newUnsafeAllocator(ConstructorConstructor.java:2)
	at com.google.gson.internal.ConstructorConstructor.a(ConstructorConstructor.java:54)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:16)
	at com.google.gson.Gson.a(Gson.java:74)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:18)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.a(ReflectiveTypeAdapterFactory.java:28)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:42)
	at com.google.gson.Gson.a(Gson.java:34)
	at com.google.gson.Gson.a(Gson.java:8)
	at com.google.gson.Gson.a(Gson.java:5)
	at com.google.gson.Gson.a(Gson.java:13)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.repeatNotification(FlutterLocalNotificationsPlugin.java:4)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.repeat(FlutterLocalNotificationsPlugin.java:19)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:165)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:17)
	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:57)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:4)
	at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
	at android.os.MessageQueue.next(MessageQueue.java:336)
	at android.os.Looper.loop(Looper.java:174)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

</details>

--------------------------

```
API Lsun/misc/Unsafe;->theUnsafe:Lsun/misc/Unsafe;
8 occurrences identified. Only unique stack traces are shown.
```

<details>
  <summary>Stacktrace 1</summary>

```
  StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Lsun/misc/Unsafe;->theUnsafe:Lsun/misc/Unsafe;
	at android.os.StrictMode.lambda$static$1(StrictMode.java:407)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredField(Class.java)
	at com.google.gson.internal.UnsafeAllocator.a(UnsafeAllocator.java:13)
	at com.google.gson.internal.ConstructorConstructor$14.<init>(ConstructorConstructor.java:7)
	at com.google.gson.internal.ConstructorConstructor.newUnsafeAllocator(ConstructorConstructor.java:2)
	at com.google.gson.internal.ConstructorConstructor.a(ConstructorConstructor.java:54)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:16)
	at com.google.gson.Gson.a(Gson.java:35)
	at com.dexterous.flutterlocalnotifications.RuntimeTypeAdapterFactory.create(RuntimeTypeAdapterFactory.java:52)
	at com.google.gson.Gson.a(Gson.java:74)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(ReflectiveTypeAdapterFactory.java:41)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(ReflectiveTypeAdapterFactory.java:123)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:22)
	at com.google.gson.Gson.a(Gson.java:74)
	at com.google.gson.Gson.a(Gson.java:4)
	at com.google.gson.Gson.a(Gson.java:8)
	at com.google.gson.Gson.a(Gson.java:5)
	at com.google.gson.Gson.a(Gson.java:13)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.repeatNotification(FlutterLocalNotificationsPlugin.java:4)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.repeat(FlutterLocalNotificationsPlugin.java:19)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:165)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:17)
	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:57)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:4)
	at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
	at android.os.MessageQueue.next(MessageQueue.java:336)
	at android.os.Looper.loop(Looper.java:174)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

</details>
<details>
  <summary>Stacktrace 2</summary>

```
 StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Lsun/misc/Unsafe;->theUnsafe:Lsun/misc/Unsafe;
	at android.os.StrictMode.lambda$static$1(StrictMode.java:407)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredField(Class.java)
	at com.google.gson.internal.UnsafeAllocator.a(UnsafeAllocator.java:13)
	at com.google.gson.internal.ConstructorConstructor$14.<init>(ConstructorConstructor.java:7)
	at com.google.gson.internal.ConstructorConstructor.newUnsafeAllocator(ConstructorConstructor.java:2)
	at com.google.gson.internal.ConstructorConstructor.a(ConstructorConstructor.java:54)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:16)
	at com.google.gson.Gson.a(Gson.java:74)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:26)
	at com.google.gson.Gson.a(Gson.java:74)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(ReflectiveTypeAdapterFactory.java:41)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(ReflectiveTypeAdapterFactory.java:123)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:22)
	at com.google.gson.Gson.a(Gson.java:35)
	at com.dexterous.flutterlocalnotifications.RuntimeTypeAdapterFactory.create(RuntimeTypeAdapterFactory.java:52)
	at com.google.gson.Gson.a(Gson.java:74)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(ReflectiveTypeAdapterFactory.java:41)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(ReflectiveTypeAdapterFactory.java:123)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:22)
	at com.google.gson.Gson.a(Gson.java:74)
	at com.google.gson.Gson.a(Gson.java:4)
	at com.google.gson.Gson.a(Gson.java:8)
	at com.google.gson.Gson.a(Gson.java:5)
	at com.google.gson.Gson.a(Gson.java:13)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.repeatNotification(FlutterLocalNotificationsPlugin.java:4)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.repeat(FlutterLocalNotificationsPlugin.java:19)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:165)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:17)
	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:57)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:4)
	at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
	at android.os.MessageQueue.next(MessageQueue.java:336)
	at android.os.Looper.loop(Looper.java:174)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```
</details>
<details>
  <summary>Stacktrace 3</summary>

```
 StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Lsun/misc/Unsafe;->theUnsafe:Lsun/misc/Unsafe;
	at android.os.StrictMode.lambda$static$1(StrictMode.java:407)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredField(Class.java)
	at com.google.gson.internal.UnsafeAllocator.a(UnsafeAllocator.java:13)
	at com.google.gson.internal.ConstructorConstructor$14.<init>(ConstructorConstructor.java:7)
	at com.google.gson.internal.ConstructorConstructor.newUnsafeAllocator(ConstructorConstructor.java:2)
	at com.google.gson.internal.ConstructorConstructor.a(ConstructorConstructor.java:54)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:16)
	at com.google.gson.Gson.a(Gson.java:74)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(ReflectiveTypeAdapterFactory.java:41)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(ReflectiveTypeAdapterFactory.java:123)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:22)
	at com.google.gson.Gson.a(Gson.java:74)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:26)
	at com.google.gson.Gson.a(Gson.java:74)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(ReflectiveTypeAdapterFactory.java:41)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(ReflectiveTypeAdapterFactory.java:123)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:22)
	at com.google.gson.Gson.a(Gson.java:35)
	at com.dexterous.flutterlocalnotifications.RuntimeTypeAdapterFactory.create(RuntimeTypeAdapterFactory.java:52)
	at com.google.gson.Gson.a(Gson.java:74)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(ReflectiveTypeAdapterFactory.java:41)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(ReflectiveTypeAdapterFactory.java:123)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:22)
	at com.google.gson.Gson.a(Gson.java:74)
	at com.google.gson.Gson.a(Gson.java:4)
	at com.google.gson.Gson.a(Gson.java:8)
	at com.google.gson.Gson.a(Gson.java:5)
	at com.google.gson.Gson.a(Gson.java:13)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.repeatNotification(FlutterLocalNotificationsPlugin.java:4)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.repeat(FlutterLocalNotificationsPlugin.java:19)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:165)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:17)
	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:57)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:4)
	at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
	at android.os.MessageQueue.next(MessageQueue.java:336)
	at android.os.Looper.loop(Looper.java:174)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

</details>
<details>
  <summary>Stacktrace 4</summary>

```
 StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Lsun/misc/Unsafe;->theUnsafe:Lsun/misc/Unsafe;
	at android.os.StrictMode.lambda$static$1(StrictMode.java:407)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredField(Class.java)
	at com.google.gson.internal.UnsafeAllocator.a(UnsafeAllocator.java:13)
	at com.google.gson.internal.ConstructorConstructor$14.<init>(ConstructorConstructor.java:7)
	at com.google.gson.internal.ConstructorConstructor.newUnsafeAllocator(ConstructorConstructor.java:2)
	at com.google.gson.internal.ConstructorConstructor.a(ConstructorConstructor.java:54)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:16)
	at com.google.gson.Gson.a(Gson.java:74)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:18)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.a(ReflectiveTypeAdapterFactory.java:28)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:42)
	at com.google.gson.Gson.a(Gson.java:34)
	at com.google.gson.Gson.a(Gson.java:8)
	at com.google.gson.Gson.a(Gson.java:5)
	at com.google.gson.Gson.a(Gson.java:13)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.repeatNotification(FlutterLocalNotificationsPlugin.java:4)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.repeat(FlutterLocalNotificationsPlugin.java:19)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:165)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:17)
	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:57)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:4)
	at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
	at android.os.MessageQueue.next(MessageQueue.java:336)
	at android.os.Looper.loop(Looper.java:174)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

</details>

**Comment by MaikuB** [comment]
You can google the warnings, which appears to show they warnings that in this case is likely not a cause for concern. It originates from a library used as part of saving info on scheduled notifications and this library (gson) is maintained by Google. A related issue on this can be found on their repository here https://github.com/google/gson/issues/1387
