### ISSUE TITLE
I get an error "The resource %s could not be found."

### ISSUE THREAD

**Issue by sinano1107** [MaikuB/flutter_local_notifications#645]
I didn't enter [%s], I get an error.
please help me.

My code.
```
import 'dart:async';
import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:racommu/models/schedule.dart';

class NotificationsService {
  FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin;

  void init() {
    var initializationSettingsAndroid =
        AndroidInitializationSettings('icon');

    var initializationSettingsIOS = IOSInitializationSettings();

    var initializationSettings = InitializationSettings(
        initializationSettingsAndroid, initializationSettingsIOS);

    flutterLocalNotificationsPlugin = FlutterLocalNotificationsPlugin();

    flutterLocalNotificationsPlugin.initialize(initializationSettings);
  }

  Future<void> scheduleNotification({
    @required int id,
    @required DateTime scheduledDate,
    @required String title,
    @required String body,
  }) async {
    var vibrationPattern = Int64List(4);
    vibrationPattern[0] = 0;
    vibrationPattern[1] = 1000;
    vibrationPattern[2] = 5000;
    vibrationPattern[3] = 2000;

    var androidPlatformChannelSpecifics = AndroidNotificationDetails(
        'your other channel id',
        'your other channel name',
        'your other channel description',
        icon: 'icon',
        sound: RawResourceAndroidNotificationSound('slow_spring_board'),
        largeIcon: DrawableResourceAndroidBitmap('icon'),
        vibrationPattern: vibrationPattern,
        enableLights: true,
        color: const Color.fromARGB(255, 255, 0, 0),
        ledColor: const Color.fromARGB(255, 255, 0, 0),
        ledOnMs: 1000,
        ledOffMs: 500);
    var iOSPlatformChannelSpecifics =
        IOSNotificationDetails(sound: 'slow_spring_board.aiff');
    var platformChannelSpecifics = NotificationDetails(
        androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);
    await flutterLocalNotificationsPlugin.schedule(
      id,
      title,
      body,
      scheduledDate,
      platformChannelSpecifics,
    ).then((value) => print('通知設定完了'));
  }
```

**Comment by sinano1107** [comment]
My error code.
```
E/flutter (25169): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(INVALID_SOUND, The resource %s could not be found. Please make sure it has been added as a raw resource to your Android head project., null)
E/flutter (25169): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (25169): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter (25169): <asynchronous suspension>
E/flutter (25169): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (25169): #3      AndroidFlutterLocalNotificationsPlugin.schedule (package:flutter_local_notifications/src/platform_flutter_local_notifications.dart:82:20)
E/flutter (25169): #4      FlutterLocalNotificationsPlugin.schedule (package:flutter_local_notifications/src/flutter_local_notifications_plugin.dart:173:12)
E/flutter (25169): #5      NotificationsService.scheduleNotification (package:racommu/services/notifications_service.dart:54:43)
E/flutter (25169): #6      NotificationsService.settingScheduleNotifications (package:racommu/services/not

```

**Comment by sinano1107** [comment]
This is a decline in android.

**Comment by MaikuB** [comment]
Looks like I need to fix a problem with the error message but the error is about how the sound file you specified (slow_spring_board) doesn't exist as a resource in your application, which you'll need to fix

**Comment by sinano1107** [comment]
You were right!
Thank you, thank you so much!
