### ISSUE TITLE
PlatformException(error, User's name must not be empty

### ISSUE THREAD

**Issue by nemoryoliver** [MaikuB/flutter_local_notifications#788]
I've been getting a lot of these crashlytic reports. It's not a fatal crash though.

```
PlatformException(error, User's name must not be empty., null, java.lang.IllegalArgumentException: User's name must not be empty. at androidx.core.app.j$g.<init>(Unknown Source:27) at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.setMessagingStyle(Unknown Source:12) at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.setStyle(Unknown Source:30) at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(Unknown Source:209) at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(Unknown Source:0) at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.show(Unknown Source:14) at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(Unknown Source:173) at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(Unknown Source:17) at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(Unknown Source:57) at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4) at android.os.MessageQueue.nativePollOnce(Native Method) at android.os.MessageQueue.next(MessageQueue.java:325) at android.os.Looper.loop(Looper.java:151) at android.app.ActivityThread.main(ActivityThread.java:6724) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810) )

StandardMethodCodec.decodeEnvelope (StandardMethodCodec.java:582)
MethodChannel._invokeMethod (MethodChannel.java:159)
FlutterLocalNotificationsPlugin.show (FlutterLocalNotificationsPlugin.java:134)
NotificationsManager.notifyFacebook (NotificationsManager.java:82)
```

**Comment by MaikuB** [comment]
Did you try updating the code so the exception goes away? The exception mentions what the problem i.e. User's name must not be empty

**Comment by MaikuB** [comment]
Closing due to lack of further response. Note that this is an issue that your application needs to fix as it's not an issue with the plugin
