### ISSUE TITLE
Unable to start receiver com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver

### ISSUE THREAD

**Issue by ariona** [MaikuB/flutter_local_notifications#838]
Error when receiving local notification, caused force close

```bash
E/AndroidRuntime(21528): java.lang.RuntimeException: Unable to start receiver com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
E/AndroidRuntime(21528): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3831)
E/AndroidRuntime(21528): 	at android.app.ActivityThread.access$1500(ActivityThread.java:220)
E/AndroidRuntime(21528): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1894)
E/AndroidRuntime(21528): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(21528): 	at android.os.Looper.loop(Looper.java:224)
E/AndroidRuntime(21528): 	at android.app.ActivityThread.main(ActivityThread.java:7520)
E/AndroidRuntime(21528): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(21528): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/AndroidRuntime(21528): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/AndroidRuntime(21528): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
E/AndroidRuntime(21528): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.setSmallIcon(FlutterLocalNotificationsPlugin.java:216)
E/AndroidRuntime(21528): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(FlutterLocalNotificationsPlugin.java:166)

```

**Comment by MaikuB** [comment]
A stack trace doesn't say much. You've likely not configured the icon correctly on your end, please take a closer at your end using the readme and example app to cross-reference with what you've done. If you're certain that've configured everything correctly then provide a minimal, complete sample app that can reproduce the issue

**Comment by ariona** [comment]
i have solved this issue by prefixing icon name with the folder name `drawable/icon_name`
```dart
const AndroidInitializationSettings initializationSettingsAndroid = AndroidInitializationSettings('drawable/app_icon');
```

Maybe the readme need to be updated on this one, since i am following the readme file.

**Comment by MaikuB** [comment]
Can you provide a link to a minimal app that reproduces this problem? No one else has mentioned needing to do this and if you looked at the example app in this repo, it doesn't need this either and runs fine
