### ISSUE TITLE
Java error when displaying scheduled notification

### ISSUE THREAD

**Issue by jesusrp98** [MaikuB/flutter_local_notifications#848]
Java is throwing error while trying to display a scheduled notification:

```
await _notifications.zonedSchedule(
        i,
        'Test',
        'Test',
        tz.TZDateTime.now(tz.local).add(const Duration(seconds: 5)),
        _notificationDetails,
        androidAllowWhileIdle: true,
        uiLocalNotificationDateInterpretation:
            UILocalNotificationDateInterpretation.wallClockTime,
);
```

```
  static final _notificationDetails = NotificationDetails(
    android: AndroidNotificationDetails(
      'channel.launches',
      'Launches notifications',
      'Stay up-to-date with upcoming SpaceX launches',
      importance: Importance.high,
    ),
    iOS: IOSNotificationDetails(),
  );
```

The init function:
```
Future<void> init() async {
    await _notifications.initialize(InitializationSettings(
      android: AndroidInitializationSettings('notification_launch'),
      iOS: IOSInitializationSettings(),
    ));
  }
```

Output:
```
E/AndroidRuntime( 7721): java.lang.RuntimeException: Unable to start receiver com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
E/AndroidRuntime( 7721): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3797)
E/AndroidRuntime( 7721): 	at android.app.ActivityThread.access$1400(ActivityThread.java:219)
E/AndroidRuntime( 7721): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1870)
E/AndroidRuntime( 7721): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime( 7721): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime( 7721): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime( 7721): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7721): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime( 7721): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/AndroidRuntime( 7721): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
E/AndroidRuntime( 7721): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.setSmallIcon(FlutterLocalNotificationsPlugin.java:216)
E/AndroidRuntime( 7721): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(FlutterLocalNotificationsPlugin.java:166)
E/AndroidRuntime( 7721): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(FlutterLocalNotificationsPlugin.java:759)
E/AndroidRuntime( 7721): 	at com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver.onReceive(ScheduledNotificationReceiver.java:44)
E/AndroidRuntime( 7721): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3788)
E/AndroidRuntime( 7721): 	... 8 more
I/Process ( 7721): Sending signal. PID: 7721 SIG: 9
Lost connection to device.
```

**Comment by MaikuB** [comment]
The icon can't be found as you don't await the initialisation so you're actually lucky that it use to work in your app before. Awaiting it should solve the problem like I tried with [this fork](https://github.com/MaikuB/spacex-go/tree/await_init) I spun up quickly. I'd suggest you set up your linters to catch when async code has been code without awaiting. Also, please be careful about using `tz.local` as I mentioned the following in the readme in [this](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#scheduling-a-notification) section

> The timezone package doesn't provide a way to obtain the current time zone on the device so developers will need to use platform channels (which is what the example app does) or use other packages that may be able to provide the information (e.g. flutter_native_timezone).

**Comment by jesusrp98** [comment]
Thanks! That solved my issues!
