### ISSUE TITLE
activity-alias support

### ISSUE THREAD

**Issue by crazecoder** [MaikuB/flutter_local_notifications#912]
```xml
<activity-alias
            android:name="DefaultAlias"
            android:enabled="true"
            android:targetActivity=".MainActivity">
```
```
java.lang.ClassNotFoundException: com.flutter.exanple.DefaultAlias
at java.lang.Class.classForName(Native Method)
at java.lang.Class.forName(Class.java:454)
at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.getMainActivityClass(FlutterLocalNotificationsPlugin.java:550)
```

**Comment by MaikuB** [comment]
Any chance you could submit a PR to resolve this issue? As Flutter's standard application template doesn't use aliases (at least last time I checked), this looks like a very specific use case. Furthermore,  this is new concept for me as I don't do "pure" native Android development

**Comment by MaikuB** [comment]
Closing as PR was merged and released. Thanks
