### ISSUE TITLE
HTTP not allowed error in example app

### ISSUE THREAD

**Issue by iqfareez** [MaikuB/flutter_local_notifications#924]
Tried to show big picture notification. 
The notification didn't show.

The log:

```
D/ViewRootImpl@e5e2f46[MainActivity](31169): ViewPostIme pointer 0
D/ViewRootImpl@e5e2f46[MainActivity](31169): ViewPostIme pointer 1
E/flutter (31169): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Bad state: Insecure HTTP is not allowed by platform: http://via.placeholder.com/48x48
E/flutter (31169): #0      _HttpClient._openUrl (dart:_http/http_impl.dart:2435:7)
E/flutter (31169): #1      _HttpClient.openUrl (dart:_http/http_impl.dart:2342:7)
E/flutter (31169): #2      IOClient.send (package:http/src/io_client.dart:31:37)
E/flutter (31169): #3      BaseClient._sendUnstreamed (package:http/src/base_client.dart:91:38)
E/flutter (31169): #4      BaseClient.get (package:http/src/base_client.dart:27:7)
E/flutter (31169): #5      get.<anonymous closure> (package:http/http.dart:46:36)
E/flutter (31169): #6      _withClient (package:http/http.dart:166:20)
E/flutter (31169): #7      get (package:http/http.dart:46:5)
E/flutter (31169): #8      _HomePageState._downloadAndSaveFile (package:flutter_local_notifications_example/main.dart:781:42)
E/flutter (31169): <asynchronous suspension>
E/flutter (31169): #9      _HomePageState._showBigPictureNotification (package:flutter_local_notifications_example/main.dart:788:40)
E/flutter (31169): #10     _HomePageState.build.<anonymous closure> (package:flutter_local_notifications_example/main.dart:410:33)
E/flutter (31169): #11     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:985:20)
E/flutter (31169): #12     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1101:38)
E/flutter (31169): #13     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
E/flutter (31169): #14     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
E/flutter (31169): #15     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
E/flutter (31169): #16     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:259:7)
E/flutter (31169): #17     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
E/flutter (31169): #18     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:372:20)
E/flutter (31169): #19     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:348:22)
E/flutter (31169): #20     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:268:11)
E/flutter (31169): #21     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:303:7)
E/flutter (31169): #22     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:267:5)
E/flutter (31169): #23     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:225:7)
E/flutter (31169): #24     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:208:7)
E/flutter (31169): #25     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (31169): #26     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (31169): #27     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (31169): #28     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter (31169): #29     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
E/flutter (31169):
```

**Comment by MaikuB** [comment]
Thanks for reporting this, looks like this things have changed since it was written. Would you consider submitting a PR for this?

**Comment by iqfareez** [comment]
on it!

**Comment by iqfareez** [comment]
Thank you for merging the PR #925 . Closing this.
