### ISSUE TITLE
java.lang.NoClassDefFoundError: java.util.Objects

### ISSUE THREAD

**Issue by vmeretin** [MaikuB/flutter_local_notifications#935]
App crashes on Android 4.3 (API 18)

```
E/flutter ( 3668): [ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(43)] java.lang.NoClassDefFoundError: java.util.Objects
E/flutter ( 3668):      at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.saveScheduledNotification(FlutterLocalNotificationsPlugin.java:420)
E/flutter ( 3668):      at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.zonedScheduleNotification(FlutterLocalNotificationsPlugin.java:333)
E/flutter ( 3668):      at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.zonedSchedule(FlutterLocalNotificationsPlugin.java:1007)
E/flutter ( 3668):      at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:922)
E/flutter ( 3668):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter ( 3668):      at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter ( 3668):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/flutter ( 3668):      at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 3668):      at android.os.MessageQueue.next(MessageQueue.java:132)
E/flutter ( 3668):      at android.os.Looper.loop(Looper.java:124)
E/flutter ( 3668):      at android.app.ActivityThread.main(ActivityThread.java:5103)
E/flutter ( 3668):      at java.lang.reflect.Method.invokeNative(Native Method)
E/flutter ( 3668):      at java.lang.reflect.Method.invoke(Method.java:525)
E/flutter ( 3668):      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
E/flutter ( 3668):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
E/flutter ( 3668):      at dalvik.system.NativeStart.main(Native Method)
```

- java.util.Objects are available above API 19 (Android 4.4.+) https://stackoverflow.com/questions/37778644/java-lang-noclassdeffounderror-java-util-objects/37778969
- your Android minSdkVersion = 16

**Comment by MaikuB** [comment]
Thanks for finding this. Strangely I couldn't reproduce the issue but I will make changes to fix this
