### ISSUE TITLE
Unable to start receiver - Invalid notification (no valid small icon):

### ISSUE THREAD

**Issue by mdmota** [MaikuB/flutter_local_notifications#948]
How do i solve this?
```
Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(channel=so_div_id pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x10 color=0x00000000 vis=PRIVATE semFlags=0x0 semPriority=0 semMissedCount=0)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4125)
       at android.app.ActivityThread.access$1400(ActivityThread.java:270)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2062)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7948)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```

**Comment by MaikuB** [comment]
This occurs when you haven't configured the icon correctly such as the name of the drawable resource that you've specified is incorrect. Based on what I've seen in the previous issue you had raised in https://github.com/MaikuB/flutter_local_notifications/issues/947, you haven't completed the release build configuration for your app as well. As mentioned in that thread, please refer to the docs as a warning had been put in the docs to say that failing to configure properly can lead to notifications not appearing at all

**Comment by mdmota** [comment]
Solved! thanks

**Comment by mdmota** [comment]
Crashlytics registered 11 failures in 8 different users in the last 7 days. All on Android 10

FlutterLocalNotificationsPlugin.java line 14

Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(channel=so_div_id pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x10 color=0x00000000 vis=PRIVATE)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3797)
       at android.app.ActivityThread.access$1400(ActivityThread.java:219)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1870)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7356)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by MaikuB** [comment]
If you released your app out to users whilst it had an issue and they scheduled notifications, the fix isn't going to be applied retroactively. If that's what you've done then that's an issue you'll need to solve within your application. Providing crashlytics logs doesn't necessarily indicate it's an issue with the plugin either. If you reckon you've come across a bug, you'll need to provide a link to link to a repository with a minimal app that can reproduce this problem

**Comment by MaikuB** [comment]
Closing as this appears to have originally been a configuration issue with no further info provided to indicate that a reproducible bug exists when an app has been configured properly
