### ISSUE TITLE
Gradle version is too low and does not allow debug build

### ISSUE THREAD

**Issue by Sadoge** [MaikuB/flutter_local_notifications#968]
When I run flutter build apk --debug on my CI (in gitlab), it does not allow me to build and gives me this error. 

> Minimum supported Gradle version is 5.6.4. Current version is 5.6.2. If using the gradle wrapper, try editing the distributionUrl in /opt/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-3.0.2/android/gradle/wrapper/gradle-wrapper.properties to gradle-5.6.4-all.zip

I have searched everywhere on google and flutter issues board on how to fix this but have been unable to make it work. Since the error specifically mentioned this package, I am posting it here.

I am running on flutter 1.22.5 and package version 3.0.2

```
 Building plugin flutter_local_notifications...
[   +3 ms] Running Gradle task 'assembleAarRelease'...
[        ] set `android.enableR8=true` in gradle.properties
[   +1 ms] /opt/flutter/bin/cache/artifacts/gradle_wrapper/gradle/wrapper/gradle-wrapper.jar mode: 33188 rw-r--r--.
[        ] /opt/flutter/bin/cache/artifacts/gradle_wrapper/gradlew mode: 33261 rwxr-xr-x.
[        ] /opt/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-3.0.2/android/gradlew mode: 33188 rw-r--r--.
[        ] Trying to give execute permission to /opt/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-3.0.2/android/gradlew.
[  +11 ms] /opt/flutter/bin/cache/artifacts/gradle_wrapper/gradlew.bat mode: 33188 rw-r--r--.
[   +6 ms] Using gradle from /opt/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-3.0.2/android/gradlew.
[        ] /opt/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-3.0.2/android/gradlew mode: 33261 rwxr-xr-x.
[        ] executing: [/opt/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-3.0.2/android/] /opt/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-3.0.2/android/gradlew -I=/opt/flutter/packages/flutter_tools/gradle/aar_init_script.gradle -Pflutter-root=/opt/flutter -Poutput-dir=/builds/beeple-mobile-app/beeple-mobile/build/app -Pis-plugin=true -PbuildNumber=1.0 -Pverbose=true -Ptarget-platform=android-arm,android-arm64,android-x64 assembleAarRelease
[+5726 ms] 
           FAILURE: Build failed with an exception.
           * Where:
           Build file '/opt/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-3.0.2/android/build.gradle' line: 22
           * What went wrong:
           A problem occurred evaluating root project 'flutter_local_notifications'.
           > Failed to apply plugin [id 'com.android.internal.version-check']
              > Minimum supported Gradle version is 5.6.4. Current version is 5.6.2. If using the gradle wrapper, try editing the distributionUrl in /opt/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-3.0.2/android/gradle/wrapper/gradle-wrapper.properties to gradle-5.6.4-all.zip
           * Try:
           Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
           * Get more help at https://help.gradle.org
           BUILD FAILED in 5s
[   +1 ms] Running Gradle task 'assembleAarRelease'... (completed in 5.7s)
[   +1 ms] 
           FAILURE: Build failed with an exception.
           * Where:
           Build file '/opt/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-3.0.2/android/build.gradle' line: 22
           * What went wrong:
           A problem occurred evaluating root project 'flutter_local_notifications'.
           > Failed to apply plugin [id 'com.android.internal.version-check']
              > Minimum supported Gradle version is 5.6.4. Current version is 5.6.2. If using the gradle wrapper, try editing the distributionUrl in /opt/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-3.0.2/android/gradle/wrapper/gradle-wrapper.properties to gradle-5.6.4-all.zip
           * Try:
           Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
           * Get more help at https://help.gradle.org
           BUILD FAILED in 5s
[  +11 ms] "flutter apk" took 414,927ms.
[  +21 ms] The plugin flutter_local_notifications could not be built due to the issue above.
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      buildPluginsAsAar (package:flutter_tools/src/android/gradle.dart:848:7)
           <asynchronous suspension>
           #2      buildGradleApp (package:flutter_tools/src/android/gradle.dart:261:11)
           #3      buildGradleApp (package:flutter_tools/src/android/gradle.dart:444:19)
           #4      _rootRunUnary (dart:async/zone.dart:1198:47)
           #5      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #6      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #8      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #9      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #10     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #11     _rootRun (dart:async/zone.dart:1190:13)
           #12     _CustomZone.run (dart:async/zone.dart:1093:19)
           #13     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #15     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #17     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
[   +3 ms] ensureAnalyticsSent: 1ms
[   +3 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

**Comment by MaikuB** [comment]
Without a link a repo and not being super familiar with the grade side, it's hard for me to tell. The plugin itself doesn't have a grade wrapper file though. My understanding is that you generally need to bump the Android gradle plugin for your app (e.g. https://github.com/MaikuB/flutter_local_notifications/blob/235538f246ac81544ead9b17b6d67f15d4bc34be/flutter_local_notifications/example/android/build.gradle#L8) so I'd suggest you try that. Perhaps you've got an app where that version is too low

**Comment by Sadoge** [comment]
@MaikuB I understand, its a private repo so it is not really possible to share the whole code. Since you say the package does not have it’s own gradle wrapper file, it’s unlikely that the issue is there. I will just look further into it. Thanks for the fast answer tho, I appreciate it a lot!

**Comment by Sadoge** [comment]
I’ll close it for now but report when I find a solution for others in the future

**Comment by MaikuB** [comment]
@Sadoge sure though a link to a minimal app that can reproduce the problem could also work though not sure I could think of a solution here. I believe the Android gradle plugin version used is what affects the version used when it comes to the Gradle distribution version and I think it would update the wrapper file automatically with that info

**Comment by Sadoge** [comment]
Finally was able to fix the issue. It apparently had to do with a "Too many open files issue". The error was not displayed on the screen but after searching for many hours we finally found where this issue can happen. Just increasing the amount of allowed opened files fixed the issue. Still unsure why the error was referring to this package specifically but will ask about that in the Flutter repo.
